export const researchAsOf = '2026-09-19';

export interface AffairsSource {
  title: string;
  url: string;
  publishedAt: string;
}

export interface AffairsBrief {
  id: string;
  region: 'Pakistan' | 'Middle East' | 'Russia and Ukraine';
  title: string;
  date: string;
  summary: string;
  whyPakistan: string;
  question: string;
  answerPoints: string[];
  watch: string[];
  sources: AffairsSource[];
}

export const researchCaveat = 'Research cutoff: 19 September 2026. This is an ISSB interview study snapshot, not a live news feed. A briefing date is its latest cited publication date, not proof that every event happened that day. Most reporting is from September 2026; the IMF decision of 8 May is explicitly background. Publication dates, reporting periods and republication dates can differ. UN verified casualty figures are minimum documented counts, not complete totals. Official statements and anonymous-source reports are attributed, not treated as independent proof. My assessment and Analysis label suggested reasoning, not news or an official Pakistani position. Limited-access pages are used only for details visible in indexed extracts; public syndications are preferred. Country-primer links support background geography, while dated briefings support current events. Inclusion does not mean a country is at war. Recheck the watch items before an interview, and say when you do not know.';

const evidence = {
  pakistanFinance: {
    title: 'Reuters via Geo News: Pakistan eyes bigger China swap line, expects US financing decision soon',
    url: 'https://www.geo.tv/latest/682472-pakistan-eyes-bigger-china-swap-line-expects-us-financing-decision-soon',
    publishedAt: '2026-09-17',
  },
  imfReview: {
    title: 'IMF: Third EFF review and second RSF review completed for Pakistan, background decision',
    url: 'https://www.imf.org/en/news/articles/2026/05/08/pr-26147-pakistan-imf-completes-3rd-rev-of-extended-arrangement-under-eff-and-2nd-rev-arrang-rsf',
    publishedAt: '2026-05-08',
  },
  pakistanAusterity: {
    title: 'Reuters via Al-Monitor: Pakistan announces austerity measures to conserve fuel',
    url: 'https://www.al-monitor.com/originals/2026/09/pakistan-announces-austerity-measures-conserve-fuel-gulf-conflict-spirals',
    publishedAt: '2026-09-17',
  },
  pakistanEnergy: {
    title: 'Reuters via The News: Energy disruption hits Bangladesh and Pakistan, republished 19 September from 17 September reporting',
    url: 'https://www.thenews.pk/print/1438088-energy-disruption-hits-bangladesh-and-pakistan-as-gulf-crisis-worsens',
    publishedAt: '2026-09-19',
  },
  pakistanFuelScheme: {
    title: 'Radio Pakistan: PM Special Fuel Relief Scheme underway, revised token and registration arrangements',
    url: 'https://www.radio.gov.pk/19-09-2026/prime-ministers-special-relief-scheme-launched-across-pakistan',
    publishedAt: '2026-09-19',
  },
  kohatAP: {
    title: 'Associated Press via NBC News: Bombing at mosque near police offices in Pakistan',
    url: 'https://www.nbcnews.com/world/pakistan/bombing-mosque-police-offices-pakistan-kills-least-21-rcna598611',
    publishedAt: '2026-09-18',
  },
  kohatUpdate: {
    title: 'Reuters citing AFP: Updated police account of the Kohat attack',
    url: 'https://www.reuters.com/world/asia-pacific/death-toll-31-pakistan-police-compound-attack-afp-reports-2026-09-19/',
    publishedAt: '2026-09-19',
  },
  pakistanFloods: {
    title: 'OCHA: Pakistan 2026 Monsoon Situation Update 7, data as of 14 September, published 15 September',
    url: 'https://www.unocha.org/publications/report/pakistan/pakistan-2026-monsoon-situation-updates-7-14-sep-2026',
    publishedAt: '2026-09-15',
  },
  pakistanResilience: {
    title: 'Radio Pakistan: NDMA chairman calls for long-term urban flood resilience planning',
    url: 'https://www.radio.gov.pk/18-09-2026/ndma-chairman-stresses-long-term-urban-resilience-planning-to-tackle-floods',
    publishedAt: '2026-09-18',
  },
  saudiPakistan: {
    title: 'Reuters analysis via Al-Monitor: Saudi-Houthi escalation tests Pakistan as defence partner and mediator',
    url: 'https://www.al-monitor.com/originals/2026/09/analysis-saudi-tensions-iran-backed-houthis-escalate-mediator-pakistan-faces',
    publishedAt: '2026-09-11',
  },
  pakistanMaritime: {
    title: 'Radio Pakistan: Pakistan supports Saudi sovereignty and calls for maritime de-escalation at the UN',
    url: 'https://www.radio.gov.pk/18-09-2026/pakistan-reaffirms-support-for-saudi-arabias-sovereignty-security',
    publishedAt: '2026-09-18',
  },
  hormuzTalks: {
    title: 'Reuters via Al-Monitor: Houthis attack Saudi Arabia as Gulf-Iran talks are postponed, updated 14 September',
    url: 'https://www.al-monitor.com/originals/2026/09/diplomacy-stumbles-postponement-meeting-strait-hormuz-proposal',
    publishedAt: '2026-09-14',
  },
  iranDiplomacy: {
    title: 'Al Jazeera explainer: Trump claims direct talks with Iran; Tehran has not confirmed their resumption',
    url: 'https://www.aljazeera.com/news/2026/9/17/trump-claims-direct-talks-with-iran-is-diplomacy-picking-up-again',
    publishedAt: '2026-09-17',
  },
  ochaSeptember17: {
    title: 'OCHA: Syria returns, Yemen aid access, Gaza health fuel and Lebanon education update',
    url: 'https://www.unocha.org/news/todays-top-news-syria-yemen-occupied-palestinian-territory-lebanon',
    publishedAt: '2026-09-17',
  },
  ochaSeptember18: {
    title: 'OCHA: Yemen displacement and Gaza shelter conditions, daily humanitarian update',
    url: 'https://www.unocha.org/news/todays-top-news-emen-occupied-palestinian-territory-democratic-republic-congo-haiti',
    publishedAt: '2026-09-18',
  },
  westBank: {
    title: 'OCHA oPt: Humanitarian Situation Report for 11 September, webpage published 12 September',
    url: 'https://www.ochaopt.org/content/humanitarian-situation-report-11-september-2026',
    publishedAt: '2026-09-12',
  },
  regionalStatement: {
    title: 'Türkiye Foreign Ministry: Joint statement by eight foreign ministers on Palestine and settlement trade',
    url: 'https://www.mfa.gov.tr/joint-statement-by-the-foreign-ministers-of-turkiye-egypt-indonesia-jordan-pakistan-qatar-saudi-arabia-and-uae-9-september-2026.en.mfa',
    publishedAt: '2026-09-09',
  },
  regionalReporting: {
    title: 'Arab News: Arab and Muslim nations welcome UK trade ban on Israeli settlement goods',
    url: 'https://www.arabnews.com/saudi-arabia/saudi-arabia-arab-and-muslim-states-welcome-uk-trade-ban-on-israeli-settlement-goods-3001100',
    publishedAt: '2026-09-09',
  },
  lebanonUNIFIL: {
    title: 'Reuters via Al-Monitor: Residents of Israeli-occupied southern Lebanon fear UNIFIL withdrawal',
    url: 'https://www.al-monitor.com/index%2ephp/originals/2026/09/lebanese-israeli-occupied-south-fear-bleak-future-once-un-peacekeepers-withdraw',
    publishedAt: '2026-09-16',
  },
  iraqMilitias: {
    title: 'Reuters via The Business Standard: Why Iraq faces difficulty disarming Iran-aligned militias',
    url: 'https://www.tbsnews.net/worldbiz/middle-east/why-us-ally-iraq-unable-disarm-irans-militia-allies-1538346',
    publishedAt: '2026-09-09',
  },
  iraqExports: {
    title: 'Reuters: Iraq trials trucking southern crude north for exports through Türkiye',
    url: 'https://www.reuters.com/business/energy/iraq-trucks-southern-crude-north-bid-raise-exports-via-turkey-2026-09-16/',
    publishedAt: '2026-09-16',
  },
  gulfInterceptions: {
    title: 'Asharq Al-Awsat: Jordan, Kuwait and Bahrain report interceptions; Iran reports attacks on US bases',
    url: 'https://english.aawsat.com/gulf/5313734-iranian-drone-and-missile-attacks-target-kuwait-jordan-bahrain-and-iraq',
    publishedAt: '2026-09-02',
  },
  gulfAFPAP: {
    title: 'Arab News with AFP and AP: Kuwait condemns attacks; Iran says it targeted US bases in Kuwait and UAE',
    url: 'https://www.arabnews.com/middle-east/kuwait-says-intercepting-iranian-missile-and-drone-attack-3000289',
    publishedAt: '2026-09-03',
  },
  uaeOilTrade: {
    title: 'Reuters via MarketScreener: Sources describe ADNOC purchases of discounted Iraqi crude',
    url: 'https://www.marketscreener.com/news/uae-s-adnoc-buys-millions-of-barrels-of-iraqi-crude-sources-say-ce785bdddd8dfe21',
    publishedAt: '2026-09-15',
  },
  ukraineDiplomacy: {
    title: 'Reuters via Asharq Al-Awsat: US envoys present peace ideas, but no breakthrough',
    url: 'https://english.aawsat.com/world/5315947-zelenskiy-says-us-envoys-presented-%E2%80%98decent-ideas%E2%80%99-peace-talks',
    publishedAt: '2026-09-08',
  },
  ukraineEnergyPosition: {
    title: 'Anadolu: Zelenskyy makes an energy truce conditional on Russia stopping corresponding attacks',
    url: 'https://www.aa.com.tr/en/russia-ukraine-war/zelenskyy-doubts-russia-will-honor-energy-target-truce-announced-by-trump/4057261',
    publishedAt: '2026-09-15',
  },
  russiaEnergyPosition: {
    title: 'Anadolu: Kremlin backs the idea of an energy ceasefire and says talks with the US continue',
    url: 'https://www.aa.com.tr/en/asia-pacific/russia-backs-trumps-idea-of-energy-ceasefire-with-ukraine/4057956',
    publishedAt: '2026-09-15',
  },
  ukraineCivilians: {
    title: 'OHCHR Ukraine: Protection of civilians in armed conflict, August 2026 report',
    url: 'https://ukraine.ohchr.org/en/Protection-of-Civilians-in-Armed-Conflict-August-2026',
    publishedAt: '2026-09-16',
  },
  ukraineAccountability: {
    title: 'OHCHR Ukraine: Findings on conflict-related sexual violence, non-graphic briefing',
    url: 'https://ukraine.ohchr.org/en/UN-Human-Rights-report-details-shocking-pattern-of-sexual-violence-amid-Russia-s-full-scale-armed-attack-on-Ukraine',
    publishedAt: '2026-09-18',
  },
  russiaSanctionsReuters: {
    title: 'Reuters: White House says new Russia sanctions bill signed into law',
    url: 'https://www.reuters.com/world/us/trump-signs-russia-sanctions-bill-into-law-2026-09-18/',
    publishedAt: '2026-09-18',
  },
  russiaSanctionsAA: {
    title: 'Anadolu: New law authorizes Russia sanctions and targeted tariffs, signed 18 September',
    url: 'https://aa.com.tr/en/world/trump-signs-russia-sanctions-bill-into-law-white-house/4061647',
    publishedAt: '2026-09-19',
  },
} satisfies Record<string, AffairsSource>;

export const currentAffairs: AffairsBrief[] = [
  {
    id: 'pakistan-economy-financing-imf',
    region: 'Pakistan',
    title: 'Economy: new financing requests are not money already received',
    date: '2026-09-17',
    summary: 'Reported facts: Finance Minister Muhammad Aurangzeb told Reuters that Pakistan had fully drawn its 30 billion yuan China swap line and would seek an expansion when it expires in 2027. He expected a US response to a proposed $10 billion exchange-stabilisation facility within two months. An IMF mission was due the following week for the fourth review of the $7 billion programme. These were plans and expectations, not fresh approvals.',
    whyPakistan: 'Analysis: Foreign currency pays for imports and debt repayments. Reliable financing matters, but repeated borrowing cannot replace stronger exports and tax collection.',
    question: 'Is Pakistan economically stable, and what should it do next?',
    answerPoints: [
      'Fact: Reuters reported new financing requests on 17 September, not a completed US package or an expanded Chinese swap.',
      'Background: On 8 May, the International Monetary Fund allowed about $1.1 billion under its Extended Fund Facility and $220 million under its Resilience and Sustainability Facility after programme reviews. This earlier approval is not September news.',
      'Plain meaning: A currency swap provides access to another currency under agreed terms. It is not free income or export earnings.',
      'Attributed assessment: The finance minister said prolonged energy disruption could put the government\'s 4% growth target at risk. A target is not measured growth.',
      'My assessment: Keep reforms credible, widen the tax base fairly, protect essential social spending and earn more foreign currency through competitive exports.',
    ],
    watch: [
      'IMF review conclusions and any subsequent board decision, not just an announced visit.',
      'Actual financing agreements, repayment terms and State Bank reserve releases.',
      'New PBS inflation data and the energy import bill before quoting a current rate.',
    ],
    sources: [evidence.pakistanFinance, evidence.imfReview],
  },
  {
    id: 'pakistan-energy-import-shock',
    region: 'Pakistan',
    title: 'Energy: Gulf disruption reaches Pakistani fuel and power supplies',
    date: '2026-09-19',
    summary: 'Reported facts: Reuters reporting of 17 September, republished on 19 September, put Asian spot LNG prices near $30 per million British thermal units, compared with about $10 before the war. It reported only two LNG cargoes confirmed for Pakistan for September at that reporting point. On 17 September, Pakistan announced fuel cuts for official vehicles and restrictions on government purchases and travel.',
    whyPakistan: 'Analysis: Costlier imported fuel can raise transport, factory and household costs. Supply security matters as much as the advertised price of a cargo.',
    question: 'How does a Middle East conflict affect an ordinary family in Pakistan?',
    answerPoints: [
      'Fact: LNG means liquefied natural gas. Disrupted Gulf shipments push buyers toward more expensive supplies on the spot market.',
      'Reported figure: Reuters cited power-system data showing winter gas needs of up to 400 million cubic feet a day for the power sector. This is a requirement, not a guaranteed shortage.',
      'Fact: The austerity announcement included less fuel for official vehicles, bans on state vehicle purchases and official foreign visits, and more teleconferencing.',
      'Reported context: Solar generation has eased some electricity pressure, but Pakistan still needs gas for households and other sectors. Solar alone does not replace all fuel uses.',
      'My assessment: Conserve fuel, diversify suppliers, improve grids and protect essential services. Do not promise that one subsidy or one new power plant solves the whole problem.',
    ],
    watch: [
      'Confirmed LNG delivery dates rather than announced purchase intentions.',
      'Power-sector gas allocation and actual outage notices.',
      'Shipping access through Hormuz and the Red Sea, plus revised fuel prices.',
    ],
    sources: [evidence.pakistanEnergy, evidence.pakistanAusterity],
  },
  {
    id: 'pakistan-governance-fuel-relief',
    region: 'Pakistan',
    title: 'Governance: fuel relief must reach people who struggle to register',
    date: '2026-09-19',
    summary: 'Reported facts: Pakistan introduced a capped Rs100-per-litre fuel subsidy for eligible small vehicles. Reuters described a rider who struggled with vehicle and phone registration. Radio Pakistan reported revised arrangements on 19 September, including free registration SMS and weekly Rs500 tokens for eligible motorcycles and rickshaws. The government described the scheme as successful; the reported registration difficulty shows why delivery needs independent checking.',
    whyPakistan: 'Analysis: Good governance means turning an announcement into a service people can actually use, while showing who pays for it and preventing unfair exclusion.',
    question: 'Would you support a fuel subsidy during this crisis?',
    answerPoints: [
      'Fact: The scheme is targeted and capped, not unlimited cheap fuel for everyone.',
      'Official update: Radio Pakistan said eligible motorcycles and rickshaws would receive one Rs500 token weekly, four per month, and registration SMS would be free.',
      'Official update: For vehicles up to 800cc, the report retained Rs100 per litre on up to ten litres every ten days. Check later eligibility changes before giving practical advice.',
      'Evidence limit: One person\'s registration difficulty is real reported experience, but it does not measure the nationwide failure rate. A government success claim is not an audit either.',
      'My assessment: Offer assisted registration, a complaint channel and published spending and redemption totals. Temporary help should be affordable and reviewed, not allowed to become an open-ended promise.',
    ],
    watch: [
      'New eligibility and token rules on official channels.',
      'Successful redemptions, complaints and access for people without digital skills.',
      'Budget cost, funding source and a clear review or end date.',
    ],
    sources: [evidence.pakistanFuelScheme, evidence.pakistanEnergy],
  },
  {
    id: 'pakistan-security-kohat',
    region: 'Pakistan',
    title: 'Security: Kohat attack and protection of police and civilians',
    date: '2026-09-19',
    summary: 'Reported facts: A vehicle bombing and armed assault struck a police compound and mosque in Kohat, Khyber Pakhtunkhwa, during Friday prayers on 18 September. AP reported police and worshippers among the victims. A Reuters update citing AFP on 19 September carried a revised death toll attributed to a police official. Early casualty and responsibility accounts were changing, so this briefing does not present an initial number as a final total.',
    whyPakistan: 'Analysis: Police capacity, public trust and protection of families are central to internal security. Claims about foreign involvement require evidence, not slogans.',
    question: 'What is a balanced response to the Kohat attack?',
    answerPoints: [
      'Fact: This was an attack on a police facility during prayers, with civilians also exposed. Condemn the violence without blaming an entire community.',
      'Evidence discipline: Identify the source and time of any casualty figure. Do not turn an initial suspicion or a militant claim into proven responsibility.',
      'Attributed positions: AP reported Pakistan\'s allegation that the Afghan authorities shelter Tehreek-e-Taliban Pakistan, or TTP, militants and Kabul\'s denial. That dispute does not independently establish who directed this attack.',
      'Reported context: AP also described Turkish and Qatari contacts aimed at reducing Pakistan-Afghanistan tensions. Diplomacy and lawful domestic policing can proceed together.',
      'My assessment: Prioritise rescue, evidence-led investigation, better police protection and civilian safety. Long-term security also needs courts, local cooperation and measures against recruitment.',
    ],
    watch: [
      'Consolidated police and hospital updates, with dates and any corrections.',
      'Investigative evidence on responsibility rather than social-media attribution.',
      'Support for victims and verifiable progress in border dialogue.',
    ],
    sources: [evidence.kohatAP, evidence.kohatUpdate],
  },
  {
    id: 'pakistan-climate-monsoon-resilience',
    region: 'Pakistan',
    title: 'Climate and floods: repair damage and reduce the next disaster',
    date: '2026-09-18',
    summary: 'Reported facts: OCHA\'s monsoon update, published on 15 September using NDMA data as of 14 September, listed 1,788 damaged houses and 41 damaged bridges. On 18 September, the NDMA chairman called for longer-term urban flood planning, including drainage, infrastructure maintenance and coordination. These are dated damage reports and a policy call, not proof that the recommended works have been completed.',
    whyPakistan: 'Analysis: Damaged homes, roads and bridges interrupt schooling, health care, transport and incomes. Disaster readiness is a national-security and development issue.',
    question: 'Is flood management only about rescue after heavy rain?',
    answerPoints: [
      'Fact: OCHA, the UN aid-coordination office, used figures from Pakistan\'s National Disaster Management Authority, or NDMA. Treat them as the 14 September snapshot, not a final monsoon total.',
      'Official position: NDMA\'s 18 September message stressed preparedness, drainage capacity, stormwater management and clear institutional responsibility.',
      'Plain distinction: Weather warnings predict hazards; damage reports record impacts; climate attribution studies examine how climate change affected an event. They are not interchangeable.',
      'My assessment: Rescue comes first during danger, followed by safe water, health care and transparent compensation. Prevention requires maintained drains, safer construction and reliable local warnings.',
      'My assessment: Publish project budgets and completion checks. Better planning should protect poorer settlements rather than simply move their risk elsewhere.',
    ],
    watch: [
      'New NDMA situation reports and district-specific warnings.',
      'Drinking-water safety, disease surveillance and access to cut-off settlements.',
      'Reconstruction funding, drainage maintenance and independently checked delivery.',
    ],
    sources: [evidence.pakistanFloods, evidence.pakistanResilience],
  },
  {
    id: 'middle-east-saudi-iran-pakistan-defence',
    region: 'Middle East',
    title: 'Saudi Arabia, Iran and Türkiye: defence commitments versus mediation',
    date: '2026-09-18',
    summary: 'Reported facts: Reuters on 11 September described the August mutual-defence agreement between Pakistan, Saudi Arabia and Türkiye as facing a major test from Saudi-Houthi fighting. Pakistan\'s foreign-ministry spokesman said then that no military response was under discussion. On 18 September, Pakistan\'s UN representative reaffirmed support for Saudi sovereignty while calling for de-escalation and safe passage for ships.',
    whyPakistan: 'Analysis: Pakistan must consider commitments to Saudi Arabia, its border relationship with Iran, domestic security demands and exposure to Gulf energy disruption.',
    question: 'Should Pakistan choose Saudi Arabia or Iran?',
    answerPoints: [
      'Reported fact: Reuters described an agreement treating an armed attack on one of the three partners as an attack on all. Do not invent operational orders or a timetable from that wording.',
      'Dated official position: The no-military-response statement was reported on 11 September. It is not a guarantee that policy cannot change after that date.',
      'Official position: On 18 September Pakistan condemned Houthi attacks on merchant shipping and supported Saudi sovereignty, while also calling for de-escalation.',
      'Important distinction: Saudi Arabia and Iran are states; the Houthis are a Yemeni armed movement. Iranian support does not by itself prove Iranian command of every attack.',
      'My assessment: Honour lawful commitments, protect citizens and shipping, and keep dialogue open with Tehran. A responsible answer weighs consequences rather than cheering for a wider war.',
    ],
    watch: [
      'Fresh Pakistani government statements and any publicly confirmed operational decision.',
      'Saudi-Houthi attacks, civilian protection and maritime access.',
      'Pakistan-Iran communication and the scope of the Türkiye-Saudi-Pakistan agreement.',
    ],
    sources: [evidence.saudiPakistan, evidence.pakistanMaritime],
  },
  {
    id: 'middle-east-iran-oman-hormuz-talks',
    region: 'Middle East',
    title: 'Iran and Oman: shipping talks stalled, and talk of talks is not peace',
    date: '2026-09-17',
    summary: 'Reported facts: Reuters\' updated 14 September report said Oman postponed a planned Iran-Gulf meeting about reopening the Strait of Hormuz. It described the shipping lane as mostly shut, not completely traffic-free. On 17 September, Al Jazeera reported Trump\'s claim of direct contact with Iran but said Tehran had not confirmed that direct negotiations had resumed. Iran\'s position concerned implementation of the June interim understanding.',
    whyPakistan: 'Analysis: Pakistan needs safe energy routes and credible mediation. Hormuz developments can affect import costs even when no fighting occurs inside Pakistan.',
    question: 'What would count as real progress between Iran and the United States?',
    answerPoints: [
      'Fact: Oman was acting as a diplomatic host. A postponed meeting is not a failed signed peace treaty, and hosting talks does not make Oman a combatant.',
      'Attributed US position: Trump said he had spoken directly with Iran. The 17 September account did not independently confirm resumed direct negotiations.',
      'Attributed Iranian position: Iranian officials demanded fulfilment of earlier commitments. This is a negotiating position, not proof that all disputed facts favour either side.',
      'Evidence limit: Reuters recorded conflicting Iranian, US and maritime-agency accounts about a damaged tanker. Do not repeat one explanation as a settled finding.',
      'My assessment: Look for an agreed text, verification, fewer attacks and safe commercial passage. Public optimism alone does not deliver those outcomes.',
    ],
    watch: [
      'A jointly confirmed meeting date and any published agreement.',
      'Verified shipping movements and notices from maritime safety authorities.',
      'Implementation of agreed steps, not just competing statements about contact.',
    ],
    sources: [evidence.hormuzTalks, evidence.iranDiplomacy],
  },
  {
    id: 'middle-east-yemen-civilians-aid',
    region: 'Middle East',
    title: 'Yemen: displacement and blocked aid behind the military headlines',
    date: '2026-09-18',
    summary: 'UN reporting: OCHA said more than 18,600 households were displaced across Yemen between 1 August and 16 September. In the same period, aid partners reached more than 11,150 displaced households. Its 17 September update said 15,000 emergency kits were ready, but road closures prevented most from reaching people in need. Mokha seaport was closed after serious damage.',
    whyPakistan: 'Analysis: Yemen\'s crisis threatens Red Sea trade and tests Pakistan\'s regional diplomacy. Civilian needs must not disappear behind discussion of alliances.',
    question: 'What is happening to ordinary Yemenis?',
    answerPoints: [
      'Fact: OCHA counted displaced households, not individual people. Do not multiply by an assumed family size and present the result as a UN figure.',
      'Fact: Prepared supplies are not the same as delivered aid. Road closures and damage to Mokha explain why access matters alongside donations.',
      'UN finding: The 17 September update put the 2026 humanitarian response plan at barely 20% funded and said a $9 million emergency allocation had been released.',
      'Important distinction: Yemen\'s population is not identical to the Houthis. Civilians live in areas controlled by different actors and are entitled to protection everywhere.',
      'My assessment: Support de-escalation, safe aid access and protection of civilian shipping. Funding, access and accountability are practical priorities, not optional extras.',
    ],
    watch: [
      'New displacement registrations and whether households can return safely.',
      'Road and port access, delivery of emergency kits and aid-worker safety.',
      'Actual humanitarian funding received rather than pledges alone.',
    ],
    sources: [evidence.ochaSeptember18, evidence.ochaSeptember17],
  },
  {
    id: 'middle-east-gaza-shelter-health',
    region: 'Middle East',
    title: 'Gaza: unsafe shelter, rain and fuel-dependent health care',
    date: '2026-09-18',
    summary: 'UN reporting: On 18 September, OCHA said an estimated 1.2 million people in Gaza faced shelter conditions ranging from critical to catastrophic. More than 65% of assessed families lived in tents or makeshift shelters. A day earlier, the humanitarian coordinator allocated $2 million to provide fuel for medical services over four months while the electricity grid remained down. This was emergency support, not restoration of normal health care.',
    whyPakistan: 'Analysis: Pakistan\'s support for Palestinians is more credible when it combines a clear political position with practical concern for shelter, health care and civilian protection.',
    question: 'What should a balanced answer about Gaza include?',
    answerPoints: [
      'Fact: The shelter figure is an OCHA estimate. The percentage refers to assessed families, not a census of every household.',
      'Fact: OCHA reported another collapse of a war-damaged residential building as rains began. Safety includes damaged buildings, water and disease risks, not only direct attacks.',
      'Fact: The health allocation was $500,000 of fuel per month for four months. An allocation is not proof every hospital has received enough fuel.',
      'UN position: OCHA called for Israeli approval of heavy equipment and durable shelter materials. It also highlighted funding shortages and restrictions affecting the response.',
      'My assessment: Protect Palestinian and Israeli civilians, reject hostage-taking and attacks on civilians, support lawful humanitarian access and pursue a durable political settlement. Do not blame a whole people for an armed group or government.',
    ],
    watch: [
      'Entry and delivery of shelter supplies, engine oil and medical fuel.',
      'Hospital operations, safe water and protection from winter flooding.',
      'Verified civilian protection measures and progress toward a lasting settlement.',
    ],
    sources: [evidence.ochaSeptember18, evidence.ochaSeptember17],
  },
  {
    id: 'middle-east-west-bank-education-displacement',
    region: 'Middle East',
    title: 'West Bank: violence and displacement also disrupt schooling',
    date: '2026-09-12',
    summary: 'UN reporting: OCHA\'s report for 11 September, posted on 12 September, documented more than 1,600 settler attacks causing Palestinian casualties or property damage across 275 communities during January-August 2026. It said regular schooling remained disrupted for more than 4,000 displaced students and that 19 schools were inaccessible, closed or abandoned. The West Bank crisis is distinct from Gaza, although both concern Palestinian rights and a political settlement.',
    whyPakistan: 'Analysis: An informed answer should cover the West Bank as well as Gaza and explain how movement, education and land policies affect the prospects of peace.',
    question: 'Why discuss the West Bank when most headlines concern Gaza?',
    answerPoints: [
      'Fact: OCHA\'s attack count covers incidents causing casualties or property damage. It is not a count of every confrontation or of all Israeli residents.',
      'Fact: The new school year began for about 846,000 West Bank students, but displacement and access restrictions prevented normal schooling for many others.',
      'Fact: The report identified demolitions, military operations, settler violence and movement restrictions as drivers of humanitarian need.',
      'Plain distinction: Gaza and the West Bank are separate geographic areas. Do not transfer a Gaza casualty figure or aid-access rule to the West Bank.',
      'My assessment: Protect children and civilian communities, investigate violence and support a viable two-state settlement. Security and human rights should reinforce each other.',
    ],
    watch: [
      'Updated OCHA incident and displacement reporting.',
      'School reopening, safe access and pending demolition orders.',
      'Policies affecting Palestinian territorial continuity and civilian livelihoods.',
    ],
    sources: [evidence.westBank],
  },
  {
    id: 'middle-east-egypt-jordan-regional-diplomacy',
    region: 'Middle East',
    title: 'Egypt, Jordan and regional partners: diplomacy is a separate role',
    date: '2026-09-09',
    summary: 'Official position: On 9 September, the foreign ministers of Türkiye, Egypt, Indonesia, Jordan, Pakistan, Qatar, Saudi Arabia and the UAE welcomed UK restrictions on trade linked to Israeli settlements. Their joint statement called for a Palestinian state based on the 4 June 1967 lines with East Jerusalem as its capital, and implementation of the Gaza peace plan. This records a shared diplomatic position, not proof that the plan has been implemented.',
    whyPakistan: 'Analysis: Pakistan is part of this diplomatic group. Understanding the actual statement is more useful than assuming every regional government has identical policies.',
    question: 'What are Egypt, Jordan and Türkiye doing besides reacting to war?',
    answerPoints: [
      'Fact: The eight-country statement is published by Türkiye\'s Foreign Ministry. Egypt and Jordan are participants in a concrete diplomatic initiative, not merely names on a map.',
      'Official position: The ministers backed a two-state solution and opposed measures changing the geography and population of occupied Palestinian territory.',
      'Scope: Restrictions on settlement-linked goods and services are not the same as a ban on all trade with Israel. Check the relevant government rules before describing their reach.',
      'Reported disagreement: Arab News noted Israel\'s opposition and the dispute over settlement policy. Diplomatic support for a statement does not settle every implementation question.',
      'My assessment: Judge diplomacy by civilian protection, access and a workable political process. Do not describe Egypt, Jordan, Qatar or the UAE as active battlefields simply because they signed a statement.',
    ],
    watch: [
      'Actual implementation and scope of settlement-trade restrictions.',
      'Follow-up joint statements and practical steps on aid and reconstruction.',
      'Progress on a political settlement rather than ceremonial meetings alone.',
    ],
    sources: [evidence.regionalStatement, evidence.regionalReporting],
  },
  {
    id: 'middle-east-lebanon-unifil-schools',
    region: 'Middle East',
    title: 'Lebanon: a peacekeeping transition and children missing school',
    date: '2026-09-17',
    summary: 'Reported facts: Reuters on 16 September described UNIFIL escorts as a lifeline for communities inside Israeli-occupied southern Lebanon. The mission\'s mandate was scheduled to end at the close of 2026, with withdrawal beginning in January if no extension was agreed. On 17 September, OCHA cited Lebanese authorities saying nearly 100,000 children could not return to school because of damage, insecurity or displacement.',
    whyPakistan: 'Analysis: Lebanon illustrates why ceasefire monitoring, national institutions and civilian services must be considered together when discussing peacekeeping.',
    question: 'Would the departure of UN peacekeepers automatically mean peace in Lebanon?',
    answerPoints: [
      'Fact: UNIFIL is the UN Interim Force in Lebanon. Its tasks include monitoring and helping maintain humanitarian access; it is not the Lebanese army or Hezbollah.',
      'Reported fact: Reuters described a June withdrawal-and-disarmament framework that had stalled. A framework agreement is not completed Israeli withdrawal or completed Hezbollah disarmament.',
      'Attributed disagreement: Residents and UN personnel feared losing access. An Israeli military official told Reuters that Israel did not regard UNIFIL as vital to humanitarian efforts.',
      'UN reporting: OCHA\'s school figure was attributed to Lebanese authorities. Schools and displaced families remain important even when attention shifts to military arrangements.',
      'My assessment: Any transition needs safe access, credible monitoring and capable Lebanese institutions. A deadline on paper should not be mistaken for a safe situation on the ground.',
    ],
    watch: [
      'Security Council decisions on the mandate and any replacement arrangement.',
      'Israeli withdrawal, Lebanese army deployment and disarmament implementation.',
      'Aid convoys, school access and safe voluntary return of displaced families.',
    ],
    sources: [evidence.lebanonUNIFIL, evidence.ochaSeptember17],
  },
  {
    id: 'middle-east-syria-return-recovery',
    region: 'Middle East',
    title: 'Syria: large returns are hopeful, but recovery is incomplete',
    date: '2026-09-17',
    summary: 'UN reporting: OCHA said on 17 September that more than 2 million internally displaced Syrians and 1.8 million refugees had returned voluntarily since December 2024. Aid agencies were reaching more than 2.5 million people monthly during 2026. The UN relief chief warned that continuing displacement, local insecurity, landmines, regional escalation and insufficient funding could undermine recovery.',
    whyPakistan: 'Analysis: Syria is a lesson in the difference between a political transition, the end of every conflict and successful rebuilding. These are separate achievements.',
    question: 'Does the return of refugees mean Syria is now safe for everyone?',
    answerPoints: [
      'Fact: A refugee has crossed an international border; an internally displaced person has moved within the country. Keep the two return categories separate.',
      'Fact: The UN described returns as voluntary and hopeful, while warning that insecurity and humanitarian needs continued.',
      'Fact: Landmines and other explosive hazards can endanger families returning to homes and farms even where large battles have stopped.',
      'UN position: The relief chief urged support for reconstruction and livelihoods and political efforts to keep Syria out of wider regional conflict.',
      'My assessment: Returns should be safe, voluntary and supported by services and legal protection. A national return total does not prove every town or minority community is safe.',
    ],
    watch: [
      'Conditions in return areas, not just the number of people returning.',
      'Mine clearance, housing, health care, water and access to livelihoods.',
      'Local violence, protection of minorities and funding actually received.',
    ],
    sources: [evidence.ochaSeptember17],
  },
  {
    id: 'middle-east-iraq-state-authority-oil',
    region: 'Middle East',
    title: 'Iraq: control of armed groups and alternatives to a blocked oil route',
    date: '2026-09-16',
    summary: 'Reported facts: Reuters said on 9 September that Iraq\'s prime minister had pledged militia disarmament by 30 September, alongside the scheduled departure of remaining US-led coalition forces. It reported strong militia resistance, not completed disarmament. On 16 September, Reuters reported a two-day trial moving about 38,000 barrels of southern crude north in 209 trucks to support exports through Türkiye after disruption to the Hormuz route.',
    whyPakistan: 'Analysis: Iraq shows how state authority and energy security interact. Pakistan should assess both the reliability of oil supply and the political risks behind it.',
    question: 'Why is Iraq more than a simple US-versus-Iran story?',
    answerPoints: [
      'Reported commitment: The September 30 disarmament deadline was a pledge. It had not arrived at this research cutoff, so do not report compliance or failure as a completed outcome.',
      'Important distinction: Iraq\'s state institutions, Iran-aligned armed groups and ordinary Iraqis are not the same actor.',
      'Reported fact: The oil-trucking trial began on 13 September and moved roughly 38,000 barrels over two days. A pilot shipment is not a replacement for the whole southern export system.',
      'Plain meaning: Alternative routes reduce dependence on a single chokepoint, but roads, loading facilities and security constrain how much they can carry.',
      'My assessment: Support Iraqi sovereignty and credible state institutions. Avoid assuming that foreign influence removes Iraqi interests or domestic political choices.',
    ],
    watch: [
      'Verified developments around the September 30 commitments and coalition timetable.',
      'Militia conduct and state control, not announcements alone.',
      'Sustained export volumes via Kirkuk and Ceyhan rather than pilot totals.',
    ],
    sources: [evidence.iraqMilitias, evidence.iraqExports],
  },
  {
    id: 'middle-east-gulf-jordan-security-claims',
    region: 'Middle East',
    title: 'Kuwait, Bahrain, UAE and Jordan: distinguish alerts from verified damage',
    date: '2026-09-03',
    summary: 'Attributed reports: On 2 September, Jordan, Kuwait and Bahrain said they had intercepted Iranian missiles or drones. Reporting on 3 September carried Kuwait\'s condemnation and Iran\'s statement that it targeted US bases in Kuwait and the UAE. These are dated accounts of regional spillover. They do not establish the result of every claimed strike, or mean that every country is experiencing the same kind of conflict.',
    whyPakistan: 'Analysis: Pakistani citizens, transport links and commercial interests can be exposed to regional disruption. Accurate consular information is more useful than rumours.',
    question: 'Are all Gulf countries involved in the same war in the same way?',
    answerPoints: [
      'Attributed fact: The governments reported interceptions. Iran said it was targeting US military sites. An attacker\'s claimed target and the independently verified impact are different things.',
      'Evidence limit: The 2 September report explicitly said an Iranian-media account of a strike on a US base in Bahrain lacked official confirmation.',
      'Geography: Jordan is not a Gulf Cooperation Council member. Saudi Arabia, Oman, UAE, Qatar, Bahrain and Kuwait are the six GCC states.',
      'Reported diplomatic role: The AFP/AP-based 3 September account said Egypt and Qatar called for a return to negotiations. Regional countries can face risk while also pursuing diplomacy.',
      'My assessment: Protect civilians of every nationality, follow embassy and aviation notices, and avoid making evacuation or battlefield claims without an official update.',
    ],
    watch: [
      'Fresh official alerts and independent confirmation of any damage.',
      'Pakistani embassy advice, transport availability and worker welfare.',
      'De-escalation efforts, while remembering this briefing\'s incident evidence is from 2-3 September.',
    ],
    sources: [evidence.gulfInterceptions, evidence.gulfAFPAP],
  },
  {
    id: 'middle-east-qatar-uae-energy-trade',
    region: 'Middle East',
    title: 'Qatar and UAE: LNG disruption and changing oil trade',
    date: '2026-09-19',
    summary: 'Reported facts and claims: Reuters\' energy reporting, republished on 19 September, described interrupted Qatari LNG deliveries pushing South Asian buyers toward costlier alternatives. Separately, Reuters on 15 September cited sources saying the UAE\'s Abu Dhabi National Oil Company, or ADNOC, had agreed large discounted Iraqi crude purchases. One source distinguished 32 million barrels allocated for August from only 20 million actually lifted because of export constraints.',
    whyPakistan: 'Analysis: A low quoted fuel price is not enough if delivery is uncertain. Qatar and the UAE also have distinct energy and diplomatic roles, not interchangeable identities.',
    question: 'Why should Pakistan care about Gulf energy logistics rather than only oil prices?',
    answerPoints: [
      'Fact: LNG supply disruption affects both electricity and industrial activity. The Reuters South Asia report described different effects in Bangladesh and Pakistan, not identical national conditions.',
      'Attributed market claim: Reuters\' ADNOC story relied on people familiar with the trade. Its purchase and lifting figures are not independently audited totals in this briefing.',
      'Plain distinction: Allocation means a planned volume; lifting means taking delivery. The August example shows why those numbers must not be confused.',
      'Analysis: Shipping access, insurance, port capacity and financing can make a cheap cargo difficult or expensive to obtain.',
      'My assessment: Evaluate energy deals by dependable delivery and total cost. Do not turn a trade story into an unsupported claim that Qatar or the whole UAE is a battlefield.',
    ],
    watch: [
      'Actual Qatari cargo departures and confirmed Pakistani delivery schedules.',
      'Trade-source claims checked against company or official export data.',
      'Shipping availability and landed cost, not headline discounts alone.',
    ],
    sources: [evidence.pakistanEnergy, evidence.uaeOilTrade],
  },
  {
    id: 'russia-ukraine-talks-energy-truce',
    region: 'Russia and Ukraine',
    title: 'Peace talks and an energy truce: distinguish proposals from implementation',
    date: '2026-09-15',
    summary: 'Reported facts: Reuters on 8 September said US envoys had visited Russia and Ukraine without a breakthrough. After Trump announced an energy-target truce, reports on 15 September carried different qualifications: Zelenskyy said Ukraine would stop corresponding attacks if partners ensured Russia did the same; the Kremlin welcomed the idea and said communication with Washington continued. These statements do not demonstrate a verified, comprehensive ceasefire.',
    whyPakistan: 'Analysis: Energy and grain disruption can affect Pakistani prices. Diplomacy matters, but its practical results must be checked rather than assumed from an announcement.',
    question: 'Has the Russia-Ukraine war ended because an energy truce was announced?',
    answerPoints: [
      'Fact: The 8 September Reuters account said talks had not resolved the major disagreements, including territory in eastern Ukraine.',
      'Attributed Ukrainian position: Zelenskyy sought reliable protection of electricity, other energy facilities, critical infrastructure and food-supply routes.',
      'Attributed Russian position: Kremlin spokesman Dmitry Peskov supported the idea of an energy truce and said talks with the US continued. Support for an idea is not proof of compliance.',
      'Plain distinction: A sector-specific pause would not automatically stop ground fighting or settle territorial claims. A ceasefire also differs from a final peace agreement.',
      'My assessment: Support diplomacy consistent with sovereignty and civilian protection. Look for agreed terms, monitoring and fewer attacks before calling it a success.',
    ],
    watch: [
      'A mutually confirmed text, covered facilities and verification arrangements.',
      'Documented attacks and restoration of power, water and heating.',
      'Prisoner exchanges, grain-shipping arrangements and wider negotiations.',
    ],
    sources: [evidence.ukraineDiplomacy, evidence.ukraineEnergyPosition, evidence.russiaEnergyPosition],
  },
  {
    id: 'russia-ukraine-civilians-august',
    region: 'Russia and Ukraine',
    title: 'Civilians: UN-verified August casualties and the limits of the count',
    date: '2026-09-16',
    summary: 'UN findings: The UN Human Rights Office, or OHCHR, reported on 16 September that it had verified at least 372 civilians killed and 2,349 injured in Ukraine during August 2026. Long-range missiles and drones caused 47% of those casualties, often far from the front. The UN said Russian authorities also reported civilian casualties inside Russia, but monitors could not verify most of those allegations because independent information was lacking.',
    whyPakistan: 'Analysis: A professional military interview answer should explain civilian protection, evidence standards and the human cost of war, not just weapons and territorial gains.',
    question: 'How can you discuss civilian suffering without exaggerating or showing double standards?',
    answerPoints: [
      'Fact: These are August figures published in September. Casualties include people killed and injured; do not call the combined total deaths.',
      'Fact: OHCHR described them as verified minimum counts. Limited access means the actual toll may be higher.',
      'UN finding: Short-range drones accounted for 30% of August civilian casualties and were the main cause near the front. Long-range strikes also endangered urban populations far away.',
      'Evidence limit: Acknowledge suffering inside Russia without presenting unverified Russian official totals as UN-confirmed numbers or treating unequal evidence as equal proof.',
      'My assessment: Protect civilians and essential services everywhere. Evaluate distinction, proportionality and precautions, meaning who is targeted, foreseeable civilian harm and steps to reduce it.',
    ],
    watch: [
      'The next OHCHR civilian-protection report and revisions to verified figures.',
      'Access for monitors in occupied areas and independently documented incidents in Russia.',
      'Civilian electricity, heating, medical care and safe movement as winter approaches.',
    ],
    sources: [evidence.ukraineCivilians],
  },
  {
    id: 'russia-ukraine-detainees-accountability',
    region: 'Russia and Ukraine',
    title: 'Civilians and prisoners: accountability without graphic detail',
    date: '2026-09-18',
    summary: 'UN findings: A report published on 18 September documented 1,004 cases of conflict-related sexual violence from 24 February 2022 through July 2026. OHCHR attributed 89% of the documented cases to Russian authorities and 11% to Ukrainian authorities. It called for both sides to investigate credible allegations and protect civilians and prisoners of war. These are documented cases over a multi-year period, not a count for September alone.',
    whyPakistan: 'Analysis: Respect for detainees and civilians is a test of military professionalism. Condemning abuse by one side never excuses abuse by another.',
    question: 'What does professional conduct require even when the enemy has committed abuses?',
    answerPoints: [
      'Fact: The UN report was based on confidential interviews and other material, including court and official records. It is not simply a collection of social-media allegations.',
      'Evidence discipline: Keep the UN attribution and reporting period attached to the numbers. The percentages concern documented cases, not every incident that may have occurred.',
      'Plain distinction: A UN finding supports investigation and accountability; this briefing does not turn it into an individual criminal conviction.',
      'UN position: Both Russia and Ukraine should investigate credible claims promptly and impartially, with particular concern about the high share attributed to Russian authorities.',
      'My assessment: Treat prisoners humanely, preserve evidence, support survivors and reject revenge against detainees. Describe the issue respectfully without repeating graphic details.',
    ],
    watch: [
      'Independent investigations and fair proceedings, regardless of rank or affiliation.',
      'Safe monitoring access and protection against retaliation for survivors.',
      'Detainee treatment, releases and access to medical and psychological support.',
    ],
    sources: [evidence.ukraineAccountability],
  },
  {
    id: 'russia-ukraine-sanctions-pakistan',
    region: 'Russia and Ukraine',
    title: 'New US sanctions law: pressure on Russia and risks for third-country trade',
    date: '2026-09-19',
    summary: 'Reported facts: Reuters on 18 September and Anadolu on 19 September reported the White House announcement that Trump signed a new Russia sanctions law. Reporting described measures aimed at Russian energy, defence and sanctions-evasion networks, and authority for targeted tariffs involving major purchasers of Russian oil or gas. Signing a law is not the same as every possible tariff immediately taking effect against every country.',
    whyPakistan: 'Analysis: Pakistan must evaluate energy affordability alongside banking, shipping and sanctions-compliance risks. This report does not establish that Pakistan has been sanctioned.',
    question: 'Should Pakistan buy discounted Russian energy regardless of sanctions?',
    answerPoints: [
      'Fact: The signing took place on 18 September; the Anadolu article was published on 19 September. Keep the event date and publication date separate.',
      'Plain meaning: Primary sanctions restrict covered dealings; secondary measures can put pressure on other actors that support specified transactions. Exact scope depends on the law and implementation.',
      'Evidence limit: Neither cited report establishes a specific new penalty on Pakistan. Do not invent one or assume an exemption.',
      'Analysis: A cheaper barrel can still carry higher financing, insurance, transport or legal costs. Compare the full landed cost and supply reliability.',
      'My assessment: Use lawful, transparent procurement and check official implementing notices with qualified specialists. Economic pragmatism should not become a slogan for ignoring civilian suffering or legal obligations.',
    ],
    watch: [
      'US Treasury and other official implementation notices, effective dates and exemptions.',
      'Bank, insurer and shipping requirements for any proposed transaction.',
      'Actual market effects and diplomatic responses rather than assumed penalties.',
    ],
    sources: [evidence.russiaSanctionsReuters, evidence.russiaSanctionsAA],
  },
];

export const regionPrimer: { country: string; capital: string; whyItMatters: string; source: string }[] = [
  {
    country: 'Pakistan',
    capital: 'Islamabad',
    whyItMatters: 'Home-country focus: connect foreign energy costs with household prices, public finances, security and climate resilience. Remittances and overseas Pakistanis also make regional stability important.',
    source: 'https://www.britannica.com/summary/Pakistan',
  },
  {
    country: 'Saudi Arabia',
    capital: 'Riyadh',
    whyItMatters: 'Major oil producer and home to Makkah and Madinah. For this snapshot, study the Pakistan-Saudi-Türkiye defence arrangement and Saudi-Houthi fighting without equating Yemen\'s people with the Houthis.',
    source: 'https://www.britannica.com/place/Saudi-Arabia',
  },
  {
    country: 'Iran',
    capital: 'Tehran',
    whyItMatters: 'Pakistan\'s neighbour and a key actor around Hormuz. Separate Iran\'s government, its people and aligned armed groups; distinguish confirmed diplomacy from claims about talks or attacks.',
    source: 'https://www.britannica.com/place/Tehran',
  },
  {
    country: 'Iraq',
    capital: 'Baghdad',
    whyItMatters: 'An oil producer whose government faces questions about armed-group control and export access. Iraq has its own interests and institutions; it is not simply another name for Iran or its militias.',
    source: 'https://www.britannica.com/place/Iraq/Baghdad',
  },
  {
    country: 'Syria',
    capital: 'Damascus',
    whyItMatters: 'Study political transition, voluntary returns, reconstruction and explosive hazards. Large return totals do not show that every area is safe or that all humanitarian needs have ended.',
    source: 'https://www.britannica.com/place/Syria',
  },
  {
    country: 'Lebanon',
    capital: 'Beirut',
    whyItMatters: 'Understand the distinct roles of the Lebanese state, Hezbollah, Israel and UNIFIL. Southern access, displaced families and schooling matter alongside the planned peacekeeping transition.',
    source: 'https://www.britannica.com/place/Beirut',
  },
  {
    country: 'Israel',
    capital: 'Jerusalem, proclaimed capital and seat of government; international status is disputed',
    whyItMatters: 'Central to the Palestinian conflict and regional security. Distinguish government policy, military actions and civilian rights. Tel Aviv should not be substituted for the actual seat of government, and Jerusalem\'s disputed status must be stated.',
    source: 'https://www.britannica.com/place/Israel',
  },
  {
    country: 'Palestine',
    capital: 'East Jerusalem is the claimed capital; Ramallah is the Palestinian Authority\'s working administrative centre',
    whyItMatters: 'Gaza and the West Bank, including East Jerusalem, have different immediate conditions. The September joint statement supports Palestinian statehood based on the 1967 lines. Do not equate all Palestinians with Hamas or any other faction.',
    source: 'https://kids.britannica.com/students/article/Ramallah/603100',
  },
  {
    country: 'Jordan',
    capital: 'Amman',
    whyItMatters: 'A neighbouring state involved in Palestinian diplomacy and affected by regional security alerts. It is not a GCC member. Diplomatic involvement and reported interceptions are different from a claim of nationwide war.',
    source: 'https://www.britannica.com/place/Jordan',
  },
  {
    country: 'Yemen',
    capital: 'Sanaa; national authority and territorial control are divided',
    whyItMatters: 'Its Red Sea position and the Bab al-Mandab route matter for shipping. Distinguish the Houthis, the internationally recognised government and civilians facing displacement and blocked aid.',
    source: 'https://www.britannica.com/place/Yemen',
  },
  {
    country: 'Oman',
    capital: 'Muscat',
    whyItMatters: 'A GCC state beside the Hormuz approaches and a diplomatic host. The postponed September meeting illustrates Oman\'s mediation role; that role does not establish that Oman is fighting a war.',
    source: 'https://www.britannica.com/summary/Oman',
  },
  {
    country: 'UAE',
    capital: 'Abu Dhabi',
    whyItMatters: 'The United Arab Emirates matters for trade, energy, overseas workers and diplomacy. ADNOC\'s reported Iraqi oil purchases are a trade story; evaluate security incidents separately and do not confuse Abu Dhabi with Dubai.',
    source: 'https://www.britannica.com/summary/Abu-Dhabi',
  },
  {
    country: 'Qatar',
    capital: 'Doha',
    whyItMatters: 'An important LNG supplier and diplomatic participant. Interrupted gas deliveries can affect South Asia, while Qatar\'s mediation and joint statements are separate diplomatic activities.',
    source: 'https://www.britannica.com/place/Doha',
  },
  {
    country: 'Bahrain',
    capital: 'Manama',
    whyItMatters: 'A Gulf island state and GCC member. For this snapshot, examine attributed interception reports and civilian safety, rather than assuming every claimed attack caused verified damage.',
    source: 'https://www.britannica.com/summary/Bahrain',
  },
  {
    country: 'Kuwait',
    capital: 'Kuwait City',
    whyItMatters: 'An oil-producing GCC state with regional security exposure. Reuters described its Pakistan defence protocol as narrower than the Saudi-Türkiye agreement, covering training, border security and capacity-building rather than an identical mutual-defence pact.',
    source: 'https://www.britannica.com/place/Kuwait-capital',
  },
  {
    country: 'Türkiye',
    capital: 'Ankara',
    whyItMatters: 'A defence partner and diplomatic actor relevant to Pakistan, Syria and Russia-Ukraine talks. The September sources show several roles, not proof that Türkiye is directly fighting in every conflict it discusses.',
    source: 'https://www.britannica.com/place/Ankara',
  },
  {
    country: 'Egypt',
    capital: 'Cairo',
    whyItMatters: 'A North African state central to the wider Middle East through Gaza diplomacy and the Suez route. Study its diplomatic role separately from active fighting elsewhere. New administrative-capital development should not be confused with the background capital listing.',
    source: 'https://www.sis.gov.eg/Story/169630/Cairo?lang=en-us',
  },
  {
    country: 'Russia',
    capital: 'Moscow',
    whyItMatters: 'The state that launched the full-scale armed attack on Ukraine in February 2022. Discuss its government\'s actions, diplomacy and energy trade without treating Russian civilians as legitimate targets.',
    source: 'https://www.britannica.com/place/Russia',
  },
  {
    country: 'Ukraine',
    capital: 'Kyiv',
    whyItMatters: 'Defending its territory while civilians face attacks, damaged services and displacement. Sovereignty, humanitarian protection, food routes and energy infrastructure all belong in the interview answer.',
    source: 'https://www.britannica.com/place/Ukraine',
  },
];
