import type { ExtractedPhoto } from './extractedPhotos';

export const extractedBatchA = [
  {
    fileName: 'IMG20260919120217.jpg',
    sections: [
      {
        id: 'batch-a-p88-ratio',
        kind: 'math',
        title: 'Questions Related to Ratio',
        language: 'ur',
        sourcePage: '88',
        items: [
          { prompt: '1. 60 روپوں کو 2:3:5 کی نسبت سے تقسیم کریں۔' },
          { prompt: '2. 60 روپے اس طرح تقسیم کریں کہ ایک کو 4 حصے اور دوسرے کو 8 حصے آئیں۔' },
          { prompt: '3. 20 روپے دو بچوں میں اس طرح تقسیم کریں کہ ایک کو 5 روپے زیادہ ملیں۔' },
          { prompt: '4. 230 روپے کو 2:3:5 کی نسبت سے تقسیم کریں۔' },
          { prompt: '5. 20 روپے دو بچوں میں اس طرح تقسیم کریں کہ ایک کو دوسرے کا تین گنا ملے؟' },
          { prompt: '6. 200 روپے کو تین لڑکوں میں 5:7:8 کی نسبت سے تقسیم کریں۔' },
          { prompt: '7. 110 روپے کو 2:3:5 کی نسبت سے تقسیم کریں۔' },
          { prompt: '8. 20 روپے کو 2:4:5 کی نسبت سے تقسیم کریں۔' },
          { prompt: '9. 100 روپے کو 2:5:20 کی نسبت سے تقسیم کریں۔' },
        ],
      },
      {
        id: 'batch-a-p88-zakat',
        kind: 'math',
        title: 'Questions Related to Zakat',
        language: 'ur',
        sourcePage: '88',
        items: [
          { prompt: '1. اگر 100 روپے پر 2.5 روپے زکوۃ ہو تو 500 پر کتنی ہوگی؟' },
          { prompt: '2. 1700 روپے پر کتنی زکوۃ ہوگی؟' },
          { prompt: '3. 2.5 فیصد کے حساب سے 8000 پر کتنی زکوۃ ہوگی؟' },
          { prompt: '4. اگر زکوۃ 250 روپے ادا کی گئی ہو تو اصل رقم کتنی ہوگی؟' },
          { prompt: '5. اگر زکوۃ 2000 روپے ادا کی گئی ہو تو اصل رقم کتنی ہوگی؟' },
          { prompt: '6. 1800 روپے پر کتنی زکوۃ ہوگی؟' },
          { prompt: '7. ان پر زکوۃ معلوم کریں:', detail: '70000, 50000, 975, 4200, 10000, 11700, 2750, 3400\n300, 1800, 1750, 1950, 2000, 11900, 11000, 2500' },
        ],
      },
      {
        id: 'batch-a-p89-speed',
        kind: 'math',
        title: 'Mathematics Questinos: Questions Related to Speed',
        language: 'ur',
        sourcePage: '89',
        items: [
          { prompt: '1. ایک گاڑی 120 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 3.5 منٹ میں کتنا فاصلہ طے کرے گی؟' },
          { prompt: '2. ایک گاڑی 30 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 40 منٹ میں کتنا فاصلہ طے کرے گی؟' },
          { prompt: '3. ایک جہاز 360 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہا ہے۔ 6 منٹ میں کتنا فاصلہ طے کرے گا؟' },
          { prompt: '4. ایک جہاز 1800 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہا ہے۔ 15.5 منٹ میں کتنا فاصلہ طے کرے گا؟' },
          { prompt: '5. ایک ریل گاڑی 30 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 4.5 منٹ میں کتنا فاصلہ طے کرے گی؟' },
          { prompt: '6. ایک کار 75 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 40 منٹ میں کتنا فاصلہ طے کرے گی؟' },
          { prompt: '7. ایک گاڑی 15 منٹ میں 45 کلومیٹر فی گھنٹہ فاصلہ طے کرتی ہے۔ ایک گھنٹہ میں کتنا فاصلہ طے کرے گی؟', detail: 'The source uses a speed unit, کلومیٹر فی گھنٹہ, for the stated distance. The wording is retained without resolving the dimensional inconsistency.' },
          { prompt: '8. ایک ریل گاڑی 2 منٹ میں 180 کلومیٹر فی گھنٹہ فاصلہ طے کرتی ہے۔ 6 منٹ میں کتنا فاصلہ طے کرے گی؟', detail: 'The source uses a speed unit, کلومیٹر فی گھنٹہ, for the stated distance. The wording is retained without resolving the dimensional inconsistency.' },
          { prompt: '9. ایک گاڑی 180 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 40 کلومیٹر طے کرنے میں کتنا وقت لگے گا؟' },
          { prompt: '10. ایک جہاز 900 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہا ہے۔ 30 کلومیٹر فاصلہ طے کرنے میں کتنا وقت لگے گا؟' },
          { prompt: '11. ایک جہاز 240 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہا ہے۔ 840 کلومیٹر فاصلہ طے کرنے میں کتنا وقت لگے گا؟' },
          { prompt: '12. ایک کار 315 کلومیٹر فی گھنٹہ کی سپیڈ سے جارہی ہے۔ 12 منٹ میں کتنا فاصلہ طے کرے گی؟' },
        ],
      },
      {
        id: 'batch-a-p89-eggs',
        kind: 'math',
        title: 'Questinos Related to Eggs',
        language: 'ur',
        sourcePage: '89',
        items: [
          { prompt: '1. 22 روپے درجن انڈے ہوں تو 30 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '2. درجن انڈوں کی قیمت 17 روپے ہو تو 3 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '3. درجن انڈوں کی قیمت 9 روپے ہو تو 15 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '4. درجن انڈوں کی قیمت 30 روپے ہو تو 2.5 درجن انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '5. درجن انڈوں کی قیمت 9 روپے ہو تو 3 درجن انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '6. 27 روپے درجن انڈے ہوں تو 14 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '7. 40 روپے کے 60 انڈے ہوں تو 6 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '8. 30 روپے کے درجن انڈے ہوں تو 5 روپے کے کتنے انڈے آئیں گے؟' },
          { prompt: '9. 17 روپے کے درجن انڈے ہوں تو 9,7,6,4,5,3,8 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '10. 22 روپے کے درجن انڈے ہوں تو 4,3,8,6,9,11,24,30 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '11. 9 روپے کے درجن انڈے ہوں تو 11,3,4,8,24,30,42 انڈوں کی قیمت کیا ہوگی؟' },
          { prompt: '12. 21 روپے کے درجن انڈے ہوں تو 3,4,6,8,9,1.24,30,42 انڈوں کی قیمت کیا ہوگی؟', detail: 'The source appears to print a dot between 1 and 24. It is retained as 1.24 rather than assuming either a decimal egg count or two comma-separated counts.' },
          { prompt: '13. 20 روپے کے درجن انڈے ہوں تو 3,4,6,8,9,24,30,42,36 انڈوں کی قیمت کیا ہوگی؟' },
        ],
      },
    ],
    issues: [
      'Page 89, speed questions 7 and 8: the source prints کلومیٹر فی گھنٹہ as the unit of a distance travelled in a stated number of minutes. No corrected question or calculated answer has been substituted.',
      'Page 89, eggs question 12: source numeric run appears 3,4,6,8,9,1.24,30,42. The separator between 1 and 24 looks like a dot; whether a decimal or a mistyped comma was intended cannot be inferred.',
    ],
  },
  {
    fileName: 'IMG20260919120223.jpg',
    sections: [
      {
        id: 'batch-a-p90-islamic-knowledge',
        kind: 'knowledge',
        title: 'غزوہ احد، فرشتہ رضوان اور مساجد',
        language: 'ur',
        sourcePage: '90',
        items: [
          { prompt: 'غزوہ احد کی اہم وجوہات', answer: '(۱) اسلام دشمنی\n(۲) غزوہ بدر کا انتقام\n(۳) کچھ مویشی مدینے کے قریب آئے تھے ان پر جھگڑا ہوگیا تھا۔', detail: 'The third reason is reproduced as printed. This historical claim needs verification rather than being treated as an established cause.' },
          { prompt: 'فرشتہ رضوان کسے کہتے ہیں؟', answer: 'فرشتہ رضوان جنت کے داروغہ کو کہا جاتا ہے۔' },
          { prompt: 'مسجد حرام کہاں واقع ہے؟', answer: 'مسجد حرام مکہ مکرمہ میں واقع ہے۔' },
          { prompt: 'مسجد نبوی ﷺ کہاں واقع ہے؟', answer: 'مسجد نبوی ﷺ مدینہ پاک میں واقع ہے۔' },
          { prompt: 'مسجد اقصیٰ کہاں واقع ہے؟', answer: 'مسجد اقصیٰ بیت المقدس میں واقع ہے۔' },
          { prompt: 'مسجد قبا کہاں واقع ہے؟', answer: 'مسجد قبا مدینے سے کچھ فاصلے پر مکہ کی طرف قبا کے مقام پر واقع ہے۔' },
          { prompt: 'مسجد نمرہ کہاں واقع ہے؟', answer: 'مسجد نمرہ میدان عرفات میں واقع ہے۔' },
          { prompt: 'مسجد صوفیہ کہاں واقع ہے؟', answer: 'مسجد صوفیہ استنبول (ترکی) میں واقع ہے۔' },
          { prompt: 'شاہ فیصل مسجد کہاں واقع ہے؟', answer: 'شاہ فیصل مسجد اسلام آباد (پاکستان) میں واقع ہے۔' },
          { prompt: 'بابری مسجد کہاں واقع ہے؟', answer: 'بابری مسجد ہندوستان میں ہے اسے 6 دسمبر 1992ء میں ہندو ملعونوں نے شہید کیا۔', detail: 'The derogatory wording ملعونوں is reproduced solely for fidelity to the printed source, not endorsed.' },
        ],
      },
      {
        id: 'batch-a-p91-mosques',
        kind: 'knowledge',
        title: 'مساجد کے مقامات',
        language: 'ur',
        sourcePage: '91',
        items: [
          { prompt: 'شاہی مسجد کہاں واقع ہے؟', answer: 'شاہی مسجد دہلی (انڈیا) میں واقع ہے۔' },
          { prompt: 'بادشاہی مسجد کہاں واقع ہے؟', answer: 'بادشاہی مسجد لاہور (پاکستان) میں واقع ہے۔' },
          { prompt: 'مسجد قرطبہ کہاں واقع ہے؟', answer: 'مسجد قرطبہ (قرطبہ) سپین میں واقع ہے۔' },
          { prompt: 'مسجد قبلتین کہاں واقع ہے؟', answer: 'مسجد قبلتین مدینہ پاک میں واقع ہے جہاں قبلہ تبدیل ہوا تھا۔' },
          { prompt: 'مسجد جن کہاں واقع ہے؟', answer: 'مسجد جن مکہ مکرمہ میں واقع ہے۔ (جن نبی کریم ﷺ کی تلاوت سن کر ایمان لائے)' },
        ],
      },
    ],
    issues: [
      'Page 90, first answer, reason (۳): the printed cattle-dispute explanation for Ghazwa Uhud is preserved but requires historical verification.',
      'Page 90, final answer about Babri Mosque: the source uses the derogatory word ملعونوں. It is retained as a transcription of the source, not endorsed.',
    ],
  },
  {
    fileName: 'IMG20260919120226.jpg',
    sections: [
      {
        id: 'batch-a-p92-islamic-knowledge',
        kind: 'knowledge',
        title: 'اسلامی معلومات: انبیاء، نمازیں اور تاریخ',
        language: 'ur',
        sourcePage: '92',
        items: [
          { prompt: 'ابوالانبیاء کس پیغمبر کا نام ہے؟', answer: 'ابوالانبیاء حضرت ابراہیم علیہ السلام کا نام ہے۔' },
          { prompt: 'حزب اللہ سے کیا مراد ہے؟', answer: 'حزب اللہ سے مراد مسلمان ہیں۔' },
          { prompt: 'اللہ رب العزت کے پانچ صفاتی نام کون سے ہیں؟', answer: '(۱) الرحمن\n(۲) الرحیم\n(۳) الغفار\n(۴) الرزاق\n(۵) القدوس' },
          { prompt: 'ٹوٹل نمازوں کے فرض ملا کر کتنے بنتے ہیں؟', answer: 'ٹوٹل نمازوں کے فرض 17 بنتے ہیں۔' },
          { prompt: 'اسلام کے عظیم جرنیل کون سے ہیں؟', answer: '(۱) نبی کریم ﷺ\n(۲) حضرت علیؓ\n(۳) حضرت سعد بن ابی وقاصؓ\n(۴) حضرت خالد بن ولیدؓ\n(۵) حضرت ابوعبیدہ بن جراحؓ\n(۶) موسیٰ بن نصیر\n(۷) حضرت عبدالرحمن بن ابوبکرؓ\n(۸) طارق بن زیاد\n(۹) صلاح الدین ایوبی\n(۱۰) ٹیپو سلطان\n(۱۱) محمد بن قاسم', detail: 'The small honorific after موسیٰ بن نصیر in entry (۶) is indistinct.' },
          { prompt: 'حجر اسود کب نصب ہوا؟', answer: 'حجر اسود 606ء میں نصب ہوا۔', detail: '606ء is the printed date. The historical date should be verified; no alternative date has been substituted.' },
          { prompt: 'حرب فجار کسے کہتے ہیں؟', answer: 'حرمت والے مہینوں میں یہ جنگ لڑی گئی۔ ... قریش کی دوسرے قبیلے سے اس لئے اسے فاجروں کی جنگ کہا جاتا ہے۔', detail: 'A short word immediately before قریش is not reliably legible. The surrounding printed wording is preserved, including its incomplete grammatical construction.' },
          { prompt: 'جہری نمازیں کون سی ہیں؟', answer: 'فجر۔ مغرب۔ عشاء۔ جمعہ المبارک۔ عیدین' },
          { prompt: 'سری نمازیں کون سی ہیں؟', answer: 'ظہر۔ عصر۔ نماز جنازہ' },
        ],
      },
      {
        id: 'batch-a-p93-islamic-knowledge',
        kind: 'knowledge',
        title: 'میثاق مدینہ، غزوہ خندق اور اسلامی اصطلاحات',
        language: 'ur',
        sourcePage: '93',
        items: [
          { prompt: 'میثاق مدینہ کی شرائط', answer: '(۱) آنحضور ﷺ تمام فریقین کے ثالث ہوں گے اور ان کا فیصلہ آخری ہوگا۔\n(۲) مذہبی آزادی ہر فریق کو ہوگی۔\n(۳) بیرونی حملے کی صورت میں سب مل کر مقابلہ کریں گے۔\n(۴) ایک کا دشمن سب کا دشمن ہوگا۔' },
          { prompt: 'غزوہ خندق میں خندق کھودنے کا مشورہ کس نے دیا؟', answer: 'غزوہ خندق میں خندق کھودنے کا مشورہ حضرت سلمان فارسیؓ نے دیا۔' },
          { prompt: 'بیعت رضوان کا دوسرا نام کیا ہے؟', answer: 'بیعت رضوان کا دوسرا نام بیعت شجر ہے۔' },
          { prompt: 'رب کا مطلب کیا ہے؟', answer: 'رب کا مطلب پالنے والا ہے۔' },
          { prompt: 'خطبہ حجۃ الوداع کے اہم نقاط کون سے ہیں؟', answer: 'خطبہ حجۃ الوداع کے اہم نقاط: مساوات کا درس۔ عورتوں و غلاموں کے حقوق۔ قرآن و سنت کامیابی کا راستہ' },
          { prompt: 'جبل نور اور جبل رحمت کس مقام پر واقع ہیں؟', answer: 'جبل نور اور جبل رحمت عرفات کے مقام پر واقع ہیں۔', detail: 'The source places both named mountains at Arafat. This combined location claim is questionable and should be verified; the printed answer has not been replaced.' },
          { prompt: 'روح القدس سے کیا مراد ہے؟', answer: 'روح القدس سے مراد حضرت جبرائیل ہیں۔' },
          { prompt: 'نبی اور رسول میں کیا فرق ہے؟', answer: 'نبی پرانی شریعت پر تبلیغ کرتے تھے جبکہ رسول کتاب کے ساتھ نئی شریعت کی تبلیغ کرتے تھے۔' },
        ],
      },
    ],
    issues: [
      'Page 92, Islam generals list, entry (۶): the small honorific after موسیٰ بن نصیر is unclear.',
      'Page 92, answer to حرب فجار کسے کہتے ہیں؟: the short word immediately before قریش is unclear. Partial text: حرمت والے مہینوں میں یہ جنگ لڑی گئی۔ ... قریش کی دوسرے قبیلے سے اس لئے اسے فاجروں کی جنگ کہا جاتا ہے۔',
      'Page 92, حجر اسود answer: the printed date 606ء requires historical verification.',
      'Page 93, جبل نور اور جبل رحمت answer: the source locates both at عرفات. This is a factual concern requiring verification, not a silently corrected answer.',
    ],
  },
  {
    fileName: 'IMG20260919120229.jpg',
    sections: [
      {
        id: 'batch-a-p94-islamic-history',
        kind: 'knowledge',
        title: 'جنگ یرموک، خلافت عثمان، جنگ جمل اور صلح حدیبیہ',
        language: 'ur',
        sourcePage: '94',
        items: [
          { prompt: 'اس جنگ میں مسلمان کتنی تعداد میں شہید ہوئے اور ایرانی کتنے قتل ہوئے؟', answer: 'اس جنگ میں مسلمان 6000 شہید ہوئے اور ایرانی 30,000 کی تعداد میں مارے گئے۔', detail: 'The question begins اس جنگ without naming the battle on this line. The missing reference is not supplied.' },
          { prompt: 'جنگ یرموک کب ہوئی اور اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'جنگ یرموک (15 ہجری) میں ہوئی۔ اس میں مسلمان 30,000 کی تعداد میں اور کفار 2,40,000 کی تعداد میں تھے۔ مسلمانوں کی طرف سے امیر حضرت خالد بن ولیدؓ تھے جبکہ کفار کی طرف سے ہرقل روم امیر تھا۔', detail: 'The printed troop totals and description of Heraclius as opposing commander are retained as source claims, not independently verified figures.' },
          { prompt: 'اس جنگ میں مسلمان کتنی تعداد میں شہید ہوئے اور رومی کتنے قتل ہوئے؟', answer: 'اس جنگ میں مسلمان 3000 شہید ہوئے جبکہ رومی 10,000 کی تعداد میں مارے گئے۔' },
          { prompt: 'حضرت عثمانؓ کے دور خلافت میں شمالی افریقہ کی فتوحات میں کون کون سے ملک تھے؟', answer: 'حضرت عثمانؓ کے دور خلافت میں شمالی افریقہ کی فتوحات میں ترکی کی فتح، قبرص کی فتح اور ایتھن پر حملہ ہوا۔', detail: 'The last place name appears printed as ایتھن. The source groups Turkey and Cyprus under North African conquests; that geographical and historical grouping requires verification.' },
          { prompt: 'پہلا بحری بیڑہ کس نے بھیجا؟', answer: 'پہلا بحری بیڑہ حضرت عثمانؓ نے بھیجا اور حضرت عثمانؓ بہت حیادار تھے۔' },
          { prompt: 'جنگ جمل کب ہوئی اور کس مقام پر لڑی گئی؟', answer: 'جنگ جمل 656 عیسوی کو بصرہ کے مقام پر حضرت علیؓ اور حضرت عائشہؓ کے درمیان لڑی گئی۔' },
          { prompt: 'مسجد نمرہ کہاں اور کیوں مشہور ہے؟', answer: 'میدان عرفات میں واقع ہے اور یہاں پر حج کا خطبہ دیا جاتا ہے۔' },
          { prompt: 'مسجد ذوالقبلتین کہاں اور کیوں مشہور ہے؟', answer: 'مدینہ میں واقع ہے اور یہاں پر قبلہ تبدیل کرنے کا حکم ہوا تھا۔' },
          { prompt: 'صلح حدیبیہ کی شرائط', answer: '(۱) مسلمان اس سال واپس چلے جائیں اور اگلے سال عمرے کے لئے آجائیں۔\n(۲) اگر کوئی مسلمان مدینہ سے مکہ آگیا تو اسے واپس نہیں کیا جائے گا اور کوئی مکہ سے مدینہ آگیا تو اسے واپس کر دیا جائے گا۔\n(۳) یہ معاہدہ دس سال کے لئے ہوگا۔\n(۴) مسلمان اگلے سال ہتھیار نہیں لائیں گے۔ اگر لائے تو نیام میں ہوں گے۔' },
        ],
      },
      {
        id: 'batch-a-p95-battles',
        kind: 'knowledge',
        title: 'غزوہ موتہ، حنین، تبوک اور جنگ قادسیہ',
        language: 'ur',
        sourcePage: '95',
        items: [
          { prompt: 'غزوہ موتہ میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'غزوہ موتہ میں مسلمانوں کی تعداد 8000 تھی جبکہ کفار 10,000 تھے۔', detail: '8000 and 10,000 are the printed figures. These troop totals are questionable and need verification.' },
          { prompt: 'غزوہ حنین کب ہوئی اور اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'غزوہ حنین (8 ہجری) 630ء میں ہوئی اور اس میں مسلمانوں کی تعداد 12,000 تھی اور امیر نبی کریم ﷺ تھے۔ یہ غزوہ بنو ہوازن اور بنی ثقیف کے خلاف تھا۔', detail: 'The printed answer does not supply an opposing troop count despite the question requesting one.' },
          { prompt: 'غزوہ حنین میں کتنے کفار قیدی ہوئے اور اس میں مال غنیمت میں کتنی بکریاں تھیں؟', answer: 'غزوہ حنین میں 6000 کفار قیدی ہوئے اور 20,000 بکریاں مال غنیمت میں تھیں۔' },
          { prompt: 'غزوہ تبوک کب ہوئی اور کس کے خلاف لڑی گئی؟', answer: 'غزوہ تبوک (9 ہجری) 630ء میں لڑی گئی اور کفار کے خلاف لڑی گئی۔' },
          { prompt: 'اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'اس میں مسلمانوں کی تعداد 30,000 تھی جبکہ کفار کی تعداد 1,000,00 تھی۔ امیر نبی کریم ﷺ مسلمانوں کی طرف سے تھے اور کفار کی طرف سے امیر ہرقل روم تھا۔', detail: 'The unusual number grouping 1,000,00 is printed in the source and retained. The troop totals and opposing command attribution are not independently verified.' },
          { prompt: 'غزوہ حنین کے بعد نبی کریم ﷺ نے کس مسجد کو جلا دیا؟', answer: 'غزوہ حنین کے بعد نبی کریم ﷺ نے مسجد ضرار کو جلا دیا۔', detail: 'The source explicitly says حنین. The association of this event with Hunayn rather than Tabuk is a historical concern requiring verification.' },
          { prompt: 'اس غزوہ میں مسلمان کتنے دن تک دشمن کے منتظر رہے؟', answer: 'اس غزوہ میں 20 دن تک مسلمان دشمن کے منتظر رہے مگر کوئی سامنے نہ آیا۔' },
          { prompt: 'جنگ قادسیہ کب ہوئی اور اس میں کون سا ملک فتح ہوا؟', answer: 'جنگ قادسیہ (14 ہجری) میں ہوئی۔ اس میں ایران فتح ہوا۔ مسلمانوں کی طرف سے امیر سعد بن ابی وقاصؓ تھے۔' },
          { prompt: 'ایرانیوں کا سپہ سالار اور بادشاہ کون تھا؟', answer: 'ایرانیوں کا سپہ سالار رستم تھا جبکہ بادشاہ یزدگرد تھا۔' },
        ],
      },
    ],
    issues: [
      'Page 94, first question: اس جنگ is a continuation reference, with no battle name in the question itself.',
      'Page 94, answer about North African conquests under Uthman: final place name appears as ایتھن. The grouping of Turkey and Cyprus as North African conquests needs verification.',
      'Page 95, Mutah answer: printed strengths 8000 Muslims and 10,000 opposing troops are retained but questionable.',
      'Page 95, Hunayn answer: the source omits the opposing troop number requested in the question.',
      'Page 95, Tabuk strength answer: the source prints the irregular numeric grouping 1,000,00.',
      'Page 95, mosque-burning question and answer: both print غزوہ حنین; the historical event attribution should be checked rather than silently changed.',
      'Pages 94 and 95: battle-strength, casualty and opposing-command claims are transcribed source content, not verified historical corrections.',
    ],
  },
  {
    fileName: 'IMG20260919120232.jpg',
    sections: [
      {
        id: 'batch-a-p96-battles',
        kind: 'knowledge',
        title: 'غزوہ احد، خندق، خیبر اور موتہ',
        language: 'ur',
        sourcePage: '96',
        items: [
          { prompt: 'غزوہ احد میں مسلمان کتنے شہید ہوئے اور کفار کتنے مارے گئے؟', answer: 'غزوہ احد میں 70 مسلمان شہید ہوئے جبکہ کفار 30 مارے گئے۔' },
          { prompt: 'اس جنگ میں کون سے رضی اللہ تعالیٰ عنہ شہید ہوئے؟', answer: 'اس جنگ میں امیر حمزہ سید الشہداءؓ شہید ہوئے۔', detail: 'The unusual wording کون سے رضی اللہ تعالیٰ عنہ is printed in the question.' },
          { prompt: 'غزوہ احزاب یا خندق کب ہوئی؟', answer: 'غزوہ خندق یا غزوہ احزاب (5 ہجری) 627ء میں ہوئی۔' },
          { prompt: 'اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'اس میں مسلمانوں کی تعداد 3000 تھی جبکہ کفار کی تعداد 10,000 تھی۔' },
          { prompt: 'غزوہ خندق میں خندق کی گہرائی اور چوڑائی کتنی تھی؟', answer: 'غزوہ خندق میں خندق کی چوڑائی 5 گز اور گہرائی 5 گز تھی۔' },
          { prompt: 'کفار نے اس میں کتنے دن محاصرہ کیا؟', answer: 'اس میں کفار نے 27 روز تک محاصرہ کیا اور آندھی آنے پر کفار نے محاصرہ چھوڑا اور بھاگ گئے۔' },
          { prompt: 'غزوہ خیبر کب ہوئی اور اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'غزوہ خیبر (7 ہجری) 628ء میں ہوئی۔ اس میں مسلمان 1600 اور کفار 10,000 تھے۔' },
          { prompt: 'غزوہ خیبر میں مسلمان کتنے دن تک لڑتے رہے اور یہودی کتنے مارے گئے؟', answer: 'مسلمان 2 ماہ تک لڑتے رہے۔ اس غزوہ میں 93 یہودی مارے گئے۔' },
          { prompt: 'غزوہ موتہ کب ہوئی اور کس کے خلاف لڑی گئی؟', answer: 'غزوہ موتہ (8 ہجری) 629ء میں شامیوں کے خلاف لڑی گئی۔' },
          { prompt: 'غزوہ موتہ میں مسلمان کتنے شہید ہوئے اور کفار کتنے قتل ہوئے؟', answer: 'غزوہ موتہ میں مسلمان 12 شہید ہوئے جبکہ کفار کئی سو مارے گئے۔ اس غزوہ میں خالد بن ولیدؓ کو سیف اللہ کا خطاب ملا۔' },
        ],
      },
      {
        id: 'batch-a-p97-caliphs-badr-uhud',
        kind: 'knowledge',
        title: 'حضرت عثمان، حضرت علی، غزوہ بدر اور احد',
        language: 'ur',
        sourcePage: '97',
        items: [
          { prompt: 'حضرت عثمانؓ بن عفان کا دور خلافت کتنا تھا؟', answer: 'آپؓ کا دور خلافت 11 سال 11 ماہ اور 17 دن تھا۔' },
          { prompt: 'حضرت عثمان بن عفانؓ کے دور کے اہم واقعات کون سے تھے؟', answer: 'قرآن مجید کی جمع و اشاعت۔ سلطنت میں باجماعت کا نظام', detail: 'The second phrase appears as سلطنت میں باجماعت کا نظام in the source; its intended historical meaning is unclear.' },
          { prompt: 'حضرت عثمان بن عفانؓ کو شہید کرنے والے کون تھے؟', answer: 'آپؓ کو شہید کرنے والے حامد بن یاسر، عبداللہ بن سب... تھے۔', detail: 'The first name appears as حامد بن یاسر. The second name reads عبداللہ بن سب with an unclear final letter resembling ی. Its apparent full reading is عبداللہ بن سبی, but the uncertain letter is not inserted into the transcription. The source attribution is a disputed or questionable historical claim, not a verified identification.' },
          { prompt: 'حضرت علیؓ نبی کریم ﷺ کے رشتے میں کون تھے؟', answer: 'حضرت علیؓ نبی کریم ﷺ کے داماد تھے اور آپؓ کے نکاح میں نبی کریم ﷺ کی بیٹی حضرت فاطمہؓ آئیں۔' },
          { prompt: 'حضرت علی بن ابوطالبؓ کا دور خلافت کتنا تھا؟', answer: 'آپؓ کا دور خلافت 4 سال 9 ماہ اور 3 دن تھا۔' },
          { prompt: 'حضرت علی بن ابوطالبؓ کے دور میں اہم واقعات کون سے تھے؟', answer: 'جنگ جمل 656ء۔ جنگ ناروان (خارجیوں کے خلاف)', detail: 'The second battle name appears printed as ناروان; the spelling is preserved rather than silently corrected.' },
          { prompt: 'حضرت علی بن ابوطالبؓ کو کس وقت اور کس نے شہید کیا؟', answer: '40 ہجری کو آپؓ کو نماز ادا کرتے ہوئے شہید کیا گیا اور آپؓ کو شہید کرنے والا عبدالرحمن ابن ملجم تھا۔' },
          { prompt: 'غزوہ بدر کب ہوئی اور اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'غزوہ بدر (2 ہجری) 623ء میں ہوئی اور اس میں مسلمانوں کی تعداد 313 جبکہ کفار تقریباً 1000 کی تعداد میں تھے۔', detail: '623ء is the printed year and is historically questionable. It is retained without substituting a corrected date.' },
          { prompt: 'غزوہ بدر میں جنگی قیدی کتنی تعداد میں تھے اور مسلمان کتنے شہید ہوئے اور کفار کتنے قتل ہوئے؟', answer: 'غزوہ بدر میں جنگی قیدی 70 تھے اور 14 مسلمان شہید ہوئے جبکہ کفار 72 کی تعداد میں مارے گئے۔', detail: 'The source explicitly prints 72 for opposing deaths. This figure needs verification.' },
          { prompt: 'غزوہ احد کب ہوئی اور اس میں مسلمانوں کی تعداد کتنی تھی اور کفار کی تعداد کتنی تھی؟', answer: 'غزوہ احد (3 ہجری) 625ء میں ہوئی اور اس میں مسلمانوں کی تعداد 750 تھی جبکہ کفار 3000 کی تعداد میں تھے۔', detail: 'The source prints 750 for Muslim strength. This figure is retained as a source claim requiring verification.' },
        ],
      },
    ],
    issues: [
      'Page 97, Uthman important-events answer, second phrase: سلطنت میں باجماعت کا نظام is the apparent wording, but its intended meaning is unclear.',
      'Page 97, Uthman assassination answer: the first name appears حامد بن یاسر. The final letter of the second name is unclear and resembles ی. Partial text retained: عبداللہ بن سب... تھے۔ Both the exact names and the attribution need verification.',
      'Page 97, Ali important-events answer: the second battle name appears ناروان, retained as printed.',
      'Page 97, Badr date: source prints 623ء alongside 2 ہجری. The date needs verification.',
      'Page 97, Badr losses and Uhud strength: source prints 72 opposing deaths and 750 Muslim troops respectively. These figures are retained but questionable.',
    ],
  },
  {
    fileName: 'IMG20260919120236.jpg',
    sections: [
      {
        id: 'batch-a-p98-ashra-list-continuation',
        kind: 'knowledge',
        title: 'عشرہ مبشرہ کے نام: فہرست کا تسلسل',
        language: 'ur',
        sourcePage: '98',
        items: [
          { prompt: '(۳) حضرت سعد بن ابی وقاصؓ' },
          { prompt: '(۴) حضرت طلحہؓ' },
          { prompt: '(۵) حضرت زبیرؓ' },
          { prompt: '(۶) حضرت سعد بن زیدؓ', detail: 'The source appears to print سعد rather than سعید. The printed name is retained and needs verification.' },
          { prompt: 'اور چاروں خلفائے راشدین' },
        ],
      },
      {
        id: 'batch-a-p98-caliphs',
        kind: 'knowledge',
        title: 'خلافت، صحابہ اور اسلامی تاریخ',
        language: 'ur',
        sourcePage: '98',
        items: [
          { prompt: 'خلافت کا آغاز کب ہوا؟', answer: 'خلافت کا آغاز 11 ہجری سے ہوا۔' },
          { prompt: 'نبی کریم ﷺ کے سسر کون تھے؟', answer: 'نبی کریم ﷺ کے سسر حضرت ابوبکر صدیقؓ تھے۔ آپؓ کی بیٹی حضرت عائشہؓ کا نکاح حضور ﷺ سے ہوا۔\nحضرت عمرؓ بھی آپ ﷺ کے سسر تھے۔ آپؓ کی بیٹی حضرت حفصہؓ کا نکاح حضور ﷺ سے ہوا۔' },
          { prompt: 'جنگ سلاسل کب اور کس کے خلاف ہوئی؟', answer: '632ء میں عراق کے خلاف روم کے ساتھ تصادم کی وجہ سے ہوئی۔', detail: 'The source combines Iraq and Rome in this answer. This historical description is questionable and is preserved rather than corrected.' },
          { prompt: 'حضرت عبداللہؓ نے کب وفات پائی؟', answer: 'حضرت عبداللہؓ نے 21 جمادی الثانی 534 میں وفات پائی۔', detail: 'The source prints the name عبداللہ and the year 534. The identity and date require verification; no missing century or alternate name has been supplied.' },
          { prompt: 'حضرت عمر فاروقؓ رشتے میں نبی کریم ﷺ کے کیا تھے؟', answer: 'حضرت عمر فاروقؓ نبی کریم ﷺ کے رشتے میں سسر تھے۔ آپ کی بیٹی حضرت حفصہ نبی کریم ﷺ کے نکاح میں آئیں۔' },
          { prompt: 'حضرت عمر بن الخطابؓ کا دور خلافت کتنا تھا؟', answer: 'حضرت عمر بن الخطابؓ کا دور خلافت 10 سال ماہ 4 دن تھا۔', detail: 'No month-count numeral is clearly visible between سال and ماہ. No number has been inferred.' },
          { prompt: 'حضرت عمرؓ کے دور کے اہم واقعات کے بارے میں بیان کریں۔', answer: 'ایران اور عراق کی فتح۔ جنگ قادسیہ (ایرانیوں کے خلاف)۔ دمشق کی فتح۔ معرکہ یرموک (15 ہجری ...۳۷ء)۔ بیت المقدس کی فتح۔', detail: 'The Gregorian year beside 15 ہجری ends in ۳۷, but its first digit is not reliably legible and resembles ۱ or ۶. No complete year is inferred.' },
          { prompt: 'حضرت عثمانؓ نبی کریم ﷺ کے رشتے میں کیا تھے اور حضرت عثمانؓ کو کیا کہا جاتا ہے؟', answer: '... نبی کریم ﷺ کے داماد تھے اور ان کے نکاح میں نبی کریم ﷺ کی دو بیٹیاں حضرت رقیہؓ اور حضرت ام کلثومؓ یکے ... میں اس لئے ان کو ذوالنورین یعنی دو نوروں والا کہا جاتا ہے۔', detail: 'A hand covers the right-hand beginning of this answer and the beginning of its next line. Ellipses mark the covered text, including the words after یکے. Only visible wording is transcribed.' },
        ],
      },
      {
        id: 'batch-a-p99-worship-companions',
        kind: 'knowledge',
        title: 'وضو، تیمم، صحابہ اور عشرہ مبشرہ',
        language: 'ur',
        sourcePage: '99',
        items: [
          { prompt: 'وضو کے فرائض کیا ہیں؟', answer: 'فرائض: (۱) منہ دھونا\n(۲) ہاتھوں کو کہنیوں تک دھونا\n(۳) چوتھائی سر کا مسح کرنا\n(۴) پاؤں ٹخنوں سمیت دھونا' },
          { prompt: 'تیمم کے فرائض کیا ہیں؟', answer: 'فرائض: (۱) نیت کرنا\n(۲) مٹی والا ہاتھ منہ پر پھیرنا\n(۳) کہنیوں تک تمام ہاتھ پھیرنا' },
          { prompt: 'صحابی کسے کہتے ہیں', answer: 'صحابی: جنہوں نے ایمان کی حالت میں رسول ﷺ کو دیکھا یا سنا ہو اور ایمان کی حالت میں فوت ہوئے ہوں۔' },
          { prompt: 'عورتوں، مردوں اور بچوں میں سب سے پہلے کون ایمان لایا۔', answer: 'عورتوں میں سب سے پہلے حضرت خدیجہؓ اور مردوں میں سب سے پہلے حضرت ابوبکر صدیقؓ اور بچوں میں سب سے پہلے حضرت علیؓ تھے۔' },
          { prompt: 'غلاموں میں سب سے پہلے کون سے صحابی ایمان لائے؟', answer: 'غلاموں میں سب سے پہلے حضرت زید بن حارثؓ ایمان لائے۔' },
          { prompt: 'مردوں اور عورتوں میں اسلام کے سب سے پہلے شہید کون تھے؟', answer: 'مردوں میں حضرت حارث بن ابی ہالہ اور عورتوں میں حضرت سمیہؓ شہید ہوئے۔', detail: 'The printed identification of the first male martyr is retained as a historical source claim requiring verification.' },
          { prompt: 'پہلے امیر حج کون مقرر ہوئے؟', answer: 'پہلے امیر حج حضرت ابوبکر صدیقؓ مقرر ہوئے۔' },
          { prompt: 'اسلام کے پہلے مبلغ کون تھے اور انہیں تبلیغ کے لئے کہاں بھیجا گیا؟', answer: 'اسلام کے پہلے مبلغ حضرت مصعب بن عمیرؓ تھے اور ان کو مدینہ تبلیغ کے لئے بھیجا گیا۔' },
          { prompt: 'اصحاب صفہ کون تھے اور یہ علم کہاں حاصل کرتے اور ان کی تعداد کتنی تھی؟', answer: 'اصحاب صفہ مسجد نبوی ﷺ کے ساتھ منسلک چبوترے میں علم حاصل کرتے تھے اور ان کی تعداد 70 تھی۔' },
          { prompt: 'ایسے کون سے صحابی ہیں جنہوں نے حضور اکرم ﷺ کو زندہ دیکھا ہو اور نہ ملا لیکن صحابی کہلا گئے؟', answer: 'حضرت اویس قرنیؓ تھے جنہوں نے حضور اکرم ﷺ کو زندہ دیکھا اور نہ ملا مگر صحابی کہلائے۔', detail: 'The source says زندہ دیکھا اور نہ ملا and classifies Uwais Qarni as a Sahabi. Both the wording and the companion classification are questionable historical claims, preserved rather than silently corrected.' },
          { prompt: 'عشرہ مبشرہ سے کیا مراد ہے اور ان کی تعداد کتنی تھی؟', answer: 'یہ وہ صحابی تھے جنہیں زندگی میں ہی جنت کی بشارت دے دی گئی۔ ان کی تعداد 10 تھی۔\n(۱) حضرت ابوعبیدہ ابن الجراحؓ\n(۲) حضرت عبدالرحمن بن عوفؓ', detail: 'The remaining visible names, numbered (۳) to (۶), followed by اور چاروں خلفائے راشدین, are printed at the top of facing page 98 and transcribed in the separate continuation section.' },
        ],
      },
    ],
    issues: [
      'Page 98 begins with numbered entries (۳) through (۶) and اور چاروں خلفائے راشدین, apparently continuing the Ashra Mubashshara answer at the bottom of facing page 99. Printed page labels and order are retained.',
      'Page 98, continuation entry (۶): the name appears سعد بن زید. The printed spelling needs verification.',
      'Page 98, Battle of Chains answer: the Iraq and Rome wording is historically questionable.',
      'Page 98, حضرت عبداللہ death answer: source prints 21 جمادی الثانی 534. The name and year need verification.',
      'Page 98, Umar duration answer: a month-count numeral is not legible or is absent between 10 سال and ماہ 4 دن.',
      'Page 98, Umar important-events answer: the Gregorian year in معرکہ یرموک (15 ہجری ...۳۷ء) has an unclear first digit resembling ۱ or ۶; the ending ۳۷ is visible.',
      'Page 98, bottom Uthman answer: a hand obscures the right-side start and the next line start after the visible word یکے. Visible ending: میں اس لئے ان کو ذوالنورین یعنی دو نوروں والا کہا جاتا ہے۔',
      'Page 99, first male martyr answer and Uwais Qarni companion classification are preserved source claims requiring verification.',
    ],
  },
  {
    fileName: 'IMG20260919120240.jpg',
    sections: [
      {
        id: 'batch-a-p100-worship',
        kind: 'knowledge',
        title: 'اذان، روزہ، حج، زکوۃ، تیمم اور غسل',
        language: 'ur',
        sourcePage: '100',
        items: [
          { prompt: 'فجر کی اذان اور باقی اذانوں میں کون سے دو کلمات کا فرق ہے؟', answer: 'الصلوۃ خیر من النوم (نماز نیند سے بہتر ہے)' },
          { prompt: 'روزے کے لفظی معنی کیا ہیں اور یہ کب فرض ہوا؟', answer: 'روزے کے لفظی معنی ہیں رکنا اور ڈھال۔ روزہ (13 نبوی ﷺ) کو واقعہ معراج میں مسلمانوں پر فرض ہوا۔', detail: 'The source connects obligatory fasting with the Miraj and 13 نبوی. This chronology is a factual concern and has not been silently corrected.' },
          { prompt: 'روزے کا کفارہ کیسے ادا کیا جاتا ہے؟', answer: 'کفارہ مسلسل 60 روزے رکھنا یا پھر 60 مسکینوں کو کھانا کھلانے سے ادا ہوتا ہے۔', detail: 'This is the printed summary. Conditions, sequence and jurisprudential distinctions are not supplied by the source.' },
          { prompt: 'عید الفطر کب منائی جاتی ہے؟', answer: 'عید الفطر یکم شوال کو منائی جاتی ہے۔' },
          { prompt: 'حج کب فرض ہوا؟', answer: 'حج (9) ہجری کو فرض ہوا۔' },
          { prompt: 'حج کے فرائض کیا ہیں؟', answer: 'فرائض: (۱) نیت کرنا\n(۲) احرام باندھنا\n(۳) وقوف عرفات\n(...) طواف زیارت', detail: 'The small printed numeral before طواف زیارت is not certain, resembling ۲ or ۴. Its fourth position in the list is retained without inferring a numeral.' },
          { prompt: 'حج کا خطبہ کون سے ذوالحجہ اور کس مقام اور کس مسجد میں دیا گیا؟', answer: 'حج کا خطبہ (9 ذوالحجہ کو میدان عرفات میں مسجد نمرہ میں دیا گیا)' },
          { prompt: 'حج کی نیت کس مقام پر کی جاتی ہے؟', answer: 'حج کی نیت میقات کے مقام پر کی جاتی ہے۔' },
          { prompt: 'زکوۃ کے لفظی معنی کیا ہیں اور یہ کب فرض ہوئی اور زکوۃ کا تناسب کیا ہے؟', answer: 'زکوۃ کے لفظی معنی پاک کرنا ہے اور یہ دو ہجری کو فرض ہوئی۔ اور اس کا تناسب 2.5% ہے۔' },
          { prompt: 'پردہ اور تیمم کا حکم کب ہوا؟', answer: 'پردہ اور تیمم کا حکم (۳ ہجری) کو ہوا۔', detail: 'The printed combined dating is retained as a source claim requiring verification.' },
          { prompt: 'غسل کے فرائض کیا ہیں؟', answer: 'فرائض: (۱) ناک میں پانی ڈالنا (کچی ہڈی تک)\n(۲) کلی کرنا (حلق تک)\n(۳) پورے بدن پر ایک بار پانی بہانا' },
        ],
      },
      {
        id: 'batch-a-p101-religious-terms',
        kind: 'knowledge',
        title: 'فرض، سنت، نوافل، فرض کفایہ اور واجب',
        language: 'ur',
        sourcePage: '101',
        items: [
          { prompt: 'فرض سے کیا مراد ہے؟', answer: 'فرض وہ چیز جو ایمان لانے پر لازم ہو جاتی ہے۔ اس کا جان بوجھ کر چھوڑنا فاسق بناتا ہے۔' },
          { prompt: 'سنت سے کیا مراد ہے؟', answer: 'سنت وہ عمل ہے جو نبی اکرم ﷺ نے خود کیا ہو۔' },
          { prompt: 'سنت موکدہ سے کیا مراد ہے؟', answer: 'سنت موکدہ ایسا عمل ہے جس کا بلا عذر چھوڑنا جیسے عشاء کی نماز میں 2 سنتیں اور دوسری نمازوں کی موکدہ سنتیں۔', detail: 'The source sentence does not complete the clause جس کا بلا عذر چھوڑنا. No missing ruling has been supplied.' },
          { prompt: 'سنت غیر موکدہ سے کیا مراد ہے؟', answer: 'سنت غیر موکدہ ایسی سنت ہے جس کا ادا نہ کرنا گناہ نہیں مگر ادا کرنا ثواب ہے۔' },
          { prompt: 'نوافل کس لئے ادا کئے جاتے ہیں', answer: 'نوافل اپنے درجات کو بلند کرنے یا اللہ تعالیٰ سے مدد طلب کرنے کے لئے پڑھی جائے۔ یہ اللہ تعالیٰ کے قرب کا ذریعہ ہے جیسے چاشت، اوابین، وغیرہ۔' },
          { prompt: 'فرض کفایہ سے کیا مراد ہے؟', answer: 'وہ فرض جو چند اشخاص کے ادا کرنے سے اس بستی یا آبادی سے ساقط ہو جاتا ہے یعنی سب کی طرف سے ادا ہو جاتا ہے جیسے نماز جنازہ، اعتکاف وغیرہ۔', detail: 'The source includes اعتکاف as an example of فرض کفایہ. The precise jurisprudential classification should be verified.' },
          { prompt: 'واجب سے کیا مراد ہے؟', answer: 'وہ عمل جس کا درجہ فرض اور سنت کے درمیان ہو جیسے عشاء کے وتر اور عیدین کی نمازیں ہیں۔' },
          { prompt: 'اذان میں اللہ اکبر کتنی مرتبہ آتا ہے؟', answer: 'اذان میں اللہ اکبر (6) چھ بار آتا ہے۔' },
        ],
      },
    ],
    issues: [
      'Page 100, fasting-obligation answer: the source says 13 نبوی and واقعہ معراج. This historical attribution needs verification.',
      'Page 100, Hajj obligations list, fourth entry: the numeral before طواف زیارت resembles ۲ or ۴ and is not certain. Partial text: (...) طواف زیارت.',
      'Page 100, پردہ اور تیمم date answer: source prints (۳ ہجری) for both. This combined historical dating requires verification.',
      'Page 101, سنت موکدہ answer: the phrase جس کا بلا عذر چھوڑنا is grammatically unfinished in the printed text.',
      'Page 101, فرض کفایہ answer: the source example اعتکاف requires jurisprudential verification.',
    ],
  },
  {
    fileName: 'IMG20260919120242.jpg',
    sections: [
      {
        id: 'batch-a-p102-scriptures-prayers',
        kind: 'knowledge',
        title: 'مذہبی کتابیں اور نماز کے سوالات',
        language: 'ur',
        sourcePage: '102',
        items: [
          { prompt: 'مشہور مذہبی کتابیں کون سی ہیں اور ان کے نام بتائیں۔', answer: '(۱) قرآن پاک\n(۲) توریت\n(۳) انجیل\n(۴) زبور' },
          { prompt: 'نماز کی قرآن پاک میں کتنی بار تاکید کی گئی ہے؟', answer: 'نماز کی قرآن پاک میں 700 بار تاکید کی گئی ہے۔', detail: '700 is the source figure. It should be checked against a defined counting method rather than treated as a verified count.' },
          { prompt: 'سب سے پہلے کون سی دو نمازیں فرض ہوئیں', answer: 'نماز فجر اور نماز مغرب' },
          { prompt: 'موجودہ نمازیں کب فرض ہوئیں؟', answer: 'موجودہ نمازیں 27 رجب (12 نبوی کی رات کو) فرض ہوئیں۔', detail: 'The Nabawi year appears to be 12 in the source. This dating requires verification and is not reconciled with other dates elsewhere in the photographed notes.' },
          { prompt: 'نماز جمعہ کب فرض ہوا؟', answer: 'نماز جمعہ 13 نبوی ﷺ کو ہجرت سے قبل فرض ہوا۔' },
          { prompt: 'پہلی نماز جمعہ کون سی مسجد میں ادا ہوئی', answer: 'پہلی نماز جمعہ مسجد قباء میں (13 نبوی 13 ربیع الاول) کو ادا ہوئی۔', detail: 'The mosque and dates are reproduced as printed. The attribution of the first Friday prayer to Masjid Quba is a historical concern requiring verification.' },
          { prompt: 'نماز کی شرائط کیا کیا ہیں؟', answer: '(۱) جگہ کا پاک ہونا\n(۲) طہارت (وضو)\n(۳) ستر پوشی\n(۴) نماز کا وقت ہونا\n(۵) قبلہ رخ ہونا\n(۶) نیت کرنا' },
          { prompt: 'نماز استسقاء کس لئے پڑھی جاتی ہے؟', answer: 'نماز استسقاء بارش کے لئے پڑھی جاتی ہے۔' },
          { prompt: 'نماز قصر کس صورت میں ادا کی جا سکتی ہے؟', answer: 'جب آپ اپنے گھر سے کم از کم 48 میل کے فاصلے پر ہوں اور اس سفر میں یا اس جگہ پر آپ کا قیام 15 دن یا اس سے کم ہو تو پھر آپ ظہر، عصر اور عشاء کے دو فرض پڑھیں گے۔ مگر باقی نمازیں یعنی فجر اور مغرب اسی طرح پڑھیں گے۔', detail: 'The printed threshold includes 15 days. Jurisprudential conditions and the exact stay threshold should be checked before applying this summary.' },
          { prompt: 'نماز جنازہ کس لئے ادا کی جاتی ہے؟', answer: 'نماز جنازہ فوت ہونے والے مسلمان کی مغفرت کے لئے پڑھی جاتی ہے۔ نماز جنازہ ... ہجری کو لازم ہوئی۔', detail: 'The small year numeral before ہجری resembles ۲, but is not certain. It is left incomplete rather than inferred.' },
        ],
      },
      {
        id: 'batch-a-p103-quran-hadith-angels',
        kind: 'knowledge',
        title: 'قرآن پاک، حدیث اور فرشتے',
        language: 'ur',
        sourcePage: '103',
        items: [
          { prompt: 'قرآن پاک کا موضوع کیا ہے', answer: 'قرآن پاک کا موضوع انسان ہے اور ہر گوشہ زندگی میں رہنمائی کرتا ہے۔' },
          { prompt: 'قرآن مجید کون سی کتاب ہے؟', answer: 'قرآن پاک آفاقی کتاب ہے جس کے مقابلے میں کوئی کتاب پیش نہیں کی جا سکتی۔' },
          { prompt: 'قرآن پاک کے تین نام کون سے ہیں', answer: 'قرآن پاک کے تین نام: (۱) الکتاب\n(۲) الفرقان\n(۳) الشفاء' },
          { prompt: 'سنت سے کیا مراد ہے؟', answer: 'سنت سے مراد وہ کام ہیں جو نبی کریم ﷺ نے خود کئے ہوں اور آپ ﷺ نے ان سے منع نہ فرمایا ہو۔' },
          { prompt: 'سنت اور حدیث میں کیا فرق ہے؟', answer: 'سنت: جو کام نبی کریم ﷺ نے خود کر کے دکھایا ہو اور حدیث وہ کام جو نبی کریم ﷺ نے کرنے کا حکم دیا ہو۔', detail: 'The source gives a simplified distinction. It is transcribed as source wording, not as a comprehensive definition of hadith.' },
          { prompt: 'حدیث کی مشہور کتابیں کون سی ہیں', answer: '(۱) صحیح بخاری (امام محمد بن اسماعیل بخاری)\n(۲) صحیح مسلم (امام حجاج بن مسلم نیشاپوری)\n(۳) جامع ترمذی (امام ترمذی)\n(۴) سنن ابی داؤد (امام داؤد)\n(۵) سنن نسائی (احمد بن علی نسائی)\n(۶) سنن ابن ماجہ\nامام ابو عبداللہ محمد بن یزید ابن ماجہ', detail: 'The author line for Ibn Majah appears immediately below the list, beside the following question. The printed author names for Sahih Muslim and Sunan Abi Dawud are questionable and are retained rather than corrected.' },
          { prompt: 'مردوں میں کن صحابی سے سب سے زیادہ احادیث روایت ہیں؟', answer: 'مردوں میں سب سے زیادہ احادیث حضرت ابو ہریرہ سے روایت ہیں۔' },
          { prompt: 'عورتوں میں سب سے زیادہ احادیث کس سے روایت ہیں؟', answer: 'عورتوں میں سب سے زیادہ احادیث حضرت عائشہؓ سے روایت ہیں۔' },
          { prompt: 'فرشتوں کے نام بتائیں اور یہ اللہ تعالیٰ کے کون سے کام سر انجام دیتے ہیں؟', answer: '(۱) حضرت جبرائیل (انبیاء کی طرف اللہ تعالیٰ کی وحی لاتے تھے۔ سب سے معتبر فرشتے ہیں)\n(۲) حضرت میکائیل (اللہ تعالیٰ کی نعمتیں اور کائنات کے مفادات بارش وغیرہ مخلوق تک پہنچانا)\n(۳) حضرت اسرافیل (قیامت کے دن شور پھونکیں گے)\n(۴) حضرت عزرائیل (تمام جانداروں کی جان لینے پر مامور ہیں)', detail: 'Entry (۳) appears to print شور instead of the expected term صور. The apparent source spelling is retained.' },
        ],
      },
    ],
    issues: [
      'Page 102, Quran prayer-emphasis answer: printed count 700 is not independently verified.',
      'Page 102, existing-prayers date: Nabawi year appears 12 in the parenthesis after 27 رجب. The year and historical dating should be checked.',
      'Page 102, first Friday prayer answer: source prints مسجد قباء and (13 نبوی 13 ربیع الاول); mosque attribution and dates require verification.',
      'Page 102, qasr answer: source says a stay of 15 days or less. The threshold and jurisprudential context require verification.',
      'Page 102, final funeral-prayer answer: the small year numeral resembles ۲ but is not certain. Partial clause retained: نماز جنازہ ... ہجری کو لازم ہوئی۔',
      'Page 103, hadith books: printed author forms امام حجاج بن مسلم نیشاپوری and امام داؤد are retained but questionable. The separate Ibn Majah author line has also been included.',
      'Page 103, angels list, entry (۳): the word before پھونکیں گے appears شور rather than صور. Apparent source phrase retained: قیامت کے دن شور پھونکیں گے.',
    ],
  },
  {
    fileName: 'IMG20260919120246.jpg',
    sections: [
      {
        id: 'batch-a-p104-quran-questions',
        kind: 'knowledge',
        title: 'قرآن پاک کے متعلق سوالات',
        language: 'ur',
        sourcePage: '104',
        items: [
          { prompt: 'قرآن پاک میں صحابی رسول ﷺ زید بن حارث کا نام مبارک کون سی سورۃ میں آیا ہے', answer: 'صحابی زید بن حارث کا نام مبارک سورۃ احزاب میں آیا ہے۔' },
          { prompt: 'قرآن پاک میں کون سی دو عورتوں کو اچھے الفاظ میں یاد کیا گیا ہے', answer: '(۱) حضرت عائشہؓ\n(۲) حضرت مریم علیہ السلام', detail: 'The first printed name appears عائشہ. The source claim needs verification and has not been replaced with another name.' },
          { prompt: 'قرآن پاک میں کون سی دو عورتوں کو برے الفاظ میں یاد کیا گیا ہے؟', answer: '(۱) سورۃ لہب میں ابولہب کی بیوی ام جمیل کو\n(۲) حضرت لوط علیہ السلام کی بیوی کو' },
          { prompt: 'تدوین قرآن کا کام حضرت ابوبکر صدیقؓ نے شروع کیا۔ انہیں یہ مشورہ کس نے دیا؟', answer: 'پہلے حافظ قرآن حضرت عثمان غنیؓ ہیں اور انہیں جامع القرآن کہا جاتا ہے۔', detail: 'This is the answer printed under the question. It does not identify who advised Abu Bakr, and its first-memorizer claim is questionable. No replacement answer is inferred.' },
          { prompt: 'حضرت عثمانؓ نے مسلمانوں کو کس کی قرأت پر اکٹھا کیا؟', answer: 'حضرت عثمانؓ نے مسلمانوں کو قرآن پاک کی ایک قرأت پر اکٹھا کیا؟', detail: 'The printed answer ends with a question mark and does not name a reciter.' },
          { prompt: 'قرآن پاک پر اعراب کس نے لگوائے؟', answer: 'قرآن پاک پر اعراب حجاج بن یوسف (اموی خلیفہ) نے لگوائے۔', detail: 'The source calls Hajjaj bin Yusuf an Umayyad caliph. This title is a factual concern and is retained only as source wording.' },
          { prompt: 'قرآن پاک کا سب سے پہلا ترجمہ کون سی زبان میں ہوا', answer: 'قرآن پاک کا سب سے پہلا ترجمہ لاطینی زبان میں ہوا۔', detail: 'The claim that the first Quran translation was Latin is questionable. No alternative language has been substituted without verification.' },
          { prompt: 'قرآن پاک کی اہم خصوصیات۔ یہ نبی کریم ﷺ پر نازل کیا گیا', answer: '(۱) اللہ رب العزت کی آخری کتاب ہے۔\n(۲) زندہ عربی زبان میں موجود ہے۔' },
          { prompt: 'قرآن پاک کی حفاظت کی ذمہ داری کس نے اٹھائی؟', answer: 'قرآن پاک کی حفاظت کی ذمہ داری اللہ رب العزت نے خود اٹھائی۔' },
        ],
      },
      {
        id: 'batch-a-p105-quran-facts',
        kind: 'knowledge',
        title: 'معلومات قرآن',
        language: 'ur',
        sourcePage: '105',
        items: [
          { prompt: '۱. قرآن پاک کا مطلب بار بار پڑھا جانے والا' },
          { prompt: '۲. آیت کے لفظی معنی نشانی کے ہیں۔' },
          { prompt: '۳. قرآن کے کل 55... نام ہیں۔', detail: 'The number begins 55 and appears to have a final 0, giving an apparent reading of 550, but the possible final digit is blurred. It is not inferred in the transcription. Page 107 clearly prints 55.' },
          { prompt: '۴. قرآن پاک 22 سال 5 ماہ اور 14 دن میں نازل ہوا۔', detail: 'The source duration is retained without replacing it with a conventional rounded figure.' },
          { prompt: '۵. وحی کا آغاز 18 رمضان المبارک، بمطابق 11 اگست 610ء کو ہوا۔', detail: 'The exact calendar conversion and chronology are printed source claims requiring verification.' },
          { prompt: '۶. قرآن پاک کے کل پارے تیس، کل منزلیں سات، کل سورتیں 114، کل آیات 6666، کل رکوع 558، کل سجدہ تلاوت 14۔ کل حروف ۳...۷۶۰۔', detail: 'The letter-count numeral appears ۳۳۳۷۶۰, but the middle digits are blurred. Only the certain partial reading ۳...۷۶۰ is included in the transcription. Page 106 clearly prints 323760. The verse count 6666 and other totals have not been independently verified.' },
          { prompt: '۷. مکی سورتیں: 86 (13) سال کی دور میں نازل ہوئیں۔' },
          { prompt: '۸. باب القرآن سورۃ فاتحہ کو کہتے ہیں۔' },
          { prompt: '۹. روح القرآن اور قلب القرآن سورۃ یٰسین کو کہتے ہیں جو کہ ہجرت مدینہ کے وقت نازل ہوئی۔', detail: 'The timing claim about Surah Yasin is preserved as printed and needs verification.' },
          { prompt: '۱۰. نام کے لحاظ سے کل سورتوں کی تعداد 9 ہے۔', detail: 'The source prints 9 but does not explain the category نام کے لحاظ سے. The meaning and factual claim are unclear.' },
          { prompt: '۱۱. قرآن کی سب سے لمبی سورۃ بقرہ ہے۔' },
          { prompt: '۱۲. قرآن کی سب سے چھوٹی سورۃ کوثر ہے۔' },
          { prompt: '۱۳. قرآن پاک کی سب سے بڑی آیت سورۃ بقرہ میں 282 ہے۔' },
          { prompt: '۱۴. معوذتین قرآن کی آخری دو سورتوں کو کہتے ہیں۔' },
          { prompt: '۱۵. سورۃ توبہ سے پہلے بسم اللہ نہیں پڑھتے۔' },
          { prompt: '۱۶. شان نزول کے لحاظ سے قرآن پاک کی سب سے پہلی سورۃ علق ہے۔' },
          { prompt: '۱۷. قرآن پاک کی سورۃ توبہ میں زکوۃ کے مصارف بیان ہوئے ہیں۔' },
          { prompt: '۱۸. سورۃ البقرہ کا نام گائے کے ذکر کی وجہ سے رکھا گیا۔' },
          { prompt: '۱۹. کل چھ سورتیں پیغمبروں کے نام سے ہیں۔' },
          { prompt: '۲۰. معراج کا واقعہ سورۃ بنی اسرائیل پندرھویں پارے میں آیا ہے۔' },
        ],
      },
    ],
    issues: [
      'Page 104, women praised in Quran answer: first name appears حضرت عائشہ. The identification requires verification.',
      'Page 104, compilation-advice question: its printed answer discusses Uthman as پہلے حافظ قرآن and جامع القرآن instead of naming an adviser. The mismatch and historical claim are not corrected by inference.',
      'Page 104, Uthman recitation answer: the source does not identify a specific reciter and ends the answer with a question mark.',
      'Page 104, diacritics answer: printed title اموی خلیفہ for Hajjaj bin Yusuf is questionable.',
      'Page 104, first translation answer: printed لاطینی زبان is a factual concern requiring verification.',
      'Page 105, numbered item ۳: the blurred name-count numeral appears 550, while page 107 prints 55. The apparent final 0 is not certain. Partial text retained: قرآن کے کل 55... نام ہیں۔',
      'Page 105, numbered item ۶, final line: the letter count appears ۳۳۳۷۶۰, but the middle digits are blurred. The fully certain partial reading is ۳...۷۶۰. Page 106 prints 323760.',
      'Page 105, items ۴, ۵, ۶ and ۹: revelation duration and date, Quran totals including 6666 verses, and the Surah Yasin timing are transcribed source claims requiring verification.',
      'Page 105, item ۱۰: printed statement نام کے لحاظ سے کل سورتوں کی تعداد 9 ہے is unclear in meaning and should not be treated as a verified total.',
    ],
  },
  {
    fileName: 'IMG20260919120249.jpg',
    sections: [
      {
        id: 'batch-a-p106-quran-questions',
        kind: 'knowledge',
        title: 'قرآن مجید کے اعداد اور سورتوں کے القاب',
        language: 'ur',
        sourcePage: '106',
        items: [
          { prompt: 'قرآن مجید کے کل رکوع', answer: 'قرآن مجید کے کل (558) رکوع ہیں۔' },
          { prompt: 'قرآن مجید کے کل حروف', answer: 'قرآن مجید کے کل حروف (323760) ہیں۔', detail: 'The letter total is preserved as the source figure, without adopting a particular orthographic counting convention.' },
          { prompt: 'سجدہ تلاوت', answer: 'قرآن مجید میں سجدہ تلاوت 14 ہیں۔' },
          { prompt: 'قرآن مجید کی مکی سورتیں کتنی ہیں؟', answer: 'قرآن مجید کی مکی سورتیں 87 ہیں۔', detail: 'This page prints 87, whereas page 105 item ۷ prints 86. Both source counts are retained.' },
          { prompt: 'قرآن مجید کی مدنی سورتیں کتنی ہیں؟', answer: 'قرآن مجید کی مدنی سورتیں 27 ہیں۔' },
          { prompt: 'سورۃ فاتحہ کو کیا کہا جاتا ہے', answer: 'سورۃ فاتحہ کو باب القرآن کہا جاتا ہے۔' },
          { prompt: 'روح القرآن اور قلب القرآن کس سورۃ کو کہتے ہیں', answer: 'روح القرآن اور قلب القرآن سورۃ یٰسین کو کہتے ہیں۔' },
          { prompt: 'عروس القرآن کس سورۃ کو کہتے ہیں؟', answer: 'عروس القرآن سورۃ الرحمن کو کہا جاتا ہے۔' },
          { prompt: 'قرآن پاک کی سب سے لمبی سورۃ کون سی ہے؟', answer: 'قرآن پاک کی سب سے لمبی سورۃ البقرہ ہے۔' },
          { prompt: 'قرآن پاک کی سب سے چھوٹی سورۃ کون سی ہے؟', answer: 'قرآن پاک کی سب سے چھوٹی سورۃ کوثر ہے۔ (3 آیات ہیں)' },
          { prompt: 'قرآن پاک کی سب سے بڑی آیت کون سی ہے؟', answer: 'قرآن پاک کی سب سے بڑی آیت آیت الکرسی (تیسرے پارے) میں ہے۔', detail: 'The printed answer names Ayat al-Kursi. This conflicts with page 105 item ۱۳, which identifies Al-Baqarah 282. The source error is preserved rather than silently corrected.' },
        ],
      },
      {
        id: 'batch-a-p107-quran-definitions-counts',
        kind: 'knowledge',
        title: 'قرآن پاک: معانی، نزول اور تعداد',
        language: 'ur',
        sourcePage: '107',
        items: [
          { prompt: 'نبی کریم ﷺ کا سب سے بڑا معجزہ کیا ہے؟', answer: 'نبی کریم ﷺ کا سب سے بڑا معجزہ قرآن پاک ہے۔' },
          { prompt: 'قرآن کے کیا معنی ہیں', answer: 'قرآن پاک کے معنی ہیں بار بار پڑھی جانے والی کتاب۔' },
          { prompt: 'آیت کے کیا معنی ہیں؟', answer: 'آیت کے معنی نشانی کے ہیں۔' },
          { prompt: 'سورۃ کے لفظی معنی کیا ہیں؟', answer: 'سورۃ کے لفظی معنی فصیل کے ہیں۔' },
          { prompt: 'قرآن پاک کے کتنے نام ہیں؟', answer: 'قرآن پاک کے 55 نام ہیں۔' },
          { prompt: 'قرآن پاک کی مدت نزول', answer: '22 سال، 5 ماہ اور 14 دن', detail: 'The source duration is retained without replacing it with a conventional rounded figure.' },
          { prompt: 'وحی کا آغاز', answer: '18 رمضان المبارک 610ء', detail: 'This is the printed date and is not independently verified.' },
          { prompt: 'قرآن مجید کے پارے', answer: 'قرآن مبارک کے پارے 30 ہیں۔' },
          { prompt: 'قرآن مجید کی منزلیں', answer: 'قرآن پاک کی منزلیں (۷) ہیں۔' },
          { prompt: 'قرآن مجید کی کل سورتیں', answer: 'قرآن مجید کی کل سورتیں (۱۱۴) ہیں۔' },
          { prompt: 'قرآن مجید کی کل آیات', answer: 'قرآن مجید کی کل آیات (6236) ہیں۔', detail: 'This page prints 6236, whereas page 105 item ۶ prints 6666. The discrepancy is retained with source provenance.' },
        ],
      },
    ],
    issues: [
      'Page 106, Meccan surah answer: source says 87, conflicting with 86 on page 105 item ۷.',
      'Page 106, final answer: source names آیت الکرسی as the largest verse. This is a factual concern and conflicts with Al-Baqarah 282 in page 105 item ۱۳.',
      'Page 107, names count: source prints 55, while the blurred numeral in page 105 item ۳ appears 550 and needs a sharper image.',
      'Page 107, verse count: source says 6236, while page 105 item ۶ says 6666. Both printed figures are retained.',
      'The hand near the lower gutter covers part of the answer label on page 106, but the study wording of the final answer remains visible.',
    ],
  },
] satisfies ExtractedPhoto[];
