import type { ExtractedPhoto } from './extractedPhotos';

export const extractedBatchB = [
  {
    fileName: 'IMG20260919120253.jpg',
    sections: [
      {
        id: 'batch-b-120253-p108-prophets',
        kind: 'knowledge',
        title: 'انبیاء کرام کے متعلق سوالات',
        language: 'ur',
        sourcePage: '108',
        items: [
          {
            prompt: 'سب سے پہلے اور سب سے زیادہ قرآن پاک میں کس نبی کا ذکر آیا؟',
            answer: 'حضرت موسیٰ بن عمران کا قرآن پاک میں سب سے زیادہ ذکر آیا۔',
            detail: 'سوال میں «سب سے پہلے» بھی چھپا ہے، لیکن جواب صرف سب سے زیادہ ذکر کے بارے میں ہے۔',
          },
          {
            prompt: 'حضرت ابراہیم علیہ السلام کا ذکر قرآن پاک میں کتنی دفعہ آیا ہے؟',
            answer: 'حضرت ابراہیم علیہ السلام کا ذکر قرآن پاک میں 68 مقامات پر آیا ہے۔',
            detail: 'یہ تعداد ماخذ کے مطابق نقل کی گئی ہے؛ یہاں اس کی آزادانہ تصدیق نہیں کی گئی۔',
          },
          {
            prompt: 'حضرت عیسیٰ بن مریم کے معجزات',
            answer: '(۱) اللہ تعالیٰ کے حکم سے مردوں کو زندہ کرنا\n(۲) بچپن میں کلام کرنا\n(۳) بغیر باپ کے پیدا ہونا',
          },
          {
            prompt: 'حضرت موسیٰ بن عمران کے معجزات',
            answer: '(۱) دائیں ہاتھ کا سورج کی طرح روشن ہونا\n(۲) کوہ طور پر اللہ تعالیٰ سے کلام کرنا\n(۳) لاٹھی کا سانپ بن جانا\n(۳) 12 چشمے لاٹھی پتھر پر مار کر نکالنا',
            detail: 'آخری دو معجزات کے ساتھ ماخذ میں (۳) دہرایا گیا ہے؛ مطبوعہ ترتیب برقرار ہے۔',
          },
          {
            prompt: 'حضرت آدم علیہ السلام کو کیا کہا جاتا ہے؟',
            answer: 'حضرت آدم علیہ السلام کو صفی اللہ کہا جاتا ہے۔',
          },
          {
            prompt: 'حضرت نوح علیہ السلام کو کیا کہا جاتا ہے؟',
            answer: 'حضرت نوح علیہ السلام کو آدم ثانی کہا جاتا ہے۔',
          },
          {
            prompt: 'حضرت ابراہیم علیہ السلام کو کیا کہا جاتا ہے؟',
            answer: 'حضرت ابراہیم علیہ السلام کو خلیل اللہ کہا جاتا ہے۔',
          },
          {
            prompt: 'حضرت اسماعیل علیہ السلام کو کیا کہا جاتا ہے؟',
            answer: 'حضرت اسماعیل علیہ السلام کو ذبیح اللہ کہا جاتا ہے۔',
          },
          {
            prompt: 'حضرت موسیٰ علیہ السلام کو کیا کہا جاتا ہے؟',
            answer: 'حضرت موسیٰ علیہ السلام کو کلیم اللہ کہا جاتا ہے۔',
          },
          {
            prompt: 'حضرت محمد ﷺ کو کیا کہا جاتا ہے؟',
            answer: 'حضرت محمد ﷺ کو محمد الرسول اللہ ﷺ کہا جاتا ہے۔',
          },
        ],
      },
      {
        id: 'batch-b-120253-p109-seerah',
        kind: 'knowledge',
        title: 'سیرت اور اسلامی معلومات',
        language: 'ur',
        sourcePage: '109',
        items: [
          {
            prompt: 'ہجرت حبشہ دوم کب ہوئی؟',
            answer: 'دوم ہجرت حبشہ 7 نبوی ﷺ کو ہوئی۔',
            detail: '7 نبوی ماخذ میں چھپا ہوا جواب ہے۔ اس تاریخی تاریخ کی تصدیق ضروری ہے؛ اسے خاموشی سے تبدیل نہیں کیا گیا۔',
          },
          {
            prompt: 'مقاطعہ قریش (شعب ابی طالب) کا واقعہ کب پیش آیا؟',
            answer: '7 نبوی سے 10 نبوی ﷺ کو پیش آیا۔',
          },
          {
            prompt: 'معراج کا واقعہ کب پیش آیا؟',
            answer: 'معراج کا واقعہ 12 نبوی ﷺ (27 رجب) کو پیش آیا۔',
            detail: 'یہ ماخذ کی درج کردہ تاریخ ہے؛ واقعۂ معراج کی متعین تاریخ کے بارے میں اختلاف پایا جاتا ہے۔',
          },
          {
            prompt: 'عام الحزن کسے کہتے ہیں؟',
            answer: '10 نبوی کے سال کو کہتے ہیں۔',
          },
          {
            prompt: 'نماز کب فرض ہوئی؟',
            answer: 'نماز 12 نبوی ﷺ کو فرض ہوئی۔',
            detail: 'جواب میں ماخذ کی تاریخ برقرار رکھی گئی ہے؛ یہ اسی صفحے کی معراج کی تاریخ سے متعلق ہے۔',
          },
          {
            prompt: 'آپ ﷺ کی والدہ ماجدہ کا نام',
            answer: 'آپ ﷺ کی والدہ ماجدہ کا نام حضرت آمنہ بنت وہب تھا۔',
          },
          {
            prompt: 'آپ ﷺ کے والد ماجد کا نام',
            answer: 'آپ ﷺ کے والد ماجد کا نام حضرت عبداللہ بن عبدالمطلب تھا۔',
          },
          {
            prompt: 'آپ ﷺ کے چچاؤں کے نام',
            answer: '(۱) حضرت عباس\n(۲) حضرت ابوطالب\n(۳) حضرت امیر حمزہ (سید الشہداء)\n(۳) ابولہب',
            detail: 'ابولہب کے ساتھ ماخذ میں بھی (۳) چھپا ہے؛ اسے (۴) میں تبدیل نہیں کیا گیا۔',
          },
          {
            prompt: 'آنحضور ﷺ کی حافظ قرآن ازواج مطہرات',
            answer: '(۱) حضرت عائشہ\n(۲) حضرت حفصہ',
          },
          {
            prompt: 'انبیاء کے نام سے شروع ہونے والی سورتیں کتنی ہیں؟',
            answer: 'انبیاء کے نام سے شروع ہونے والی سورتیں (۶) ہیں۔',
          },
        ],
      },
    ],
    issues: [
      'صفحہ 108، پہلا سوال: «سب سے پہلے» بھی پوچھا گیا ہے، لیکن مطبوعہ جواب صرف سب سے زیادہ ذکر ہونے والے نبی کا نام بتاتا ہے۔',
      'صفحہ 108، حضرت موسیٰ کے معجزات، اور صفحہ 109، چچاؤں کے نام: ہر فہرست کی آخری مد کے ساتھ بھی (۳) چھپا ہے۔ ماخذ کے دہرائے ہوئے اعداد برقرار رکھے گئے ہیں۔',
      'صفحہ 108، حضرت ابراہیم علیہ السلام کے ذکر کی تعداد 68 اور صفحہ 109، ہجرت حبشہ دوم کی تاریخ 7 نبوی بعینہٖ ماخذ سے نقل ہیں؛ ان کی تصدیق درکار ہے۔',
      'صفحہ 109، معراج اور فرضیت نماز کے جوابات میں 12 نبوی، اور معراج کے لیے 27 رجب درج ہے۔ متعین تاریخ کو متفق علیہ حقیقت نہ سمجھا جائے۔',
    ],
  },
  {
    fileName: 'IMG20260919120259.jpg',
    sections: [
      {
        id: 'batch-b-120259-p110-family-seerah',
        kind: 'knowledge',
        title: 'نبی کریم ﷺ کے بیٹے اور بیٹیاں، ولادت، نکاح اور ہجرت',
        language: 'ur',
        sourcePage: '110',
        items: [
          {
            prompt: 'نبی کریم ﷺ کے بیٹے',
            answer: '(۱) حضرت قاسم\n(۲) حضرت ابراہیم\n(۳) حضرت طاہر',
            detail: 'ماخذ میں بیٹوں اور بیٹیوں کے مشترکہ سوال کے تحت یہ تین نام درج ہیں۔',
          },
          {
            prompt: 'نبی کریم ﷺ کی بیٹیاں',
            answer: '(۱) حضرت زینب\n(۲) حضرت ام کلثوم\n(۳) حضرت رقیہ\n(۳) حضرت فاطمہ',
            detail: 'حضرت فاطمہ کے ساتھ بھی ماخذ میں (۳) چھپا ہے؛ اصل دہرایا ہوا عدد برقرار رکھا گیا ہے۔',
          },
          {
            prompt: 'نبی کریم ﷺ کی ولادت',
            answer: '22 اپریل 571ء بروز سوموار ولادت ہوئی۔',
            detail: 'عیسوی تاریخ بعینہٖ مطبوعہ جواب سے نقل کی گئی ہے؛ تاریخی تاریخ کی تصدیق نہیں کی گئی۔',
          },
          {
            prompt: 'آپ ﷺ کا پہلا نکاح مبارک کتنی عمر میں ہوا؟',
            answer: 'آپ ﷺ کا پہلا نکاح 25 سال کی عمر میں ہوا۔',
          },
          {
            prompt: 'پہلی ہجرت حبشہ کب ہوئی',
            answer: 'پہلی ہجرت حبشہ 5 نبوی ﷺ کو ہوئی۔',
          },
          {
            prompt: 'پہلی ہجرت حبشہ میں مردوں اور عورتوں کی تعداد کتنی تھی؟',
            answer: '11 مرد اور 4 خواتین شامل تھیں۔',
          },
        ],
      },
      {
        id: 'batch-b-120259-p110-memorization',
        kind: 'guidance',
        title: 'زبانی یاد کرنے والی چیزیں کون سی ہیں؟',
        language: 'ur',
        sourcePage: '110',
        items: [
          { prompt: '(۱) 6 (چھ) کلمے پہلے تین بمعہ ترجمہ' },
          { prompt: '(۲) آیت الکرسی' },
          { prompt: '(۳) دعائے قنوت' },
          { prompt: '(۴) ایمان مفصل، ایمان مجمل' },
          { prompt: '(۵) نماز جنازہ' },
          { prompt: '(۶) سورۃ اخلاص اور سورۃ کوثر کا اردو انگلش ترجمہ' },
          { prompt: '(۷) سن نبوی ﷺ اور سن ہجری کے واقعات' },
        ],
      },
      {
        id: 'batch-b-120259-p111-events',
        kind: 'knowledge',
        title: 'غزوات، احکام اور سیرت کی تاریخیں',
        language: 'ur',
        sourcePage: '111',
        items: [
          {
            prompt: 'غزوہ حنین کب ہوا؟',
            answer: 'غزوہ حنین (8 ہجری) کو ہوا۔',
          },
          {
            prompt: 'شراب کب حرام ہوئی؟',
            answer: 'شراب (8 ہجری) کو حرام قرار دی گئی۔',
            detail: '8 ہجری مطبوعہ جواب ہے؛ یہ تاریخ مشتبہ ہے اور اس کی تصدیق درکار ہے۔',
          },
          {
            prompt: 'غزوہ موتہ کب ہوا؟',
            answer: 'غزوہ موتہ (8 ہجری) کو ہوا۔',
          },
          {
            prompt: 'جنگ یمامہ کب ہوئی؟',
            answer: 'جنگ یمامہ (8 ہجری) کو ہوئی۔',
            detail: 'ماخذ میں 8 ہجری چھپا ہے۔ جنگ یمامہ کی یہ تاریخ مشتبہ ہے؛ اصل جواب محفوظ رکھا گیا ہے، متبادل تاریخ یہاں تصدیق نہیں کی گئی۔',
          },
          {
            prompt: 'غزوہ تبوک کب ہوا؟',
            answer: 'غزوہ تبوک (9 ہجری) کو ہوا۔',
          },
          {
            prompt: 'حج کب فرض ہوا؟',
            answer: 'حج مبارک (9 ہجری) کو فرض ہوا۔',
          },
          {
            prompt: 'خطبہ حجۃ الوداع کب دیا گیا',
            answer: 'خطبہ حجۃ الوداع (10 ہجری) کو دیا گیا۔',
          },
          {
            prompt: 'نبی کریم ﷺ نے کتنے حج ادا کیے',
            answer: 'نبی کریم ﷺ نے ایک (1) حج 10 ہجری کو ادا کیا۔',
          },
          {
            prompt: 'سود کو کب حرام قرار دیا گیا؟',
            answer: 'سود کو (10 ہجری) کو حرام قرار دیا گیا۔',
          },
          {
            prompt: 'نبی کریم ﷺ کا وصال کب ہوا؟',
            answer: '12 ربیع الاول (11 ہجری) 7 جون 632ء بروز سوموار ہوا۔',
            detail: '7 جون ماخذ کا مطبوعہ جواب ہے؛ عیسوی تاریخ کی تصدیق ضروری ہے۔',
          },
        ],
      },
      {
        id: 'batch-b-120259-p111-p110-wives',
        kind: 'knowledge',
        title: 'ازواج مطہرات یا امہات المؤمنین',
        language: 'ur',
        sourcePage: '111 (۱ تا ۶)، 110 (۷ تا ۱۱)',
        items: [
          { prompt: '(۱) حضرت خدیجہ', detail: 'صفحہ 111، فہرست کا آغاز۔' },
          { prompt: '(۲) حضرت سودہ', detail: 'صفحہ 111۔' },
          { prompt: '(۳) حضرت عائشہ', detail: 'صفحہ 111۔' },
          { prompt: '(۴) حضرت زینب', detail: 'صفحہ 111؛ یہاں مزید نسبت درج نہیں۔' },
          { prompt: '(۵) حضرت میمونہ', detail: 'صفحہ 111۔' },
          { prompt: '(۶) حضرت حفصہ', detail: 'صفحہ 111۔' },
          {
            prompt: '(۷) حضرت ماریہ قبطیہ',
            detail: 'صفحہ 110 کے اوپر۔ ماخذ انہیں ازواج کی فہرست میں شامل کرتا ہے؛ اس درجہ بندی کی الگ تصدیق درکار ہے۔',
          },
          { prompt: '(۸) حضرت ام حبیبہ', detail: 'صفحہ 110 کے اوپر۔' },
          { prompt: '(۹) حضرت جویریہ', detail: 'صفحہ 110 کے اوپر۔' },
          { prompt: '(۱۰) حضرت زینب بنت جحش', detail: 'صفحہ 110 کے اوپر۔' },
          { prompt: '(۱۱) حضرت ام سلمہ', detail: 'صفحہ 110 کے اوپر۔' },
        ],
      },
    ],
    issues: [
      'ازواج کی فہرست کے نمبر ۱ تا ۶ دائیں صفحے 111 کے آخر میں اور ۷ تا ۱۱ بائیں صفحے 110 کے شروع میں چھپے ہیں۔ اصل نمبر برقرار رکھ کر ایک ہی فہرست میں جوڑے گئے ہیں؛ صفحہ نمبروں کی یہ غیر معمولی ترتیب ماخذ میں ہے۔',
      'صفحہ 110، بیٹیوں کی فہرست میں حضرت رقیہ اور حضرت فاطمہ دونوں کے ساتھ (۳) چھپا ہے۔ ماخذ کا دہرایا ہوا عدد (۴) میں تبدیل نہیں کیا گیا۔',
      'صفحہ 111، شراب کی حرمت اور جنگ یمامہ دونوں کے لیے 8 ہجری چھپا ہے۔ یہ جوابات مشتبہ ہیں اور الگ تاریخی تصدیق کے محتاج ہیں۔',
      'صفحہ 111، وصال کے جواب میں 7 جون 632ء درج ہے؛ اسے درست فرض نہ کیا جائے۔ صفحہ 110 کی ولادت کی عیسوی تاریخ 22 اپریل 571ء بھی ماخذ کے مطابق ہے۔',
      'صفحہ 110، ازواج کی فہرست کی مد ۷ میں حضرت ماریہ قبطیہ کو شامل کیا گیا ہے۔ ماخذ کی یہ درجہ بندی تصدیق طلب ہے۔',
    ],
  },
  {
    fileName: 'IMG20260919120304.jpg',
    sections: [
      {
        id: 'batch-b-120304-p112-religion',
        kind: 'knowledge',
        title: 'مذہب سے متعلق',
        language: 'ur',
        sourcePage: '112',
        items: [
          {
            prompt: 'غزوہ بدر کب ہوا؟',
            answer: 'غزوہ بدر (17 رمضان 2 ہجری) کو ہوا۔',
          },
          {
            prompt: 'غزوہ احد کب ہوا؟',
            answer: 'غزوہ احد (7 شوال 3 ہجری) کو ہوا۔',
          },
          {
            prompt: 'قبلہ تبدیل کرنے کا حکم کب آیا؟',
            answer: '(قبلہ کا بدلنا) بیت المقدس سے بیت اللہ (2 ہجری)',
          },
          {
            prompt: 'اذان کب لازم ہوئی؟',
            answer: 'اذان (2 ہجری) کو لازم ہوئی۔',
            detail: '2 ہجری ماخذ میں درج ہے؛ یہ تاریخ تصدیق طلب ہے۔',
          },
          {
            prompt: 'زکوٰۃ کب لازم ہوئی؟',
            answer: 'زکوٰۃ (2 ہجری) کو فرض ہوئی۔',
          },
          {
            prompt: 'پردہ کا حکم کب آیا؟',
            answer: 'پردہ کا حکم (3 ہجری) کو ہوا۔',
            detail: '3 ہجری مطبوعہ جواب ہے؛ اس تاریخ کی تصدیق درکار ہے۔',
          },
          {
            prompt: 'غزوہ خندق کب ہوا؟',
            answer: 'غزوہ خندق (5 ہجری) کو ہوا۔',
          },
          {
            prompt: 'بیعت رضوان یا بیعت شجر کا واقعہ کب پیش آیا؟',
            answer: 'بیعت رضوان یا بیعت شجر (6 ہجری) کو پیش آیا۔',
          },
          {
            prompt: 'غزوہ خیبر کب ہوا؟',
            answer: 'غزوہ خیبر (7 ہجری) صلح حدیبیہ (6 ہجری) کو ہوا۔',
            detail: 'صلح حدیبیہ کی تاریخ اسی مطبوعہ جواب میں اضافی طور پر دی گئی ہے۔',
          },
          {
            prompt: 'مکہ کب فتح ہوا؟',
            answer: 'مکہ (8 ہجری) کو فتح ہوا۔',
          },
        ],
      },
      {
        id: 'batch-b-120304-p113-urdu-set-10',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر دس',
        language: 'ur',
        sourcePage: '113',
        seconds: 360,
        items: [
          { prompt: '۱۔ کبھی کبھی یوں لگتا ہے جیسے' },
          { prompt: '۲۔ جوانوں نے ایک ہی دن میں' },
          { prompt: '۳۔ میرے تمام دوست' },
          { prompt: '۴۔ اس کا منصوبہ تھا' },
          { prompt: '۵۔ مجھے اکثر یاد آتا ہے کہ' },
          { prompt: '۶۔ ملک کی خدمت کیلئے' },
          { prompt: '۷۔ اس نے صبر تو کیا لیکن' },
          { prompt: '۸۔ مجھے فکر ہے کہ' },
          { prompt: '۹۔ لوگوں کے سامنے آتے ہی اس نے' },
          { prompt: '۱۰۔ اپنی انفرادیت برقرار رکھنے کیلئے' },
          { prompt: '۱۱۔ افراتفری میں اس نے' },
          { prompt: '۱۲۔ امیروں کے ساتھ' },
          { prompt: '۱۳۔ اس کا دل گھبرا اٹھا کہ' },
          { prompt: '۱۴۔ موقع سے فائدہ اٹھاتے ہوئے' },
          { prompt: '۱۵۔ میں اس لئے خوش ہوں کہ' },
          { prompt: '۱۶۔ اس نے وعدہ تو کر لیا' },
          { prompt: '۱۷۔ اپنے جذبہ کو ثابت کرنے کیلئے' },
          { prompt: '۱۸۔ مصروفیت کی وجہ سے اس نے' },
          { prompt: '۱۹۔ مالدار بننے کیلئے وہ' },
          { prompt: '۲۰۔ منزل پانے کے لئے' },
          { prompt: '۲۱۔ سخت بیماری کی حالت میں اس نے' },
          { prompt: '۲۲۔ اس نے اپنے دوست کو ترغیب دی کہ' },
          { prompt: '۲۳۔ میں چاہتا ہوں کہ' },
          { prompt: '۲۴۔ میرے والدین مجھ سے' },
          { prompt: '۲۵۔ مہمانوں کے آنے پر' },
          { prompt: '۲۶۔ محنت کرنے کے باوجود' },
        ],
      },
    ],
    issues: [
      'صفحہ 112، اذان کے لیے 2 ہجری اور پردہ کے حکم کے لیے 3 ہجری مطبوعہ جوابات ہیں؛ تاریخی تصدیق درکار ہے۔',
    ],
  },
  {
    fileName: 'IMG20260919120310.jpg',
    sections: [
      {
        id: 'batch-b-120310-p114-urdu-set-9',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر نو',
        language: 'ur',
        sourcePage: '114',
        seconds: 360,
        items: [
          { prompt: '۱۔ اس کی امید کے خلاف' },
          { prompt: '۲۔ خواہشوں کے ہجوم میں' },
          { prompt: '۳۔ تنگدستی غالب آئی تو' },
          { prompt: '۴۔ اس نے گھبرا کر' },
          { prompt: '۵۔ میرے لئے اس نے' },
          { prompt: '۶۔ مکان بنانے کے لئے اس نے' },
          { prompt: '۷۔ ابھی وہ بچہ ہی تھا' },
          { prompt: '۸۔ ایک دن اس نے غلطی سے' },
          { prompt: '۹۔ اکھڑ مزاج ہونے کے ساتھ ساتھ' },
          { prompt: '۱۰۔ سونے سے پہلے وہ اکثر' },
          { prompt: '۱۱۔ اس کے آنے سے' },
          { prompt: '۱۲۔ میری ماں نے' },
          { prompt: '۱۳۔ جب زور نہ چلا تو' },
          { prompt: '۱۴۔ زندگی بھر وہ اس کوشش میں رہا' },
          { prompt: '۱۵۔ شادی شدہ ہونے کے باوجود' },
          { prompt: '۱۶۔ شام کے وقت' },
          { prompt: '۱۷۔ کام سے فارغ ہو کر' },
          { prompt: '۱۸۔ موسم بدلتے ہی' },
          { prompt: '۱۹۔ اندھیری رات میں اس نے' },
          { prompt: '۲۰۔ میں جلدی پہچان گیا کہ وہ' },
          { prompt: '۲۱۔ اس نے ایک ہی وار میں' },
          { prompt: '۲۲۔ اس کے حوصلہ ہارنے کی وجہ' },
          { prompt: '۲۳۔ دیر سے آنے کی وجہ سے' },
          { prompt: '۲۴۔ جب کام چل نکلا تو' },
          { prompt: '۲۵۔ باغ میں سیر کرتے ہوئے' },
          { prompt: '۲۶۔ اسے ہر وقت یہ خیال ستاتا ہے کہ' },
        ],
      },
      {
        id: 'batch-b-120310-p115-urdu-set-8',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر آٹھ',
        language: 'ur',
        sourcePage: '115',
        seconds: 360,
        items: [
          { prompt: '۱۔ دیکھنے میں تو وہ سادہ ہے لیکن' },
          { prompt: '۲۔ جب جان بچانے کیلئے لوگ بھاگے تو' },
          { prompt: '۳۔ پڑھائی کے ساتھ ساتھ وہ' },
          { prompt: '۴۔ اس کی غیرت اس وقت جاگی جب' },
          { prompt: '۵۔ پولیس آئی تو وہ' },
          { prompt: '۶۔ فاقہ کشی تک نوبت پہنچی تو' },
          { prompt: '۷۔ وہ ہے ایماندار لیکن کبھی کبھی' },
          { prompt: '۸۔ اس کی چالاکی' },
          { prompt: '۹۔ وہ دن رات' },
          { prompt: '۱۰۔ اپنے بوڑھے باپ کی خاطر' },
          { prompt: '۱۱۔ وہ اپنے آپ کو' },
          { prompt: '۱۲۔ جب وہ سکول میں تھا' },
          { prompt: '۱۳۔ چور کے خوف سے' },
          { prompt: '۱۴۔ دوستوں کے درمیان' },
          { prompt: '۱۵۔ رنگین مزاج ہونے کے باوجود' },
          { prompt: '۱۶۔ اس نے اپنی بیماری کی وجہ سے' },
          { prompt: '۱۷۔ اس کی زبان پر ہر وقت' },
          { prompt: '۱۸۔ اپنے مستقبل کے لئے' },
          { prompt: '۱۹۔ آجکل کی لڑکیاں' },
          { prompt: '۲۰۔ دکان میں بھیڑ سے فائدہ اٹھاتے ہوئے' },
          { prompt: '۲۱۔ ملک واپس آتے ہوئے' },
          { prompt: '۲۲۔ دوسروں کو نیچا دکھانے کیلئے' },
          { prompt: '۲۳۔ افسری کے زعم میں اس نے' },
          { prompt: '۲۴۔ ملازموں کے ساتھ اس کا سلوک' },
          { prompt: '۲۵۔ اس نے سختی برداشت کرلی لیکن' },
          { prompt: '۲۶۔ ذرا سی پریشانی آنے پر' },
        ],
      },
    ],
    issues: [],
  },
  {
    fileName: 'IMG20260919120315.jpg',
    sections: [
      {
        id: 'batch-b-120315-p116-urdu-set-7',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر سات',
        language: 'ur',
        sourcePage: '116',
        seconds: 360,
        items: [
          { prompt: '۱۔ باپ کی غیر موجودگی میں' },
          { prompt: '۲۔ غلطی کرنے کے بعد' },
          { prompt: '۳۔ کبھی کبھی بات بڑھانے کیلئے' },
          { prompt: '۴۔ ملکی حالات کو دیکھ کر' },
          { prompt: '۵۔ وہ میرے لئے باہر گیا لیکن' },
          { prompt: '۶۔ امیر ہونے کے باوجود اس نے' },
          { prompt: '۷۔ وہ دیکھنے میں چھوٹا ہے لیکن' },
          { prompt: '۸۔ لوگوں پر رعب ڈالنے کیلئے' },
          { prompt: '۹۔ ماں سے ڈانٹ کھا کر' },
          { prompt: '۱۰۔ رات کو اکیلے گھر' },
          { prompt: '۱۱۔ جب میں اداس ہوتا ہوں' },
          { prompt: '۱۲۔ بظاہر تو وہ ہنستا رہتا ہے' },
          { prompt: '۱۳۔ چلتے چلتے تھک جانے پر اس نے' },
          { prompt: '۱۴۔ وہ حج پر جانا چاہتا ہے' },
          { prompt: '۱۵۔ اس نے روزہ تو رکھ لیا' },
          { prompt: '۱۶۔ وہ اکثر رات کو' },
          { prompt: '۱۷۔ اندھیرے سے فائدہ اٹھاتے ہوئے' },
          { prompt: '۱۸۔ باپ کے ایسے حکم پر وہ' },
          { prompt: '۱۹۔ جب لڑکی نے اس کی طرف دیکھا تو' },
          { prompt: '۲۰۔ گھر سے تو مسجد گیا' },
          { prompt: '۲۱۔ مایوسی کی حالت میں' },
          { prompt: '۲۲۔ امتحان کی فکر' },
          { prompt: '۲۳۔ اس نے اپنے استاد' },
          { prompt: '۲۴۔ دوڑ شروع ہوتے ہی' },
          { prompt: '۲۵۔ وہ گھبراہٹ کے مارے' },
          { prompt: '۲۶۔ اپنی جلد بازی کی وجہ سے' },
        ],
      },
      {
        id: 'batch-b-120315-p117-urdu-set-6',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر چھ',
        language: 'ur',
        sourcePage: '117',
        seconds: 360,
        items: [
          { prompt: '۱۔ جب کوئی راستہ نظر نہ آئے' },
          { prompt: '۲۔ میں اپنے گھر میں' },
          { prompt: '۳۔ میرے سارے ساتھی' },
          { prompt: '۴۔ دولت ملتے ہی' },
          { prompt: '۵۔ اکثر ماں باپ' },
          { prompt: '۶۔ میرے سامنے اب' },
          { prompt: '۷۔ وقت کے ساتھ' },
          { prompt: '۸۔ اس نے لڑکی سے' },
          { prompt: '۹۔ میرے خوابوں میں' },
          { prompt: '۱۰۔ لڑتے لڑتے' },
          { prompt: '۱۱۔ نوجوانی میں اکثر' },
          { prompt: '۱۲۔ سارے مسائل کا حل' },
          { prompt: '۱۳۔ اس نے آنکھ بچا کر' },
          { prompt: '۱۴۔ میرے دل میں' },
          { prompt: '۱۵۔ اس نے دن دھاڑے' },
          { prompt: '۱۶۔ سٹیشن پر جاتے ہوئے' },
          { prompt: '۱۷۔ اگر کام نہ ملا' },
          { prompt: '۱۸۔ اس دور میں مذہب' },
          {
            prompt: '۱۹۔ میرے وجہ سے',
            detail: 'ماخذ میں «میرے وجہ سے» پڑھا جاتا ہے؛ عبارت کو نحوی طور پر تبدیل نہیں کیا گیا۔',
          },
          { prompt: '۲۰۔ شرافت کے لبادے میں' },
          { prompt: '۲۱۔ بازار میں جاتے ہوئے' },
          { prompt: '۲۲۔ شرط جیتنے کیلئے' },
          { prompt: '۲۳۔ مصروفیت کے باعث' },
          { prompt: '۲۴۔ دل اور دماغ کی جنگ میں' },
          { prompt: '۲۵۔ لڑکیوں کی محفل میں' },
          { prompt: '۲۶۔ پیار کرنے کیلئے' },
        ],
      },
    ],
    issues: [
      'صفحہ 117، سیٹ نمبر چھ، مد ۱۹ میں مطبوعہ ترکیب «میرے وجہ سے» برقرار رکھی گئی ہے۔',
    ],
  },
  {
    fileName: 'IMG20260919120322.jpg',
    sections: [
      {
        id: 'batch-b-120322-p118-urdu-set-5',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر پانچ',
        language: 'ur',
        sourcePage: '118',
        seconds: 360,
        items: [
          { prompt: '۱۔ اس نے اپنی زندگی' },
          { prompt: '۲۔ بچپن کی حالت میں' },
          { prompt: '۳۔ شادی کروانے کے لئے' },
          { prompt: '۴۔ عورتوں کے ہجوم میں' },
          { prompt: '۵۔ ڈر کے مارے' },
          { prompt: '۶۔ اپنے جرم کا خیال آتے ہی' },
          { prompt: '۷۔ کام کرتے وقت' },
          { prompt: '۸۔ لڑکوں کے ساتھ' },
          { prompt: '۹۔ قربانی کی خاطر' },
          { prompt: '۱۰۔ میری ماں نے' },
          { prompt: '۱۱۔ بچپن میں اس نے' },
          { prompt: '۱۲۔ اپنی بات منوانے کے لئے' },
          { prompt: '۱۳۔ جونہی بارش شروع ہوئی' },
          { prompt: '۱۴۔ رات کی تاریکی میں' },
          { prompt: '۱۵۔ زندگی بھر اس نے' },
          { prompt: '۱۶۔ میرے گھر والے' },
          { prompt: '۱۷۔ اس کا جواب سن کر' },
          { prompt: '۱۸۔ ناکامی کے بعد' },
          { prompt: '۱۹۔ دشمن کو دیکھ کر' },
          { prompt: '۲۰۔ اپنے دوست کے ساتھ' },
          { prompt: '۲۱۔ افسر بننے کے لئے' },
          {
            prompt: '۲۲۔ وہ [غیر واضح] مارا گیا لیکن',
            detail: '«وہ» کے بعد اور «مارا» سے پہلے کا لفظ واضح نہیں۔',
          },
          { prompt: '۲۳۔ تنہائی میں' },
          { prompt: '۲۴۔ غصے کے مارے' },
          { prompt: '۲۵۔ ایسے حالات میں' },
          { prompt: '۲۶۔ مجھے موقع مل گیا' },
        ],
      },
      {
        id: 'batch-b-120322-p119-urdu-set-4',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر چار',
        language: 'ur',
        sourcePage: '119',
        seconds: 360,
        items: [
          { prompt: '۱۔ ان دنوں میں' },
          { prompt: '۲۔ میرے لئے' },
          { prompt: '۳۔ شام کے وقت' },
          { prompt: '۴۔ بات کرتے ہوئے' },
          { prompt: '۵۔ اس نے کہا' },
          { prompt: '۶۔ میرے خوابوں میں' },
          { prompt: '۷۔ پیسے کے لالچ میں' },
          { prompt: '۸۔ گھبرا کر وہ' },
          { prompt: '۹۔ الجھن کی وجہ سے' },
          { prompt: '۱۰۔ میری بہن' },
          { prompt: '۱۱۔ گاڑی کی آواز سنتے ہی' },
          { prompt: '۱۲۔ پریشانی سے تنگ آ کر' },
          { prompt: '۱۳۔ تھکن کی وجہ سے' },
          { prompt: '۱۴۔ خوف کے مارے' },
          { prompt: '۱۵۔ احسان کے مارے' },
          { prompt: '۱۶۔ دن ڈھلتے ہی' },
          { prompt: '۱۷۔ وقت گزارنے کے لئے' },
          {
            prompt: '۱۸۔ وفادار جو [غیر واضح] ہے',
            detail: '«جو» اور «ہے» کے درمیان کا لفظ واضح نہیں۔',
          },
          { prompt: '۱۹۔ میں لڑائی کی وجہ سے' },
          { prompt: '۲۰۔ جب میں سکول میں تھا' },
          { prompt: '۲۱۔ میں جوان ہو کر' },
          { prompt: '۲۲۔ بازار میں لوگ' },
          { prompt: '۲۳۔ بیماری کی حالت میں' },
          { prompt: '۲۴۔ اس کا جی تو چاہتا ہے' },
          { prompt: '۲۵۔ اپنے شوق پورے کرنے کے لئے' },
          { prompt: '۲۶۔ خوبصورت لڑکیاں' },
        ],
      },
    ],
    issues: [
      'تصویر 90 درجے گھومی ہوئی ہے۔ متن صفحہ 118 اور صفحہ 119 کی مطبوعہ سطر اور نمبر کی ترتیب میں نقل کیا گیا ہے۔',
      'صفحہ 118، سیٹ نمبر پانچ، مد ۲۲: «وہ ... مارا گیا لیکن» میں «وہ» اور «مارا» کے درمیان کا لفظ یقینی طور پر نہیں پڑھا جا سکا۔',
      'صفحہ 119، سیٹ نمبر چار، مد ۱۸: «وفادار جو ... ہے» میں «جو» اور «ہے» کے درمیان کا لفظ غیر واضح ہے۔',
    ],
  },
  {
    fileName: 'IMG20260919120330.jpg',
    sections: [
      {
        id: 'batch-b-120330-p120-urdu-set-3',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر تین',
        language: 'ur',
        sourcePage: '120',
        seconds: 360,
        items: [
          { prompt: '۱۔ جب دشمن سامنے آیا' },
          { prompt: '۲۔ خوشی کے مارے' },
          { prompt: '۳۔ ترقی کے نام پر آجکل' },
          { prompt: '۴۔ ہمارے ہاں' },
          { prompt: '۵۔ خود کو دیکھتے ہی' },
          { prompt: '۶۔ میں سوچتا ہوں' },
          { prompt: '۷۔ لڑکے اکیلے ہوں تو' },
          { prompt: '۸۔ میں چاہتا ہوں' },
          {
            prompt: '۹۔ اگر [غیر واضح] ہو گیا تو',
            detail: '«اگر» کے بعد کا لفظ تصویر میں غیر واضح ہے۔',
          },
          { prompt: '۱۰۔ جوانی آتے ہی میں نے' },
          { prompt: '۱۱۔ لوگوں کے خیال میں' },
          { prompt: '۱۲۔ نادان بچوں کے ساتھ' },
          { prompt: '۱۳۔ اچانک شور کی' },
          { prompt: '۱۴۔ نیک نامی حاصل کرنے کیلئے' },
          { prompt: '۱۵۔ اس نے ناتا توڑ ڈالا لیکن' },
          { prompt: '۱۶۔ فارغ وقت میں وہ' },
          { prompt: '۱۷۔ جب لڑکیاں چیخیں' },
          { prompt: '۱۸۔ رشتے میں وہ' },
          { prompt: '۱۹۔ تنگی کی حالت میں' },
          { prompt: '۲۰۔ سکول سے چھٹی ہوتے ہی' },
          { prompt: '۲۱۔ بہت عرصہ سے وہ' },
          { prompt: '۲۲۔ جب اس سے برداشت نہ ہو سکا تو' },
          { prompt: '۲۳۔ اپنی بیماری کی وجہ سے' },
          { prompt: '۲۴۔ شوہر پریشان' },
          { prompt: '۲۵۔ انکار سن کر اس نے' },
          { prompt: '۲۶۔ اس کے آنسو دیکھ کر' },
        ],
      },
      {
        id: 'batch-b-120330-p121-urdu-set-2-cropped',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر دو',
        language: 'ur',
        sourcePage: 'دائیں صفحے کا نمبر تصویر میں کٹا ہوا؛ بائیں صفحے پر 120 ہے',
        seconds: 360,
        items: [],
      },
    ],
    issues: [
      'صفحہ 120، سیٹ نمبر تین، مد ۹: «اگر ... ہو گیا تو» میں «اگر» کے بعد کا لفظ غیر واضح ہے۔',
      'دائیں صفحے، سیٹ نمبر دو: سرخی اور وقت 6 منٹ پڑھے جا سکتے ہیں، لیکن سوالات کے آغاز اور ان کے اصل اعداد تصویر کے نچلے کنارے سے باہر ہیں۔ پہلی سے چھبیسویں تک نظر آنے والی سطروں کے باقی حصے بھی دھندلے ہیں؛ کسی مکمل یا قابل اعتماد جزوی جملے کی تصدیق نہیں ہوئی۔ اس لیے فرضی سوالات یا دوسرے سیٹ کا متن شامل نہیں کیا گیا۔',
      'دائیں صفحے، سیٹ نمبر دو، نچلی سطریں: ہاتھ صفحے کے کچھ حصے پر بھی آ رہا ہے۔ مکمل سوالات کے لیے اسی صفحے کی سیدھی، غیر کٹی اور صاف تصویر درکار ہے۔',
    ],
  },
  {
    fileName: 'IMG20260919120335.jpg',
    sections: [
      {
        id: 'batch-b-120335-p122-urdu-set-1',
        kind: 'sentence-completion',
        title: 'سیٹ نمبر ایک',
        language: 'ur',
        sourcePage: '122',
        seconds: 360,
        items: [
          { prompt: '۱۔ میں نے ایک دن' },
          { prompt: '۲۔ اس نے میرے سامنے' },
          { prompt: '۳۔ وہ ابھی تک' },
          { prompt: '۴۔ چاند نکلنے کے بعد' },
          { prompt: '۵۔ ایک دفعہ کا ذکر' },
          { prompt: '۶۔ ان کے درمیان ہر روز' },
          { prompt: '۷۔ اس کی تکرار سے تنگ آ کر' },
          { prompt: '۸۔ رشتہ داروں کے ساتھ' },
          { prompt: '۹۔ میرے سکول میں' },
          { prompt: '۱۰۔ اگر چاہا جائے' },
          { prompt: '۱۱۔ کالج میں داخل ہوتے ہی' },
          { prompt: '۱۲۔ صبح کے وقت' },
          { prompt: '۱۳۔ تنہائی کے لمحات' },
          { prompt: '۱۴۔ موجودہ دور میں' },
          { prompt: '۱۵۔ ایسے حالات میں تو' },
          { prompt: '۱۶۔ گھبرائے بغیر' },
          { prompt: '۱۷۔ زندگی کی دوڑ میں' },
          { prompt: '۱۸۔ کاروبار چلانے کے بہانے' },
          { prompt: '۱۹۔ راہ چلتے لوگوں پر' },
          { prompt: '۲۰۔ جب ڈر لگے تو' },
          { prompt: '۲۱۔ کام کرتے کرتے وہ' },
          { prompt: '۲۲۔ وہ اپنی ماں سے' },
          { prompt: '۲۳۔ اس نے پریشانی کی وجہ سے' },
          { prompt: '۲۴۔ جب وہ اداس ہوتا ہے' },
          { prompt: '۲۵۔ میرے بس میں ہو تو' },
        ],
      },
      {
        id: 'batch-b-120335-right-day-2-discussion',
        kind: 'discussion',
        title: '2nd Day: Group Discussion',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        seconds: 900,
        items: [{ prompt: '1. Group Discussion (15 minutes).' }],
      },
      {
        id: 'batch-b-120335-right-day-2-lecture',
        kind: 'lecture',
        title: '2nd Day: Lecture',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        seconds: 120,
        items: [{ prompt: '2. Lecture (In English or in Urdu in 2 minutes).' }],
      },
      {
        id: 'batch-b-120335-right-day-2-planning',
        kind: 'planning',
        title: '2nd Day: Group Planing',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        seconds: 900,
        items: [{ prompt: '3. Group Planing (15 minutes).' }],
      },
      {
        id: 'batch-b-120335-right-day-2-group-tasks',
        kind: 'guidance',
        title: '2nd Day: Group Tasks',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        items: [
          { prompt: '4. Progressive group Task (40 minutes).' },
          { prompt: '5. Half Group Task (8 minutes).' },
        ],
      },
      {
        id: 'batch-b-120335-right-day-2-interview',
        kind: 'guidance',
        title: '2nd Day: Deputy President Interview',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        seconds: 900,
        items: [
          {
            prompt: '6. Interview (Deputy President, 15 minutes time approximately).',
            detail: 'The source specifies an approximate duration, not an exact fixed limit.',
          },
        ],
      },
      {
        id: 'batch-b-120335-right-day-3',
        kind: 'guidance',
        title: '3rd Day',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        items: [
          { prompt: '1. Command Task (8 minutes).' },
          { prompt: '2. Obstacles (Total 9, 2 minutes).' },
          { prompt: '3. Final group Task (20 minutes, in English).' },
          { prompt: '4. Mutual Assessment form (2 minutes).' },
        ],
      },
      {
        id: 'batch-b-120335-right-day-4',
        kind: 'guidance',
        title: '4th Day',
        language: 'en',
        sourcePage: 'Right page opposite 122; printed page number obscured by the hand',
        items: [
          { prompt: '1. Re-Obstacles.' },
          { prompt: '2. Re-Interview.' },
          { prompt: '3. Re. Command Task.' },
        ],
      },
    ],
    issues: [
      'صفحہ 122، سیٹ نمبر ایک میں ۱ تا ۲۵ سوالات نظر آتے ہیں۔ مد ۲۵ کے بعد صفحے کی آخری لکیر ہے؛ فرضی مد ۲۶ شامل نہیں کی گئی۔',
      'The printed page number of the right-hand schedule page is obscured by the hand. Its position opposite page 122 is recorded without inventing a visible page number.',
      'The 2nd Day schedule is split into classified sections, but its original item numbers 1 through 6 are retained. The Deputy President interview duration is explicitly approximate.',
    ],
  },
  {
    fileName: 'IMG20260919120345.jpg',
    sections: [
      {
        id: 'batch-b-120345-reporting-administration',
        kind: 'guidance',
        title: 'ISSB TEST SCHEDULE: REPORTING DAY',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        items: [
          { prompt: '1. Collection of Documents.' },
          { prompt: '2. Allotment of Chest Numbers.' },
          { prompt: '3. Photo.' },
        ],
      },
      {
        id: 'batch-b-120345-reporting-biodata',
        kind: 'biodata',
        title: 'REPORTING DAY: Biodata form',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        items: [{ prompt: '4. Biodata form.' }],
      },
      {
        id: 'batch-b-120345-reporting-english-event',
        kind: 'guidance',
        title: 'REPORTING DAY: Event in English',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 240,
        items: [{ prompt: '5. Event, in English (4 minutes time).' }],
      },
      {
        id: 'batch-b-120345-day-1-intelligence',
        kind: 'guidance',
        title: '1st Day: 1. Intelligence test',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        items: [
          { prompt: '(a) Verbal Test (85 questions in 30 minutes).' },
          {
            prompt: '(b) Non-Verbal Test (64 Questions in 25 minu[...])',
            detail: 'The line runs outside the right edge after the beginning of the word for minutes.',
          },
          {
            prompt: '(c) Mechanical aptitude Test (64 questions in [cropped text])',
            detail: 'The time at the right end of this line is not reliably readable. No duration has been supplied.',
          },
        ],
      },
      {
        id: 'batch-b-120345-day-1-sentence-schedule',
        kind: 'sentence-completion',
        title: '1st Day: 2. Incomplete Sentences',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 360,
        items: [
          { prompt: '2 Sets in English (Each set 26 questions).' },
          { prompt: '2 Sets in Urdu (Each set 26 questions).' },
          { prompt: 'Note: The Time for each set is 6 minutes.' },
        ],
      },
      {
        id: 'batch-b-120345-day-1-wat-schedule',
        kind: 'wat',
        title: '1st Day: 3. Words Association test',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 10,
        items: [
          {
            prompt: '3. Words Association test (Total 100 words, in [cropped text]). 10 seconds for one word.',
            detail: 'The 10-second duration applies to each word, not to the whole test. Words at the right edge of the first line are blurred and cropped.',
          },
        ],
      },
      {
        id: 'batch-b-120345-day-1-picture-story-schedule',
        kind: 'story',
        title: '1st Day: 4. Picture Stories',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 240,
        items: [
          {
            prompt: '4. Picture Stories (Total 4, 4 minutes for each, in [cropped text])',
            detail: 'The duration is per story. The final words after the visible timing are outside the photograph.',
          },
        ],
      },
      {
        id: 'batch-b-120345-day-1-pointer-story-schedule',
        kind: 'story',
        title: '1st Day: 5. Pointer Story',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 240,
        items: [{ prompt: '5. Pointer Story (Total 2, 04 minutes for each).' }],
      },
      {
        id: 'batch-b-120345-day-1-self-description',
        kind: 'biodata',
        title: '1st Day: 6. Self description',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        items: [
          {
            prompt: '6. Self description (in English or in Urdu, 8 Minu[...])',
            detail: 'The source line continues beyond the legible area. The digit after the language options appears to be 8, but the remainder of the timing is not clear enough to set a duration.',
          },
        ],
      },
      {
        id: 'batch-b-120345-day-1-psychologist-interview',
        kind: 'guidance',
        title: '1st Day: 7. Interview',
        language: 'en',
        sourcePage: 'Single photographed page; page number not visible',
        seconds: 900,
        items: [
          { prompt: '7. Interview (15 minutes by Psychologist).' },
          {
            prompt: 'Note: This interview can be held [cropped text]',
            detail: 'The boxed note at the bottom continues outside the photograph; its condition or timing cannot be recovered from this image.',
          },
        ],
      },
    ],
    issues: [
      'Only one page is present in this photograph. Its printed page number is not visible; the right edge and the bottom of the page are cut off and much of the text is motion-blurred.',
      '1st Day, item 1(b), Non-Verbal Test: 64 Questions in 25 minu... is visible; the right end of the line is outside the photograph.',
      '1st Day, item 1(c), Mechanical aptitude Test: 64 questions in ... is readable, but the time at the far right is cropped or too blurred to transcribe reliably.',
      '1st Day, item 3, Words Association test: the material after Total 100 words at the right edge is not fully readable. The separate line 10 seconds for one word is readable.',
      '1st Day, item 4, Picture Stories: the text after Total 4, 4 minutes for each continues outside the photograph.',
      '1st Day, item 6, Self description: the languages English and Urdu are readable. The following digit appears to be 8, but the rest of the timing is blurred or cropped, so no seconds value is asserted.',
      'Bottom boxed note after item 7: only Note: This interview can be held is readable; the rest is cut off.',
    ],
  },
] satisfies ExtractedPhoto[];
