export const introductionOutline = [
  ['Who you are', 'Your name, hometown and current education or work.'],
  ['What shaped you', 'One useful family, school or community experience. Keep private details private.'],
  ['What you do', 'A real hobby, responsibility or achievement that you can discuss further.'],
  ['Why this service', 'Your own reasons, what you know about the role and what you still need to improve.'],
];

export const personalInterviewPrompts = [
  { group: 'Introduction', prompt: 'Introduce yourself in about one minute.' },
  { group: 'Introduction', prompt: 'What is your hometown known for, and what would you improve there?' },
  { group: 'Introduction', prompt: 'Which experience best explains the person you are today?' },
  { group: 'Family and responsibility', prompt: 'Who has influenced you most, and what have you learned from them?' },
  { group: 'Family and responsibility', prompt: 'What responsibilities do you handle at home?' },
  { group: 'Family and responsibility', prompt: 'Describe a disagreement with a family member and how you handled it.' },
  { group: 'Education', prompt: 'Explain your marks, strong subjects and any gaps in education.' },
  { group: 'Education', prompt: 'Teach me one simple idea from your favourite subject.' },
  { group: 'Education', prompt: 'Why did your performance improve or decline between two exams?' },
  { group: 'Education', prompt: 'What percentage did you score? Explain how you calculated it.' },
  { group: 'Habits and interests', prompt: 'What did you actually do in your free time last week?' },
  { group: 'Habits and interests', prompt: 'Tell me the rules and your role in a sport you play.' },
  { group: 'Habits and interests', prompt: 'Describe a book, article or news report you recently read.' },
  { group: 'Habits and interests', prompt: 'What habit are you trying to change, and what have you done about it?' },
  { group: 'Strengths and mistakes', prompt: 'Give a real example of a strength, rather than only naming a quality.' },
  { group: 'Strengths and mistakes', prompt: 'What is a weakness that has affected your work or relationships?' },
  { group: 'Strengths and mistakes', prompt: 'Tell me about a failure. What part was your responsibility?' },
  { group: 'Strengths and mistakes', prompt: 'When did you change your mind after receiving criticism?' },
  { group: 'Strengths and mistakes', prompt: 'Describe a mistake you admitted before someone else discovered it.' },
  { group: 'Teamwork', prompt: 'Describe a time you helped a team without being its leader.' },
  { group: 'Teamwork', prompt: 'How did you handle a teammate who disagreed with your plan?' },
  { group: 'Teamwork', prompt: 'When did you put a shared responsibility ahead of your own convenience?' },
  { group: 'Teamwork', prompt: 'What would your closest friend say you should improve?' },
  { group: 'Service motivation', prompt: 'Why do you want to join this particular service?' },
  { group: 'Service motivation', prompt: 'What part of service life do you expect to find difficult?' },
  { group: 'Service motivation', prompt: 'What do you understand about training and an officer’s responsibilities?' },
  { group: 'Service motivation', prompt: 'What will you do if you are not selected?' },
  { group: 'Judgment', prompt: 'What would you do if you did not understand an instruction?' },
  { group: 'Judgment', prompt: 'How would you respond if you did not know the answer to a general-knowledge question?' },
  { group: 'Judgment', prompt: 'Describe how you distinguish a news report, an opinion and an unverified social-media claim.' },
  { group: 'Judgment', prompt: 'Explain a current national problem and one practical response, including its trade-off.' },
  { group: 'Judgment', prompt: 'What have you learned about yourself while preparing for this interview?' },
];
