/* Auto-generated by scripts/build-narration.mjs — do not edit by hand */
export type NarrationEntry = {
  section: string;
  id: string;
  title: string;
  audio: string;
  script: string;
};

export const gkNarration: Record<string, { audio: string; script: string }> = {
  "indus-waters-treaty": {
    "audio": "/audio/gk/indus-waters-treaty.mp3",
    "script": "Indus Waters Treaty 1960 The Indus Waters Treaty IWT was signed in 1960 by Pakistan and India with the World Bank as broker. It divides the Indus basin, Eastern Rivers Ravi, Beas, Sutlej go mainly to India, Western Rivers Indus, Jhelum, Chenab go mainly to Pakistan, with limited Indian uses allowed domestic, non consumptive, limited agriculture, and regulated hydropower. A Permanent Indus Commission handles day to day cooperation, disputes can go to a Neutral Expert or a Court of Arbitration. Signed 19 September 1960, entered into force after ratifications, effective from 1 April 1960. Next, Eastern Rivers → India unrestricted use after a transition period that ended by 1970 or 1973. Western Rivers → Pakistan unrestricted use of waters India must let flow. Next, India may build run of river hydropower on Western Rivers under Annexure D design rules, with notice to Pakistan. Next, Dispute ladder, Permanent Indus Commission → Neutral Expert → Court of Arbitration Annexure G. Next, April 2025, India announced it was holding the treaty “in abeyance” after an attack in Indian administered Jammu & Kashmir. Pakistan rejects unilateral suspension. Next, 31 August 2026, Court of Arbitration PCA secretariat ruled unanimously that the treaty remains fully in force and India must observe its obligations. India rejects the court’s jurisdiction and keeps its abeyance stance. Next, Practical friction, Permanent Indus Commission has not met since May 2022 per Pakistani reporting, data sharing and inspections have been disrupted. Remember Six rivers, two sides, East Ravi Beas Sutlej India, West Indus Jhelum Chenab Pakistan. Treaty cannot be ended by one side alone only by a new joint treaty. Why interviewers ask this. Water security is a classic ISSB interview topic. State the allocation clearly, name the World Bank role, and separate legal findings Aug 2026 award from political positions India’s abeyance claim."
  },
  "geography-pakistan": {
    "audio": "/audio/gk/geography-pakistan.mp3",
    "script": "Geography of Pakistan Pakistan is in South Asia, with a coastline on the Arabian Sea. It shares land borders with India east, Afghanistan and Iran west, and China north east. The landscape runs from high Himalaya or Karakoram or Hindu Kush mountains in the north, through the Indus plain and deserts Thar, Cholistan, Kharan, to coastal Balochistan and Sindh. Capital, Islamabad. Largest city or economic hub, Karachi. Next, Four provinces, Punjab, Sindh, Khyber Pakhtunkhwa, Balochistan. Plus Islamabad Capital Territory and the administered territories of Azad Jammu & Kashmir and Gilgit Baltistan status is politically sensitive state facts carefully. Next, Core river system, Indus and its tributaries Jhelum, Chenab, Ravi, Beas historically, Sutlej the Indus basin feeds most irrigated agriculture. Next, Northern highlands hold K2 Godwin Austen in the Karakoram second highest peak on Earth. Next, Climate, largely arid or semi arid, monsoon rains matter for floods and crops, winters can be severe in the north. Next, Strategic depth themes interviewers like, Gwadar on the Arabian Sea, mountain passes to Afghanistan or China, and the Indus as a lifeline. Remember Sketch, Arabian Sea south, India east, Afghanistan or Iran west, China north east, Indus spine through the country. Why interviewers ask this. Interviewers expect a clean mental map before current affairs. Geography answers should stay short, correct, and free of invented statistics."
  },
  "provinces-territories": {
    "audio": "/audio/gk/provinces-territories.mp3",
    "script": "Provinces & territories Pakistan’s provincial structure is a staple ISSB question. Know the four provinces and their capitals, plus Islamabad Capital Territory. When asked about the north, distinguish carefully between provinces and administered territories. Punjab capital Lahore. Most populous province, Indus plain agriculture. Next, Sindh capital Karachi also Pakistan’s main port city. Next, Khyber Pakhtunkhwa formerly NWFP or “Sarhad” capital Peshawar. Includes former FATA agencies after the 25th Amendment merger 2018. Next, Balochistan capital Quetta. Largest by area, sparse population, Gwadar on the Makran coast. Next, Islamabad Capital Territory federal capital. Next, Former FATA agencies for recall, Bajaur, Mohmand, Khyber, Kurram, Orakzai, North Waziristan, South Waziristan. Remember Lahore, Karachi, Peshawar, Quetta + Islamabad. KP = old NWFP, FATA merged into KP 2018. Why interviewers ask this. Fast recall of province capitals is a common warm up question before deeper geopolitics."
  },
  "rivers-dams": {
    "audio": "/audio/gk/rivers-dams.mp3",
    "script": "Rivers, dams & hydropower Pakistan’s agriculture and cities depend on the Indus basin. Know the main rivers, where major dams sit, and the link to the Indus Waters Treaty. Avoid quoting outdated reservoir statistics unless you rechecked them. Main stem, Indus. Major western tributaries relevant to the treaty, Jhelum and Chenab plus Indus itself. Next, Kabul River joins the Indus near Attock. Next, Tarbela Dam Indus River, Khyber Pakhtunkhwa large earth fill dam, hydropower + irrigation storage. Next, Mangla Dam Jhelum River Azad Jammu & Kashmir or Punjab interface, storage + power. Next, Warsak Kabul River near Peshawar. Khanpur Haro River KP. Ghazi Barotha Indus run of river or diversion scheme. Next, Interview angle, storage, siltation, flood management, and treaty limits on Indian Western River projects. Remember Tarbela Indus, Mangla Jhelum, Warsak Kabul. Attock = Kabul meets Indus. Why interviewers ask this. Links geography, water security, and the IWT in one tidy answer."
  },
  "borders-neighbours": {
    "audio": "/audio/gk/borders-neighbours.mp3",
    "script": "Borders & neighbours Pakistan has four land neighbours and a southern maritime frontier on the Arabian Sea. Border answers should name the neighbour, the general direction, and one strategic note without inventing lengths or troop figures. India east or south east, includes the Line of Control LoC in Jammu & Kashmir a ceasefire line, not an agreed international boundary. Next, Afghanistan west or north west, Durand Line frontier, key crossings include Torkham via Khyber and Chaman. Next, Iran west or south west, Balochistan frontier, trade and security links via Taftan and coastal routes. Next, China north east, high Karakoram frontier, Khunjerab Pass links to Xinjiang Karakoram Highway. Next, Arabian Sea south, Karachi and Port Qasim Sindh, Gwadar and the Makran coast Balochistan. Remember India Afghanistan Iran China + Arabian Sea. Torkham or Chaman to Afghanistan, Khunjerab to China. Why interviewers ask this. Sets up CPEC, Afghanistan, and India Pakistan questions without sounding memorised from a pamphlet."
  },
  "khyber-pass": {
    "audio": "/audio/gk/khyber-pass.mp3",
    "script": "Khyber Pass The Khyber Pass is a mountain pass in Khyber Pakhtunkhwa on the Pakistan Afghanistan border. It connects the Peshawar Valley via Jamrud or Landi Kotal with Afghanistan toward the Jalalabad Kabul route, with the border town of Torkham as the key crossing. For centuries it was a Silk Road or invasion corridor, in the 2000s it carried a large share of NATO ground supplies into Afghanistan. Location, Khyber District, KP, through the Spin Ghar Safed Koh or White Mountains foothills. Next, Route idea, Peshawar → Jamrud → Landi Kotal → Torkham border → toward Jalalabad or Kabul. Next, Length of the main pass corridor is on the order of ~50 km or ~30 miles depending on start or end points used, summit area around Landi Kotal ~1,000 m+. Next, Strategic value, shortest practical land link from the Indus plains toward Kabul, hard to bypass. Next, Other famous Pakistani passes do not confuse, Bolan Balochistan, Quetta route internal or strategic toward Kandahar axis historically, Khojak near Chaman, Khunjerab China. Next, Modern angle, Torkham crossing, border management with Afghanistan, and the Khyber Pass Economic Corridor road upgrades Peshawar Torkham. Remember Khyber = Peshawar Torkham Afghanistan. Not Bolan. Landi Kotal is the high point bazaar town. Why interviewers ask this. If an interviewer says “Pepper Pass,” they almost certainly mean Khyber Pass. Correct gently and give location + strategic why."
  },
  "strategic-passes": {
    "audio": "/audio/gk/strategic-passes.mp3",
    "script": "Strategic mountain passes Pakistan’s mountain frontiers are pierced by a few named passes that keep appearing in ISSB papers and interviews. Learn where each one sits and which neighbour it serves. Khyber Pass KP or Afghanistan Torkham. Historic military & trade corridor to Kabul. Next, Bolan Pass Balochistan, near Quetta. Historic route toward southern Afghanistan, railway or road significance. Next, Khojak Pass near Chaman, Balochistan Afghanistan frontier. Next, Khunjerab Pass Gilgit Baltistan or Xinjiang China. Highest paved international border crossing on the Karakoram Highway. Next, Lowari Pass or Tunnel Chitral access within KP internal connectivity, not a foreign border. Remember Afghanistan, Khyber, Khojak, Bolan axis. China, Khunjerab. Always name the province or region. Why interviewers ask this. Short lists score well. Pair each pass with one neighbour and one town."
  },
  "cpec": {
    "audio": "/audio/gk/cpec.mp3",
    "script": "CPEC China Pakistan Economic Corridor CPEC is the China Pakistan Economic Corridor, a flagship of China’s Belt and Road Initiative. Phase I focused on energy plants, highways, and Gwadar linked infrastructure. Phase II “CPEC 2.0” emphasises industrialisation, Special Economic Zones SEZs, agriculture, mining, ICT, and business to business investment rather than only mega construction. Core idea, connect China’s Xinjiang via Karakoram Highway or Khunjerab through Pakistan to the Arabian Sea at Gwadar. Next, Early harvest, power generation capacity additions, motorways or highways, Gwadar port and airport related works. Next, Long Term Plan originally framed for roughly 2017 2030, Pakistan and China have discussed revising it under a CPEC 2.0 frame growth, innovation, green, livelihood, openness. Next, Priority SEZ names often cited, Rashakai, Allama Iqbal Industrial City, Dhabeji, Bostan progress varies by zone. Next, May 2026 Pakistan China joint messaging reaffirmed industrial parks, skills, supply chains, and security of Chinese personnel or projects. Next, Interview balance, note connectivity & energy gains, and also real constraints security in parts of Balochistan, debt or circular debt context, slow SEZ take up without slogan answers. Remember CPEC = China ↔ Gwadar corridor. Phase I = energy + roads, Phase II = industry or SEZs or B2B. Why interviewers ask this. Often confused with “CPAC.” Say the full name once, then CPEC. Tie it to Gwadar and China Pakistan “all weather” friendship carefully and factually."
  },
  "gwadar": {
    "audio": "/audio/gk/gwadar.mp3",
    "script": "Gwadar Port Gwadar is a port city in Balochistan on the Arabian Sea. Under CPEC it is promoted as Pakistan’s western deep water gateway, shorter overland access for western China to the Indian Ocean, and a potential logistics or free zone hub for the region. Location, Makran coast, Balochistan west of Karachi. Next, CPEC role, southern terminus of the corridor, free zones and industrial or logistics ambitions sit alongside the port. Next, New Gwadar International Airport was inaugurated in October 2024 and handed to Pakistan’s airport authority, commercialisation remains a 2026 27 focus in official planning notes. Next, Strategic debate, commercial trade hub vs wider Indian Ocean access for China for ISSB, stick to geography and stated project goals, then give a balanced personal view if asked. Next, Local development, water supply, and security are recurring practical issues mention them as challenges, not talking points. Remember Gwadar = Balochistan Arabian Sea port = CPEC’s sea end. Karachi remains the larger established port complex. Why interviewers ask this. Pairs with CPEC and naval or geostrategy questions."
  },
  "china-pakistan": {
    "audio": "/audio/gk/china-pakistan.mp3",
    "script": "China Pakistan relations Pakistan and China maintain a deep strategic partnership covering diplomacy, defence production or cooperation, and economic ties via CPEC. For interviews, separate friendship rhetoric from concrete pillars, border stability at Khunjerab, economic corridor projects, and regular high level visits. Diplomatic relations date from the early 1950s, both sides often call the relationship “all weather strategic cooperative.” Next, Economic spine, CPEC or Belt and Road projects. Next, Defence, long standing military technical cooperation aircraft, ships, joint exercises quote only facts you can source. Next, Border, Khunjerab Pass and Karakoram Highway link Gilgit Baltistan with Xinjiang. Next, 2025 26 messaging stressed CPEC 2.0 industrialisation and protection of Chinese personnel in Pakistan. Remember Three pillars, diplomacy, defence cooperation, CPEC economy. Border link = Khunjerab. Why interviewers ask this. Expect a follow up on Gwadar, debt, or Xinjiang answer calmly, stick to verified facts, and say when you do not know."
  },
  "arabian-sea": {
    "audio": "/audio/gk/arabian-sea.mp3",
    "script": "Arabian Sea & Pakistan’s coastline Pakistan’s only ocean frontage is the Arabian Sea. It matters for trade almost all seaborne commerce, naval strategy, energy imports, and CPEC’s maritime outlet at Gwadar. Main ports, Karachi Port and Port Qasim Sindh, Gwadar Balochistan. Next, Sea lines of communication connect Pakistan to the Persian Gulf energy, East Africa, and East Asia. Next, Hormuz or Gulf tensions can raise freight and insurance costs for Pakistani fuel and goods. Next, EEZ and fisheries exist as economic themes, avoid inventing square kilometre figures unless verified. Remember One sea, Arabian Sea. Three names to drop, Karachi, Qasim, Gwadar. Why interviewers ask this. Links geography to energy security and regional wars without overclaiming."
  },
  "mountains-peaks": {
    "audio": "/audio/gk/mountains-peaks.mp3",
    "script": "Mountains & peaks Northern Pakistan holds parts of three great ranges. Interviewers often ask for the highest peak in Pakistan and which range it sits in. Karakoram includes K2 Mount Godwin Austen, ~8,611 m, second highest on Earth, Baltoro region of Gilgit Baltistan. Next, Himalaya eastern northern rim, Nanga Parbat ~8,126 m is a famous Himalayan peak in Pakistan. Next, Hindu Kush northwestern highland system toward Afghanistan. Next, Khunjerab and other high passes cut through this highland belt toward China. Remember Highest in Pakistan = K2 in the Karakoram. Nanga Parbat = Himalaya. Why interviewers ask this. Clean three range answer beats a long tourist speech."
  },
  "water-security": {
    "audio": "/audio/gk/water-security.mp3",
    "script": "Water security for Pakistan Pakistan is a lower riparian state on the western Indus rivers. Food, cities, and industry depend on predictable flows, storage Tarbela, Mangla, etc., and canal irrigation. Climate variability glacier melt, monsoon extremes and upstream projects make water a strategic not only technical subject. Lower riparian vulnerability, timing of flows matters as much as annual volume. Next, Treaty framework, Indus Waters Treaty allocates rivers and limits upstream design on Western Rivers. Next, Domestic agenda, storage, lining or efficiency of canals, groundwater stress, urban supply, and flood management. Next, Do not claim India can “turn off” the Indus overnight geography and run of river dam design limit sudden total cutoff, still, data sharing and predictability matter. Next, Interview stance, defend lawful water rights, name the treaty, urge technical cooperation, avoid warmongering slogans. Remember Water = Indus basin + storage + IWT rules + climate stress. Predictability is the keyword. Why interviewers ask this. Shows mature judgment, facts first, then a calm national interest view."
  },
  "orgs-memberships": {
    "audio": "/audio/gk/orgs-memberships.mp3",
    "script": "Pakistan in international organisations Pakistan is an active member of several political and economic organisations. Know the full form, HQ if commonly asked, and one purpose line. UN United Nations New York HQ. Pakistan contributes to peacekeeping. Next, OIC Organisation of Islamic Cooperation. Next, SCO Shanghai Cooperation Organisation regional security or economy, China, Russia, Central Asia, India, Pakistan, etc.. Next, SAARC South Asian Association for Regional Cooperation often stalled politically. Next, ECO Economic Cooperation Organization Pakistan, Iran, Türkiye, Central Asian partners, etc.. Next, IMF or World Bank financial or development institutions frequently in economic news World Bank also brokered the IWT. Remember UN OIC SCO SAARC ECO. World Bank = IWT broker. Why interviewers ask this. Acronym rounds are easy marks if you rehearse aloud."
  },
  "defence-pact-context": {
    "audio": "/audio/gk/defence-pact-context.mp3",
    "script": "Saudi Türkiye Pakistan defence ties In 2025 2026 reporting, Pakistan’s defence diplomacy with Saudi Arabia and Türkiye deepened including Mecca linked defence cooperation coverage. Treat this as evolving diplomacy, not a NATO style automatic mutual defence clone, unless a specific signed text says so. Know partners, Saudi Arabia strategic economic + defence links, Türkiye defence industry and training cooperation history, Pakistan professional military and production partnerships. Next, For interview answers, cite the dated briefing on this site’s Current Affairs page rather than inventing treaty articles. Next, Separate, defence cooperation MoUs or industry deals vs a full collective defence guarantee. Next, Tie in topics, Middle East stability, Muslim world diplomacy, and Pakistan’s professional military image. Remember Point to or current affairs for the Mecca defence pact follow up. Do not invent clause text. Why interviewers ask this. Shows you track living files and know where your facts come from."
  },
  "paf-fighters": {
    "audio": "/audio/gk/paf-fighters.mp3",
    "script": "PAF fighter jets The Pakistan Air Force combat fleet mixes Chinese or Pakistani JF 17 Thunder and J 10CE jets, US origin F 16 Fighting Falcons, and ageing French Mirage III or 5 and Chinese F 7PG aircraft. Public inventories are estimates IISS or FlightGlobal or open directories the PAF does not publish a full official order of battle. Treat numbers as approximate and dated. JF 17 Thunder PAC or CAC main indigenous multirole fighter, single seat JF 17B dual seat trainer. Typical open figures, max speed ~Mach 1.6, service ceiling ~55,000 ft or ~16,800 m. Blocks 1 3 in service, Block III adds modern AESA or weapons suite. Next, F 16 Fighting Falcon long serving US multirole, PAF flies A or B MLU or ADF and C or D Block 52 variants. Single seat A or C or dual seat B or D. Max speed about Mach 2 class, crew 1 or 2 in trainer variants. Next, J 10CE Chinese single engine multirole with AESA radar, export “CE” for Pakistan. Crew 1. Public reporting ties PL 15E BVR missiles to this type in 2025 coverage. Next, Mirage III or Mirage 5 ROSE upgrades French origin strike or multirole, single seat some dual trainers. Ageing fleet, being phased toward JF 17 or J 10 replacements. Crew typically 1. Next, F 7PG Chinese interceptor derived from MiG 21 lineage, single seat. Phasing out of front line roles as newer types arrive. Next, Interview tip, name type → origin → role → crew → one performance cue. Do not invent exact squadron counts. Remember Front line, JF 17 + F 16 + J 10CE. Legacy, Mirage III or 5 + F 7PG. Crew = usually 1 trainers = 2. Why interviewers ask this. Service knowledge questions reward clean type cards, not memorised secret OOB numbers."
  },
  "paf-transport": {
    "audio": "/audio/gk/paf-transport.mp3",
    "script": "PAF transport & tanker aircraft PAF air mobility centres on the Lockheed C 130 Hercules for tactical airlift, the Ilyushin Il 78MP for strategic lift and aerial refuelling, and a small CN 235 utility fleet open sources note retirement pressure. Exact payload figures vary by variant and configuration quote roles and crew carefully. C 130 Hercules turboprop tactical transport, PAF operates B or E or H variants open count ~20+. Crew typically 4 6 pilots + loadmasters or flight engineers depending on fit. Payload on the order of ~20 tonnes class depending on variant or range do not invent exact kg without a checked source. Next, Il 78MP Midas four jet dual role tanker or transports open count, 4. Crew ~6. Can refuel fighters in flight and haul freight. Operated by No. 10 MRTT Squadron Nur Khan. Next, CN 235 twin turboprop medium utility, open lists show a handful often 4. Crew ~2 3. Smaller payload or range than C 130, reported as limited operational value or retirement candidate in Pakistani coverage. Next, Interview angle, C 130 = tactical workhorse, Il 78 = tanker + strategic lift, CN 235 = light utility. Remember C 130 airlift Il 78 tanker or transport 4 CN 235 light utility. Why interviewers ask this. Shows you understand that air power is not only fighters."
  },
  "paf-fleet-size": {
    "audio": "/audio/gk/paf-fleet-size.mp3",
    "script": "How many planes does the PAF have? There is no single official public “PAF has exactly N aircraft” number. Open source directories IISS Military Balance, FlightGlobal World Air Forces, Wikipedia aggregations give bands. For ISSB, state the source, the year, and whether you mean combat aircraft only or all fixed wing types. Combat or fighter band commonly cited from IISS Military Balance 2025 style tallies, on the order of ~400 fighters roughly JF 17 ~150 175, F 16 ~75, J 10CE ~20+, Mirage III or 5 ~80 combined, F 7PG ~50 figures move with deliveries and retirements. Next, Wider “all aircraft” counts on secondary sites sometimes exceed 1,000 when trainers, helicopters including other services, and UAVs are mixed in do not blend those without saying so. Next, Transport snapshot, C 130 ~20+, Il 78 = 4, CN 235 handful again estimates. Next, AEW&C, Saab 2000 Erieye often listed around ~9 in open sources. Next, Safe interview line, “Open sources put front line combat jets around four hundred, exact numbers are classified or not officially published.” Remember ~400 combat jets open source band cite year or source never invent a precise classified total. Why interviewers ask this. Honesty about uncertainty scores better than a fake exact number."
  },
  "pakistan-air-defence": {
    "audio": "/audio/gk/pakistan-air-defence.mp3",
    "script": "Pakistan air defence systems Pakistan fields a layered ground based air defence across Army and Air Force units, increasingly Chinese long or medium range SAMs plus older Western short range systems. Exact battery counts are not fully public learn the layers and names. Long range, HQ 9 or P Army HIMADS, ~125 km class in open reporting, PAF has disclosed HQ 9BE longer envelope in open specs, ~260 km class against aircraft. Next, Medium range, LY 80 or LY 80EV Army, HQ 16 export family, ~40 70 km class, PAF HQ 16FE extended medium or long in open reporting. Next, Short range or point defence, Spada 2000 Plus Aspide for PAF bases, Crotale variants, Army FM 90. Next, MANPADS, Anza series Pakistani, plus other man portable systems in open lists e.g. RBS 70, FN series verify before quoting exotic names. Next, Sensors or C2, long range radars, AEW&C Erieye cue fighters and SAMs inside an integrated air picture. Next, Interview stance, describe layers long → medium → short → guns or MANPADS, name 3 4 systems, avoid inventing battery numbers. Remember HQ 9 long LY 80 or HQ 16 medium Spada or Crotale or FM 90 short Anza MANPADS. Why interviewers ask this. Shows modern multi domain awareness beyond aircraft names alone."
  },
  "recent-paf-military": {
    "audio": "/audio/gk/recent-paf-military.mp3",
    "script": "Recent PAF & military activity For ISSB current affairs, separate 1 force modernisation, 2 the May 2025 India Pakistan crisis, and 3 defence diplomacy. Always say what is claimed vs independently confirmed. 6 7 May 2025, After the April 2025 Pahalgam attack, India launched Operation Sindoor strikes, Pakistan reported a major air battle and claimed multiple IAF jets downed. Open assessments discuss beyond visual range engagements and Chinese origin weapons in PAF use. India and Pakistan dispute details state both sides’ claims. Next, Modernisation thread, JF 17 Block III production, J 10CE induction, reported interest in future stealth types e.g. J 35 family in open reporting treat as programme talk until in service. Next, Defence diplomacy, deepening ties with Saudi Arabia and Türkiye appear in 2025 26 briefings on this site’s Current Affairs page. Next, Domestic security or counter terror operations continue to involve joint services quote only facts you can source. Remember May 2025 = Operation Sindoor or PAF response claims. Modernisation = JF 17 III + J 10CE. Diplomacy = Saudi or Türkiye file. Why interviewers ask this. Interviewers probe whether you confuse viral claims with verified facts."
  },
  "abhinandan-tea-incident": {
    "audio": "/audio/gk/abhinandan-tea-incident.mp3",
    "script": "Captured pilot & “the tea is fantastic” Wing Commander Abhinandan Varthaman IAF MiG 21 Bison was shot down and captured near the LoC on 27 February 2019 during the post Balakot or Swift Retort crisis. In a widely shared custody video he praised his treatment and, when asked about the tea, said “The tea is fantastic, thank you.” He was returned to India on 1 March 2019. This is NOT the May 2025 conflict that later crisis did not produce this tea quote. Date, 27 February 2019 not 6 May. Context, day after Balakot related escalation, PAF Operation Swift Retort narrated on the Pakistani side. Next, Pilot, then Wing Commander Abhinandan Varthaman, IAF, aircraft MiG 21 Bison, ejected and was captured in Pakistani territory near the LoC. Next, Viral line, “The tea is fantastic, thank you,” while holding a cup, also said Pakistani officers had looked after him well, while refusing mission details “I am not supposed to tell you this”. Next, Return, handed back at Wagah on 1 March 2019 as a goodwill or de escalation step announced by Pakistan’s leadership. Next, ISSB angle, professional treatment of PoWs, media discipline, and knowing correct dates so you do not mix 2019 with May 2025. Next, If someone says “6 May tea incident,” politely correct, May 2025 was a different clash, the tea quote is February 2019. Remember 27 Feb 2019 Abhinandan MiG 21 “tea is fantastic” returned 1 Mar 2019. Not May 2025. Why interviewers ask this. Tests factual precision under popular memory pressure."
  }
} as const;

export const martyrNarration: Record<string, { audio: string; script: string }> = {
  "muhammad-sarwar": {
    "audio": "/audio/martyrs/muhammad-sarwar.mp3",
    "script": "Captain Muhammad Sarwar. Captain Muhammad Sarwar led an attack on a fortified position at Tilpatra in Kashmir. Barbed wire stopped his company close to the defenders. Radio Pakistan records that, despite a shoulder wound, he moved forward with six men and cut the wire under fire. The opening allowed the attack to continue towards its objective. He was killed by machine gun fire on 27 July 1948. Remember Sarwar, wounded shoulder, wire cut, way forward."
  },
  "saif-ali-janjua": {
    "audio": "/audio/martyrs/saif-ali-janjua.mp3",
    "script": "Naik Saif Ali Janjua. Naik Saif Ali Janjua commanded a platoon defending a post at Bhudha Khanna in Kashmir. The Army biography records that he led his men through repeated attacks and helped repel attempts to take the post. This kept the local position defended while the fighting continued. He was seriously wounded in the battle and died on 26 October 1948. Remember Janjua, platoon leader holding a Kashmir post."
  },
  "tufail-muhammad": {
    "audio": "/audio/martyrs/tufail-muhammad.mp3",
    "script": "Major Tufail Muhammad. Major Tufail Muhammad led an assault on an Indian post at Lakshmipur in then East Pakistan. Radio Pakistan describes how he divided his men into three groups and attacked in darkness. Despite bullet wounds in his abdomen, he used grenades against machine gun positions and kept directing the attack. His men drove the opposing troops out of the post. He died from his wounds on 7 August 1958. Remember Tufail, wounded commander, grenades, post cleared."
  },
  "raja-aziz-bhatti": {
    "audio": "/audio/martyrs/raja-aziz-bhatti.mp3",
    "script": "Major Raja Aziz Bhatti. Major Raja Aziz Bhatti commanded a company defending the BRB Canal near Burki, Lahore. Radio Pakistan records that he stayed with his forward platoon for five days under tank and artillery fire, organizing the defence alongside his men. This helped hold the local canal line against repeated attacks. He was killed by an enemy shell on 12 September 1965. Remember Bhatti, forward platoon, canal defence."
  },
  "rashid-minhas": {
    "audio": "/audio/martyrs/rashid-minhas.mp3",
    "script": "Pilot Officer Rashid Minhas. Pilot Officer Rashid Minhas was preparing for a training flight when his instructor seized the aircraft and headed towards India. The official Pakistani account says Minhas fought for control, then forced the aircraft to crash before it crossed the border. This prevented the aircraft from being taken to India. He died in the crash near Sujawal on 20 August 1971. Remember Minhas, training aircraft, resisted hijacking."
  },
  "muhammad-akram": {
    "audio": "/audio/martyrs/muhammad-akram.mp3",
    "script": "Major Muhammad Akram. Major Muhammad Akram commanded a company at Hilli in then East Pakistan. The Army account says he resisted repeated attacks and led an anti tank party ahead of the defensive positions to engage enemy tanks. His resistance helped hold the local position and delay the Indian advance. He was killed fighting on 5 December 1971. Remember Akram, Hilli, company commander leading the anti tank party."
  },
  "shabbir-sharif": {
    "audio": "/audio/martyrs/shabbir-sharif.mp3",
    "script": "Major Shabbir Sharif. Major Shabbir Sharif led a company of 6 Frontier Force to capture high ground near Sulemanki Headworks. According to the official Army account, his men attacked defenders supported by tanks, took the ground and repelled counterattacks. Holding that ground strengthened their local position. He was killed by a tank shell on 6 December 1971. Remember Shabbir, take the high ground, then hold it."
  },
  "muhammad-hussain": {
    "audio": "/audio/martyrs/muhammad-hussain.mp3",
    "script": "Sawar Muhammad Hussain. Sawar Muhammad Hussain served as a driver with 20th Lancers. Near Harar Khurd, he spotted enemy tanks by a minefield and directed recoilless rifle fire onto them. ISPR credits the resulting fire with destroying tanks and strengthening the local defence. He was killed by machine gun fire while directing the guns on 10 December 1971. Remember Hussain, the driver who spotted tanks and guided fire."
  },
  "muhammad-mahfuz": {
    "audio": "/audio/martyrs/muhammad-mahfuz.mp3",
    "script": "Lance Naik Muhammad Mahfuz. Lance Naik Muhammad Mahfuz attacked a bunker at Pul Kunjry in the Wagah Attari sector. Radio Pakistan says his machine gun was destroyed, so he entered the bunker and fought an enemy soldier at close quarters. His action supported his unit's assault on the position. He was killed by bayonet wounds during the night of 17 to 18 December 1971, his anniversary is observed on 18 December. Remember Mahfuz, broken gun, bunker assault."
  },
  "karnal-sher-khan": {
    "audio": "/audio/martyrs/karnal-sher-khan.mp3",
    "script": "Captain Karnal Sher Khan. Captain Karnal Sher Khan defended mountain posts in the Gultary area during Kargil. The Army account says he led a counterattack after Indian troops took part of a post, recovering the lost portion. This supported the local defence, not an overall victory in Kargil. He was killed fighting on 5 July 1999. Remember Captain Sher Khan, counterattack on a mountain post."
  },
  "lalak-jan": {
    "audio": "/audio/martyrs/lalak-jan.mp3",
    "script": "Havildar Lalak Jan. Havildar Lalak Jan volunteered for a forward mountain position in Kargil. According to the Army account, he helped repel repeated Indian attacks and stayed at his post after severe injuries during mortar fire. Radio Pakistan says he refused evacuation and continued fighting. His continued resistance helped hold the local position. He died from his wounds on 7 July 1999. Remember Lalak Jan, wounded but still holding the post."
  }
} as const;

export const gtoNarration: Record<string, { audio: string; script: string }> = {
  "long-jump": {
    "audio": "/audio/gto/long-jump.mp3",
    "script": "Outdoor obstacle. Long jump ditch. Clear a wide ditch from a short run up. Speed and a committed take off from the near edge matter more than height. Here is the technique step by step. Know your take off foot. Start from a spot that lets that foot land on the edge naturally. Then, Run in a controlled rhythm and keep your eyes on the far bank, not the ditch. Then, Keep your speed. Put the whole take off foot down flat, just behind the edge. Then, Push hard through the take off leg and drive the free knee and both arms up. Aim for a low, forward flight of roughly 20 25°, not a high hop. Then, Keep your chest up and bring both legs forward together. Then, Reach your heels forward, land on both feet and swing your arms forward. Then, Bend your knees and let your weight roll forward, never backward. Then move on to the next obstacle."
  },
  "high-jump": {
    "audio": "/audio/gto/high-jump.mp3",
    "script": "Outdoor obstacle. High jump. Clear a bar set across two poles using the scissors technique. You take off from one foot and land on your feet, not your back. Here is the technique step by step. Use 5 to 7 springy strides so you arrive balanced, not flat out. Then, Take off from the foot farther from the bar. Lean back very slightly as you plant. Then, Kick the lead leg straight up and over the bar while both arms drive up. Then, The lead leg comes down as the trail leg lifts over. Keep your hips high and your chest upright. Then, Land on the lead foot, then both feet, with knees bent. Keep your arms out for balance."
  },
  "rope-climb": {
    "audio": "/audio/gto/rope-climb.mp3",
    "script": "Outdoor obstacle. Rope climb. Climb a vertical rope using a leg lock so your legs do most of the work, touch the top and come down under control. Here is the technique step by step. Stand with the rope in front of you, almost touching your chest. Then, Reach high and grip with one hand above the other, thumbs wrapped around the rope. Then, Pull your knees up. Let the rope run down the outside of one leg and across the top of that foot, then clamp it with the other foot J hook or S wrap. Then, Straighten your legs to push your body up. The hands only hold, while the legs lift. Then, Move one hand higher, then the other. Keep your elbows close to your body. Then, Knees up, lock, stand, reach. Keep a steady rhythm and do not rush. Then, Touch the beam or the mark clearly so the officer can see it. Then, Loosen the foot lock a little so it acts as a brake. Lower yourself hand under hand and never slide."
  },
  "double-rope": {
    "audio": "/audio/gto/double-rope.mp3",
    "script": "Outdoor obstacle. Double rope. Cross from one platform to the other on two parallel ropes, with your feet on the lower rope and your hands on the upper rope. Here is the technique step by step. Take the upper rope in both hands before stepping on. Keep your hands about shoulder width apart. Then, Put the arch of the foot on the rope, not the toes, with your knees slightly bent. Then, Slide the lead foot along the rope. Never cross your feet. Then, Slide the lead hand after the foot so three points always stay in contact. Then, Bring the trail foot and hand up, then repeat, lead foot, lead hand, close. Keep your hips close to the rope and look ahead. Then, Release only once both feet are on the platform."
  },
  "plank": {
    "audio": "/audio/gto/plank.mp3",
    "script": "Outdoor obstacle. Plank walk. Climb up, walk a raised narrow plank, step up onto the victory stand, stand upright for a moment, then walk off and climb down. Here is the technique step by step. Keep three points of contact, two hands and one foot, or two feet and one hand. Then, Fix your eyes on the far end and hold your arms out for balance. Then, Use short, even steps and place your feet in line along the plank. Then, Step up with one foot, drive through it and bring the other foot up. Then, Stand fully upright for a moment so the officer can see it, then continue. Then, Step down under control and keep the same steady pace. Then, Go down one rung at a time. Do not jump from the top."
  },
  "tyre": {
    "audio": "/audio/gto/tyre.mp3",
    "script": "Outdoor obstacle. Tyre. Pass through a tyre hanging at about waist to chest height, feet first, and land on your feet on the other side. Here is the technique step by step. Walk up to the tyre with it directly in front of you. Then, Hold the inner rim at the sides or top. Keep your arms bent and your body close. Then, Bend your knees, spring and lift both legs together in front of you. Then, Push both feet straight through the hole with your toes pointed. Then, Lean back with your weight on your hands and slide your hips through the tyre. Then, Tuck your chin and let your shoulders follow, holding the rim until your feet reach down. Then, Let go, land on both feet with bent knees and move on."
  },
  "tarzan-swing": {
    "audio": "/audio/gto/tarzan-swing.mp3",
    "script": "Outdoor obstacle. Tarzan swing. Take the rope on a raised platform, swing out with momentum and let go at the forward end so you land inside the marked target. Here is the technique step by step. Grip at head height with your hands close together, strong hand on top. Then, Bend your knees with your weight on the balls of your feet and look at the target. Then, Push forward off the platform and hold on firmly. Then, Pull your knees up so your feet clear the ground at the lowest point. Then, As you rise, shoot your legs forward toward the target. Then, Let go with both hands together just before the rope stops rising. Then, Land on both feet inside the marked area with your knees bent."
  },
  "zig-zag": {
    "audio": "/audio/gto/zig-zag.mp3",
    "script": "Outdoor obstacle. Zig zag. Move plank to plank as they rise, keeping your rhythm and balance, then come off the end under control. Here is the technique step by step. Before you start, look at the full route and decide which foot goes first. Then, Put the lead foot in the centre of the next plank and drive up through it. Then, Keep your arms out for balance and your eyes on the next plank, not your feet. Then, Stay low and centred. The planks are narrow, so shorten your step. Then, Lower yourself onto the next plank with a bent support knee. Then, From the lowest safe exit, jump forward and land on both feet with bent knees."
  },
  "boxing-ring": {
    "audio": "/audio/gto/boxing-ring.mp3",
    "script": "Outdoor obstacle. Boxing ring. Three ropes in a row, jump over the first, go under the second and jump over the third without touching them. Here is the technique step by step. Build an even rhythm. Speed is not needed here. Then, Lead with a straight leg and lift the trail knee up and sideways. Then, Bend at the knees and hips before you reach the middle rope. Keep your head down. Then, Take short steps with your back flat. Stay low until your hips are clear. Then, Stand up only once you are past the rope, then take two quick strides. Then, Use the same technique as rope one. Land running and move straight on."
  },
  "indoor-overview": {
    "audio": "/audio/gto/indoor-overview.mp3",
    "script": "Indoor Group Testing Officer practice. Here you prepare for discussion motions, short lectures, and planning problems. Pick a topic, outline your points in plain language, then practise speaking for the timed window. Debate motions are prompts for reasoned opinion, not established facts. For planning tasks, list the given facts, name what is missing, and build a conditional plan rather than inventing numbers."
  }
} as const;

export const psychNarration: Record<string, { audio: string; script: string }> = {
  "story-picture-1": {
    "audio": "/audio/psychological/story-picture-1.mp3",
    "script": "Picture story prompt. A grey evening in a park. An older man sits on a bench, leaning forward with his hands clasped and his eyes lowered. A younger man beside him has turned towards him. A bare tree and a street lamp stand nearby. Observe carefully, then write what you see happening and how it ends."
  },
  "overview": {
    "audio": "/audio/psychological/overview.mp3",
    "script": "Psychological tests practice. This dimension covers word association, picture stories, sentence completion, and related writing drills. Timed sessions use fixed deadlines and save drafts automatically. Official format facts shown inside each simulator are limited to details published on the ISSB Selection System page. App specific prompt counts, content, timing choices, and interactions are practice methodology, not a prediction of the real board."
  },
  "wat-overview": {
    "audio": "/audio/psychological/wat-overview.mp3",
    "script": "Word association test practice. You see a word and write the first natural response that comes to mind. Keep answers short, honest, and consistent with how you actually think. Do not rehearse a fake personality."
  },
  "sentence-completion-overview": {
    "audio": "/audio/psychological/sentence-completion-overview.mp3",
    "script": "Sentence completion practice. Finish each unfinished sentence with a clear, realistic ending in your own words. Focus on attitude, responsibility, and practical problem solving rather than slogans."
  },
  "story-writing-overview": {
    "audio": "/audio/psychological/story-writing-overview.mp3",
    "script": "Story writing practice. You observe a picture or opening line, then write a complete story with a beginning, middle, and end. The practice pictures are original illustrations for this site, not official ISSB stimuli. Like the real test they are deliberately ambiguous, so you decide what happened and how it ends."
  },
  "unified-observe-30-write-210": {
    "audio": "/audio/psychological/unified-observe-30-write-210.mp3",
    "script": "Picture story prompt. A grey evening in a park. An older man sits on a bench, leaning forward with his hands clasped and his eyes lowered. A younger man beside him has turned towards him. A bare tree and a street lamp stand nearby. Observe carefully, then write what you see happening and how it ends."
  },
  "story-picture-2": {
    "audio": "/audio/psychological/story-picture-2.mp3",
    "script": "Picture story prompt. A young woman in a shalwar kameez and dupatta stands at a window, one hand on the frame, looking out at the rain. A packed bag rests on the floor and an envelope lies on a small table behind her. Observe carefully, then write what you see happening and how it ends."
  },
  "story-picture-3": {
    "audio": "/audio/psychological/story-picture-3.mp3",
    "script": "Picture story prompt. A young man sits on the steps of a building, leaning over a letter held in both hands. An older man stands in the open doorway behind him, looking down at him. A bicycle leans against a pillar. Observe carefully, then write what you see happening and how it ends."
  },
  "story-picture-4": {
    "audio": "/audio/psychological/story-picture-4.mp3",
    "script": "Picture story prompt. At the edge of a dry, cracked field, an older farmer in a turban leans on a spade beside his teenage son. Heavy clouds gather over a distant village. The boy looks up at the sky, the father looks across the field. Observe carefully, then write what you see happening and how it ends."
  }
} as const;

export const narrationManifest = [
  {
    "section": "general-knowledge",
    "id": "indus-waters-treaty",
    "title": "Indus Waters Treaty (1960)",
    "audio": "/audio/gk/indus-waters-treaty.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "geography-pakistan",
    "title": "Geography of Pakistan",
    "audio": "/audio/gk/geography-pakistan.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "provinces-territories",
    "title": "Provinces & territories",
    "audio": "/audio/gk/provinces-territories.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "rivers-dams",
    "title": "Rivers, dams & hydropower",
    "audio": "/audio/gk/rivers-dams.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "borders-neighbours",
    "title": "Borders & neighbours",
    "audio": "/audio/gk/borders-neighbours.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "khyber-pass",
    "title": "Khyber Pass",
    "audio": "/audio/gk/khyber-pass.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "strategic-passes",
    "title": "Strategic mountain passes",
    "audio": "/audio/gk/strategic-passes.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "cpec",
    "title": "CPEC (China–Pakistan Economic Corridor)",
    "audio": "/audio/gk/cpec.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "gwadar",
    "title": "Gwadar Port",
    "audio": "/audio/gk/gwadar.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "china-pakistan",
    "title": "China–Pakistan relations",
    "audio": "/audio/gk/china-pakistan.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "arabian-sea",
    "title": "Arabian Sea & Pakistan’s coastline",
    "audio": "/audio/gk/arabian-sea.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "mountains-peaks",
    "title": "Mountains & peaks",
    "audio": "/audio/gk/mountains-peaks.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "water-security",
    "title": "Water security for Pakistan",
    "audio": "/audio/gk/water-security.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "orgs-memberships",
    "title": "Pakistan in international organisations",
    "audio": "/audio/gk/orgs-memberships.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "defence-pact-context",
    "title": "Saudi–Türkiye–Pakistan defence ties",
    "audio": "/audio/gk/defence-pact-context.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "paf-fighters",
    "title": "PAF fighter jets",
    "audio": "/audio/gk/paf-fighters.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "paf-transport",
    "title": "PAF transport & tanker aircraft",
    "audio": "/audio/gk/paf-transport.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "paf-fleet-size",
    "title": "How many planes does the PAF have?",
    "audio": "/audio/gk/paf-fleet-size.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "pakistan-air-defence",
    "title": "Pakistan air-defence systems",
    "audio": "/audio/gk/pakistan-air-defence.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "recent-paf-military",
    "title": "Recent PAF & military activity",
    "audio": "/audio/gk/recent-paf-military.mp3"
  },
  {
    "section": "general-knowledge",
    "id": "abhinandan-tea-incident",
    "title": "Captured pilot & “the tea is fantastic”",
    "audio": "/audio/gk/abhinandan-tea-incident.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "muhammad-sarwar",
    "title": "Captain Muhammad Sarwar",
    "audio": "/audio/martyrs/muhammad-sarwar.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "saif-ali-janjua",
    "title": "Naik Saif Ali Janjua",
    "audio": "/audio/martyrs/saif-ali-janjua.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "tufail-muhammad",
    "title": "Major Tufail Muhammad",
    "audio": "/audio/martyrs/tufail-muhammad.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "raja-aziz-bhatti",
    "title": "Major Raja Aziz Bhatti",
    "audio": "/audio/martyrs/raja-aziz-bhatti.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "rashid-minhas",
    "title": "Pilot Officer Rashid Minhas",
    "audio": "/audio/martyrs/rashid-minhas.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "muhammad-akram",
    "title": "Major Muhammad Akram",
    "audio": "/audio/martyrs/muhammad-akram.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "shabbir-sharif",
    "title": "Major Shabbir Sharif",
    "audio": "/audio/martyrs/shabbir-sharif.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "muhammad-hussain",
    "title": "Sawar Muhammad Hussain",
    "audio": "/audio/martyrs/muhammad-hussain.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "muhammad-mahfuz",
    "title": "Lance Naik Muhammad Mahfuz",
    "audio": "/audio/martyrs/muhammad-mahfuz.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "karnal-sher-khan",
    "title": "Captain Karnal Sher Khan",
    "audio": "/audio/martyrs/karnal-sher-khan.mp3"
  },
  {
    "section": "nishan-e-haider",
    "id": "lalak-jan",
    "title": "Havildar Lalak Jan",
    "audio": "/audio/martyrs/lalak-jan.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "long-jump",
    "title": "Long jump (ditch)",
    "audio": "/audio/gto/long-jump.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "high-jump",
    "title": "High jump",
    "audio": "/audio/gto/high-jump.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "rope-climb",
    "title": "Rope climb",
    "audio": "/audio/gto/rope-climb.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "double-rope",
    "title": "Double rope",
    "audio": "/audio/gto/double-rope.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "plank",
    "title": "Plank walk",
    "audio": "/audio/gto/plank.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "tyre",
    "title": "Tyre",
    "audio": "/audio/gto/tyre.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "tarzan-swing",
    "title": "Tarzan swing",
    "audio": "/audio/gto/tarzan-swing.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "zig-zag",
    "title": "Zig-zag",
    "audio": "/audio/gto/zig-zag.mp3"
  },
  {
    "section": "gto-outdoor",
    "id": "boxing-ring",
    "title": "Boxing ring",
    "audio": "/audio/gto/boxing-ring.mp3"
  },
  {
    "section": "gto-indoor",
    "id": "indoor-overview",
    "title": "Indoor practice overview",
    "audio": "/audio/gto/indoor-overview.mp3"
  },
  {
    "section": "psychological",
    "id": "overview",
    "title": "Psychological tests overview",
    "audio": "/audio/psychological/overview.mp3"
  },
  {
    "section": "psychological",
    "id": "wat-overview",
    "title": "Word association overview",
    "audio": "/audio/psychological/wat-overview.mp3"
  },
  {
    "section": "psychological",
    "id": "sentence-completion-overview",
    "title": "Sentence completion overview",
    "audio": "/audio/psychological/sentence-completion-overview.mp3"
  },
  {
    "section": "psychological",
    "id": "story-writing-overview",
    "title": "Story writing overview",
    "audio": "/audio/psychological/story-writing-overview.mp3"
  },
  {
    "section": "psychological",
    "id": "unified-observe-30-write-210",
    "title": "unified-observe-30-write-210",
    "audio": "/audio/psychological/unified-observe-30-write-210.mp3"
  },
  {
    "section": "psychological",
    "id": "story-picture-2",
    "title": "story-picture-2",
    "audio": "/audio/psychological/story-picture-2.mp3"
  },
  {
    "section": "psychological",
    "id": "story-picture-3",
    "title": "story-picture-3",
    "audio": "/audio/psychological/story-picture-3.mp3"
  },
  {
    "section": "psychological",
    "id": "story-picture-4",
    "title": "story-picture-4",
    "audio": "/audio/psychological/story-picture-4.mp3"
  }
] as const;
