export interface KnowledgePage {
  sourceImage: string;
  sourcePage: string;
  category: 'Science' | 'Service knowledge' | 'Pakistan' | 'World';
  cards: [string, string][];
  note?: string;
}

export const sourceRankEquivalency = [
  ['Second Lieutenant', 'Midshipman', 'Pilot Officer'],
  ['Lieutenant', 'Sub-Lieutenant', 'Flying Officer'],
  ['Captain', 'Lieutenant', 'Flight Lieutenant'],
  ['Major', 'Lieutenant Commander', 'Squadron Leader'],
  ['Lieutenant Colonel', 'Commander', 'Wing Commander'],
  ['Colonel', 'Captain', 'Group Captain'],
  ['Brigadier', 'Commodore', 'Air Commodore'],
  ['Major General', 'Rear Admiral', 'Air Vice Marshal'],
  ['Lieutenant General', 'Vice Admiral', 'Air Marshal'],
  ['General', 'Admiral', 'Air Chief Marshal'],
];

export const sourceAwardTable = [
  ['Captain Muhammad Sarwar', '2nd Punjab', '1948', 'Tilpatra, Kashmir'],
  ['Major Tufail Muhammad', '13th Punjab', '1958', 'Lakshmipur, then East Pakistan'],
  ['Major Raja Aziz Bhatti', '17th Punjab', '1965', 'BRB Canal, Wagah border'],
  ['Pilot Officer Rashid Minhas', '22 Squadron (as printed)', '1971', 'Jacobabad (as printed)'],
  ['Major Muhammad Akram', '4 FF', '1971', 'Hilli sector, then East Pakistan'],
  ['Major Shabbir Sharif', '6 FF', '1971', 'Sulemanki sector'],
  ['Sawar Muhammad Hussain', '20th Lancers', '1971', 'Shakargarh, Sialkot'],
  ['Lance Naik Muhammad Mahfuz', '15th Punjab', '1971', 'Wagah border'],
  ['Captain Karnal Sher Khan', '12th NLI (attachment)', '1999', 'Kargil sector'],
  ['Havildar Lalak Jan', '12th NLI', '1999', 'Kargil sector'],
];

export const knowledgePages: KnowledgePage[] = [
  {
    sourceImage: 'IMG20260919120211.jpg', sourcePage: '84', category: 'World',
    cards: [
      ['Which passes connect Pakistan and Afghanistan?', 'Khyber and Khojak are important examples. Bolan, also listed in the source, is an internal Balochistan route, not a border crossing into Afghanistan.'],
      ['Which pass connects Pakistan and China?', 'Khunjerab Pass.'], ['Where do Punjab’s five rivers join?', 'Their combined waters form the Panjnad system near Uch Sharif.'],
      ['Which states formed the G8?', 'Canada, France, Germany, Italy, Japan, Russia, the UK and the US. Russia’s participation was suspended in 2014; the group now operates as the G7.'],
      ['Which states founded the D-8?', 'Bangladesh, Egypt, Indonesia, Iran, Malaysia, Nigeria, Pakistan and Türkiye. The source gives the founding eight; verify later membership changes for current affairs.'],
      ['Which cities received Hilal-e-Istiqlal?', 'Lahore, Sialkot and Sargodha.'],
      ['Which countries belong to SAARC, and what is its purpose?', 'Afghanistan, Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan and Sri Lanka. It promotes regional cooperation in economic, social, cultural, scientific and technological fields.'],
      ['What country lies north of China?', 'Mongolia, along with Russia on other parts of China’s northern border.'],
      ['Where is the Suez Canal, and what does it connect?', 'In Egypt, connecting the Mediterranean and Red seas. It is an artificial canal, not a natural passage as the source claims.'],
      ['Where is the Panama Canal, and what does it connect?', 'In Panama in Central America. It links the Atlantic via the Caribbean Sea with the Pacific Ocean.'],
      ['Where is the Dead Sea, and is it lifeless?', 'Between Jordan and Israel / the occupied West Bank. Its high salinity prevents most fish and aquatic plants, but microorganisms can live there.'],
      ['Which Pakistani scientists are named apart from Abdul Qadeer Khan?', 'The source prints Abdus Salam, Akhlaq Ahmad, Samar Mubarakmand, Munir Ishfaq and Bashiruddin. Some names may be erroneous or incomplete; their intended identities have not been established.'],

      ['Which ocean lies between Europe and America?', 'The Atlantic Ocean.'], ['Where is Cyprus?', 'In the eastern Mediterranean. The answer continues on another photographed page.'],
    ],
    note: 'The G8 is historical, the D-8 list is the founding membership, and the source’s Suez and Dead Sea descriptions are corrected.',
  },
  {
    sourceImage: 'IMG20260919120207.jpg', sourcePage: '82, 83', category: 'Pakistan',
    cards: [
      ['What is Ghauri, and whose name does it use?', 'A surface-to-surface missile named after Muhammad of Ghor, also called Shahabuddin Ghori.'],
      ['Which winter flowers are named?', 'Narcissus and calendula (gul-e-ashrafi). The second flower’s Urdu print is not fully clear, so confirm it against a clearer copy.'],
      ['What can BP stand for?', 'Blood pressure, blueprint or boiling point, depending on context.'],
      ['Which three non-officer gallantry recipients are named?', 'Sawar Muhammad Hussain, Lance Naik Muhammad Mahfuz and Havildar Lalak Jan. The complete collection also includes Naik Saif Ali Janjua.'],
      ['Which chief justice is named in the old notes?', 'Iftikhar Muhammad Chaudhry. This is a historical answer, not the current officeholder.'],
      ['Why is the daytime sky blue?', 'Air molecules scatter shorter visible wavelengths more strongly than longer ones (Rayleigh scattering). The source’s ozone explanation is incorrect.'],
      ['How many OIC member states are there?', '57 member states.'], ['How many UN member states are there?', '193, not 207 as printed.'],
      ['What is a national budget?', 'A plan of government revenue and spending over a financial period, usually a year.'], ['What is Pakistan’s Senate?', 'The upper house of Parliament.'],
      ['Which African countries are named under the source’s southern-Africa heading?', 'Algeria, Tunisia, Djibouti and Mauritius. The heading is geographically wrong: the first two are in North Africa, Djibouti is in the Horn, and Mauritius is an Indian Ocean island state.'],
      ['What is the Line of Control?', 'The military control line dividing Indian-administered and Pakistani-administered parts of the disputed Kashmir region. It is not an agreed international border.'],
      ['What is the Durand Line?', 'The boundary associated with Pakistan and Afghanistan. The source identifies it as Pakistan’s longest land boundary.'],
      ['What does KRL stand for?', 'Khan Research Laboratories, at Kahuta. The source expands it as Kahuta Research Laboratories.'],
      ['What lies west of Bhutan?', 'The Indian state of Sikkim lies between Bhutan and Nepal. Nepal is farther west and does not share a border with Bhutan.'],
      ['Which five Balochistan places are named?', 'Quetta, Ziarat, Zhob, Chaman and Kalat.'],
      ['What additional description of Cyprus is printed?', 'An island in the Mediterranean, described as 40 miles from Türkiye and 200 miles from Greece and important for trade. Treat those distances as approximate source claims, not surveyed measurements.'],
      ['What metal does the source name for Nishan-e-Haider?', 'Gunmetal.'], ['Which award follows Nishan-e-Haider in gallantry precedence?', 'Hilal-e-Jurat.'],
      ['Where are Somalia and Djibouti?', 'In the Horn of Africa.'], ['Who wrote Pakistan’s national anthem lyrics?', 'Hafeez Jalandhari.'],
      ['What is a leap year?', 'A year with an extra day. In the Gregorian calendar, years divisible by 4 are leap years except century years unless divisible by 400. The source omits the century rule.'],
      ['Which sea borders Afghanistan?', 'None. Afghanistan is landlocked.'], ['Which sea borders Nepal?', 'None. Nepal is landlocked.'],
      ['Which Hilal-e-Jurat recipients are named in the notes?', 'Brigadier Usman (the first name is unclear in print), Sarfaraz Rafiqui and M. M. Alam are the printed examples. Do not memorise the unclear first attribution without a better source.'],
      ['How do Karachi and Lahore’s climates differ?', 'Karachi has a coastal climate with higher humidity and smaller temperature extremes. Lahore is inland, with hotter summers and colder winters.'],
      ['Which sea lies south of Pakistan?', 'The Arabian Sea.'], ['Where is Darra Adam Khel?', 'In Khyber Pakhtunkhwa, on the route between Peshawar and Kohat.'],
      ['What Army battle cry is printed?', 'Allahu Akbar.'],
      ['Which Air Force rank does the source compare with Lance Naik?', 'Junior Technician. This is a source comparison, not a universal equivalence across all trades and pay structures.'],
      ['What is Greenpeace?', 'An environmental campaigning organisation.'],
      ['What KP Assembly seat count is printed?', '99 general, 22 women’s and 3 non-Muslim seats, totalling 124. This is an old composition; consult the current assembly after the former FATA merger.'],
      ['Does the UK have no constitution?', 'The UK has a constitution, but it is not contained in one codified document. The source confuses uncodified with nonexistent.'],
      ['Where did India test nuclear weapons in 1998?', 'Pokhran.'],
      ['How long would sound from an explosion on the Sun take to reach Earth?', 'It would not travel to Earth through the vacuum of space. Sound needs a medium.'],
      ['When and where did Pakistan conduct its first nuclear tests?', '28 May 1998 in the Chagai region of Balochistan.'],
    ],
    note: 'The sky-colour explanation, UN count, leap-year rule, KRL expansion and several geography statements are corrected. Obsolete leadership and assembly data stay labelled. Two names require a clearer photo.',
  },
  {
    sourceImage: 'IMG20260919120204.jpg', sourcePage: '80, 81', category: 'World',
    cards: [
      ['Which glacier is often called the world’s highest battlefield?', 'Siachen Glacier.'], ['What is the capital of the Netherlands?', 'Amsterdam. The government sits in The Hague.'],
      ['Which ocean lies between Europe and the Americas?', 'The Atlantic Ocean.'], ['Which continent or region includes New Zealand?', 'Oceania. The source uses Australia as a broad continental label.'],
      ['Where is Somalia?', 'In the Horn of Africa.'], ['Where is Fiji?', 'In the South Pacific, in Oceania; it is not in Australia itself.'],
      ['Where is the Red Sea relative to Saudi Arabia?', 'To its west.'],
      ['What Pakistan-India border length appears in the source?', '1,610 km. Published totals differ depending on whether contested lines are counted; this old figure should not be treated as an authoritative total.'],
      ['What Pakistan-Afghanistan border length appears in the source?', '2,250 km, labelled the Durand Line. Modern references commonly give a longer figure around 2,600 km; identify the source and definition before quoting a precise total.'],
      ['Where is Kosovo?', 'In southeastern Europe in the Balkans. It declared independence from Serbia and is recognised by many but not all states. Yugoslavia, named in the old notes, no longer exists.'],
      ['Which Air Force rank corresponds broadly to Army Brigadier?', 'Air Commodore.'],
      ['Which three gallantry awards are named in descending order?', 'Nishan-e-Haider, Hilal-e-Jurat and Sitara-e-Jurat.'],
      ['Why is water useful as a laboratory reference?', 'Its properties are well studied and it is widely available as a solvent and reference material. Simply existing as solid, liquid and gas, the source’s reason, is not unique to water.'],
      ['Where did India and Pakistan carry out their 1998 nuclear tests?', 'India at Pokhran and Pakistan at Chagai in Balochistan.'],
      ['What historical names are associated with Prithvi and Ghauri?', 'Prithvi is a Sanskrit word for Earth and also appears in the name Prithviraj. Ghauri refers to Muhammad of Ghor. The source gives an embellished naming story that should not be treated as verified history.'],
      ['What does the Ghaznavi name refer to?', 'Mahmud of Ghazni. The source instead links it to a spear; that explanation is not used as a verified answer.'],
      ['What does Hatf mean?', 'An Arabic word associated with death. The source connects it to a traditional sword name; treat that attribution separately from the literal meaning.'],
      ['What is a light-year?', 'The distance light travels in vacuum in one Julian year, about 9.46 trillion kilometres. It is a distance, not a duration.'],
      ['Who moved the Objectives Resolution, and where?', 'Liaquat Ali Khan moved it in Pakistan’s Constituent Assembly in 1949.'],
      ['What do ISSB and CTBT stand for?', 'Inter Services Selection Board; Comprehensive Nuclear-Test-Ban Treaty.'],
      ['Where is Siphon / Sidhnai Barrage in the source?', 'The source appears to say Sidhnai Barrage near Mian Channu. The scanned name is unclear; confirm the barrage name before using this as a quiz fact.'],
      ['Why is red used for danger signals?', 'It is a strong convention and is easily distinguished in many settings. Red visible light has a longer wavelength and lower frequency than blue, contrary to the source’s higher-frequency claim.'],
      ['Where is the Gobi Desert?', 'Across parts of northern China and southern Mongolia.'], ['What is Buenos Aires?', 'The capital of Argentina.'],
      ['What is the 23 March parade called?', 'The Pakistan Day Parade.'],
      ['What are the opening names of the fourth and fifth Quranic juz?', 'Fourth: Lan tanalu (لن تنالوا). Fifth: Wal-muhsanat (والمحصنات).'],
      ['What is the McMahon Line?', 'A boundary line associated with the eastern sector between India and Tibet, disputed by China. It is not the entire India-China border.'],
      ['Where is Panama?', 'In Central America, connecting North and South America. The source says South America alone.'], ['What does GTR stand for in the source?', 'Grand Trunk Road.'],
      ['Which five European countries are listed?', 'Portugal, United Kingdom, France, Belgium and Italy.'],
      ['Where is Chechnya?', 'A republic in the Russian Federation in the North Caucasus. The source’s claim that it is independent is incorrect.'],
      ['Where is Taxila?', 'Near Rawalpindi, on the route towards Attock.'],
      ['Which weapon figures are printed under Armoured Corps?', 'The source prints 1.5 metres and 122 mm without enough context to identify a valid specification. These are preserved as an unclear source entry, not an equipment fact.'],
      ['Where is the Pothohar Plateau?', 'In northern Punjab, including the Rawalpindi, Jhelum and Attock region.'], ['What is Pakistan’s highest civil award?', 'Nishan-e-Pakistan.'],
    ],
    note: 'Several answers are obsolete or scientifically wrong. Those errors are called out. The barrage name and an equipment specification are uncertain in the source.',
  },
  {
    sourceImage: 'IMG20260919120200.jpg', sourcePage: '78, 79', category: 'World',
    cards: [
      ['How many UN Security Council members are there?', '15: five permanent and ten elected members.'], ['What is Japan’s largest island?', 'Honshu.'],
      ['Is Japanese written from top to bottom?', 'Traditional Japanese can be written vertically, top to bottom with columns ordered right to left. Modern Japanese is also written horizontally.'],
      ['Where are the Red Sea and Mediterranean Sea?', 'The Red Sea lies between northeast Africa and the Arabian Peninsula. The Mediterranean lies south of Europe, north of Africa and west of the Levant.'],
      ['What is a census?', 'An official count and survey of a population. The source’s Pakistan population of about 180 million is an old figure, not a current estimate.'],
      ['Which range contains K2?', 'The Karakoram.'], ['Which mountain ranges are listed for Pakistan?', 'Himalaya, Karakoram, Hindu Kush, Sulaiman, Kirthar and Safed Koh.'],
      ['Where is the Maldives?', 'An island country in South Asia in the Indian Ocean, southwest of India and Sri Lanka.'],
      ['Who fought the first Battle of Panipat?', 'Babur and Ibrahim Lodi in 1526, not 1520 as printed.'],
      ['Which football world champion is named in the old notes?', 'Italy. This is an outdated answer without a tournament year, not the current champion.'],
      ['Who chaired the first SAARC summit?', 'Bangladesh’s President Hussain Muhammad Ershad. Do not confuse summit chair with the organisation’s secretary-general.'],
      ['When was the All-India Muslim League founded?', '1906.'], ['What was Gandhi’s full name?', 'Mohandas Karamchand Gandhi.'],
      ['Who were the Ali brothers?', 'Maulana Mohammad Ali Jauhar and Maulana Shaukat Ali.'],
      ['When did Islam reach Afghanistan?', 'Muslim armies reached parts of present-day Afghanistan in the seventh century; conversion spread over many centuries. The source’s single twelfth-century answer is too late as a starting date.'],
      ['When did Pakistan’s first constitution take effect?', '23 March 1956. Iskander Mirza became president; the source incorrectly attributes its enforcement to Khawaja Nazimuddin.'],
      ['How high is K2?', '8,611 metres. The source prints 8,624 metres.'],
      ['What Ghauri missile range does the source print?', '1,500 to 2,300 km. This is a historical source range and must not be treated as a verified specification without identifying a variant and source.'],
      ['What would an object weigh on the Moon?', 'About one-sixth of its Earth weight. Its mass remains the same.'],
      ['What area of Türkiye is printed in the source?', '744,742 km². Modern references generally give a total area around 783,562 km²; specify the land/total-area definition.'],
      ['How do an ocean and a sea differ?', 'Oceans are the major connected bodies of salt water. Seas are usually smaller subdivisions, often partly enclosed by land. The source’s claim that an ocean has no shore is incorrect.'],
      ['What are European countries?', 'Countries located wholly or partly in Europe. This is not the same as the European Union’s membership list.'],
      ['What lies north of Iran?', 'Armenia, Azerbaijan, the Caspian Sea and Turkmenistan are along its northern side. Afghanistan lies mainly to the east; the source’s one-word answer is misleading.'],
      ['Where was the eighth Islamic Summit held?', 'Tehran, Iran, in 1997.'],
      ['What does jumbo mean?', 'Very large. The source links it to a horse of Porus, which is not a reliable etymology. The word was popularised by a famous elephant named Jumbo.'],
      ['Who was Cyril Radcliffe?', 'The British lawyer who chaired the boundary commissions that drew the partition boundaries in Punjab and Bengal.'],
      ['How high is Minar-e-Pakistan?', 'About 70 metres (230 feet). The source prints 196 feet.'],
      ['Who developed the Grand Trunk Road?', 'Sher Shah Suri expanded and improved an ancient route. He did not originate every part of the road from nothing.'],
      ['Which aircraft names are printed in the old PAF list?', 'Mirage, Mushshak, F-5, F-6, F-7, F-16 and JF-17 Thunder. This is not a verified current fleet list; in particular, do not infer Pakistani F-5 service from this page.'],
      ['When was the Indus Waters Treaty signed?', '1960.'], ['Which international organisations are named for Pakistan?', 'OIC, UN, SAARC, ECO and D-8.'],
      ['Which ports and countries are paired in the source?', 'Alexandria: Egypt; Al Hudaydah: Yemen; Pasni: Pakistan; Jeddah: Saudi Arabia.'],
      ['Who was Razia Sultan?', 'A ruler of the Delhi Sultanate and its first female sovereign.'],
      ['Which Pakistani won the Nobel Prize in Physics?', 'Abdus Salam.'], ['Why are Taxila, Harappa and Mohenjo-daro famous?', 'For their archaeological remains of ancient civilisations and settlements.'],
      ['Where was the fourth Islamic Summit held?', 'Casablanca, Morocco, in 1984. The source says Islamabad, which is incorrect for the fourth summit.'],
      ['When did the Khilafat Movement begin?', '1919.'],
    ],
    note: 'The source’s geography, scientific definitions, K2 height, summit numbering and several historical dates are corrected. Old statistics and equipment claims remain clearly labelled.',
  },
  {
    sourceImage: 'IMG20260919120157.jpg', sourcePage: '76, 77', category: 'Pakistan',
    cards: [
      ['When did Quaid-e-Azam inaugurate the State Bank?', '1 July 1948.'], ['When did the Iranian Revolution take place?', '1979.'],
      ['Where is Changa Manga forest?', 'In Punjab, Pakistan. The source says Sindh, which is incorrect.'], ['How long is Khojak Tunnel?', 'About 3.9 km. The source prints 5.3 km; do not use that as the verified length.'],
      ['Who first used the words two-nation theory?', 'The source attributes this to Shah Waliullah. The development of the idea involves several thinkers; a claim about the first use of these exact words needs a specific historical citation.'],
      ['When and where was the UN established?', 'The Charter was signed in San Francisco and came into force in 1945. Its headquarters is in New York; that is not the Charter-signing location.'],
      ['When did the Second World War begin?', '1939.'], ['How long is Pakistan’s coastline?', 'Published estimates vary with measurement. The source gives 700 km; a commonly cited modern estimate is about 1,046 km. State the source rather than treating an old figure as exact.'],
      ['What literacy figure is printed in the notes?', '47%. It is undated and outdated, not a current statistic. Use the latest Pakistan Economic Survey or census and state the population definition.'],
      ['How long is the Pakistan-Iran border?', 'Often reported at roughly 900 km; the exact figure depends on the reference. The source prints 900 km.'],
      ['Which five Sindh cities are named?', 'Karachi, Hyderabad, Sanghar, Mirpur Khas and Sukkur. This is not a verified current population ranking.'],
      ['Which five cities are listed under Sarhad?', 'Peshawar, Abbottabad, Nowshera, Dera Ismail Khan and Mardan. Sarhad / NWFP is the older name for Khyber Pakhtunkhwa.'],
      ['Which five Punjab cities are named?', 'Lahore, Gujranwala, Rawalpindi, Multan and Faisalabad.'],
      ['Which five places in Indian-administered Kashmir are named?', 'Srinagar, Bandipora, Kupwara, Anantnag and Doda. This is the source list, not a current size ranking.'],
      ['Which three British political parties are named?', 'Labour, Conservative (Tory) and Liberal. Liberal Democrats is the relevant modern major-party name rather than treating the old Liberal Party label as interchangeable.'],
      ['How do communism and socialism differ?', 'They cover a range of ideas about collective or public ownership and economic organisation. Some socialist systems coexist with markets and private firms. The source incorrectly treats both as one system in which government owns everything.'],
      ['Which border towns are named in the notes?', 'Lahore, Wagah, Sialkot, Head Sulemanki, Ganda Singh Wala, Rasulpur and Khem Karan. These are source examples across the border region, not all Pakistani cities.'],
      ['Who commissioned the Red Fort in Delhi?', 'Mughal emperor Shah Jahan.'], ['Who was Pakistan’s first president?', 'Iskander Mirza.'],
      ['Where do the Kabul and Indus rivers meet?', 'Near Attock.'], ['How long is the Great Wall of China?', 'Its measured total depends on which walls and branches are included. The complete surveyed system exceeds 21,000 km; the source’s 1,500-mile figure is not a reliable total.'],
      ['When did Pakistan join the Non-Aligned Movement?', '1979, not 1989 as printed in the source.'],
      ['Who approved Islamabad as the new capital?', 'The decision was taken under President Ayub Khan. The source gives 1960; planning and approval involved several steps around 1959 and 1960.'],
      ['Who composed the national anthem’s music?', 'Ahmed Ghulam Ali Chagla. Hafeez Jalandhari wrote the lyrics.'], ['What is Pakistan’s largest desert?', 'The Thar Desert.'],
      ['What years did Pakistan’s sixth five-year plan cover?', '1983 to 1988. The source calls it the fifth plan, which is incorrect.'],
      ['Which country is called the Land of the Rising Sun?', 'Japan.'], ['Which country does the source call the land of the setting sun?', 'Denmark. This is not a standard geographical title and should not be memorised as a unique fact.'],
      ['Which marine animal nurses its young with milk?', 'A whale. Whales are mammals, not fish.'],
      ['Which university does the source name as Pakistan’s largest?', 'University of the Punjab. Largest is ambiguous without specifying enrolment, campus area or another measure.'],
      ['Which hydropower plant is called the oldest in the notes?', 'Warsak. Earlier hydropower installations exist, so the source’s unrestricted oldest claim should not be used without defining the comparison.'],
      ['Where is the SAARC Secretariat?', 'Kathmandu, Nepal.'], ['Who was Pakistan’s first foreign minister?', 'Sir Muhammad Zafarullah Khan.'],
      ['Who was the first president of the All-India Muslim League?', 'Aga Khan III.'], ['When did Pakistan join the UN?', '30 September 1947.'],
      ['What agriculture-employment figure is printed?', '53% of the population. The source gives no date or definition and confuses population with employment share. Do not treat it as current.'],
      ['Which Turkish city spans Europe and Asia?', 'Istanbul.'], ['Where does the Tigris flow?', 'Through Türkiye and Iraq, with part of its course along the Syrian border. The source names Iraq.'],
      ['Which Pakistani coast is named in the notes?', 'The Makran coast. It covers a large part of Balochistan’s Arabian Sea coast.'],
      ['Who first stepped onto the Moon?', 'Neil Armstrong.'], ['What Pakistan-China border length does the source give?', '600 km. Modern references commonly give about 523 km; do not treat the rounded source number as exact.'],
      ['Where is the World Bank headquartered?', 'Washington, D.C., United States, not Geneva as printed.'],
    ],
    note: 'English study translation of both Urdu pages. Dated statistics and doubtful superlatives are labelled, and clear factual errors are corrected.',
  },
  {
    sourceImage: 'IMG20260919120152.jpg', sourcePage: '74', category: 'World',
    cards: [
      ['Bangladesh: capital?', 'Dhaka.'], ['India: capital?', 'New Delhi.'], ['Afghanistan: capital?', 'Kabul.'], ['Nepal: capital?', 'Kathmandu.'],
      ['Bhutan: capital?', 'Thimphu.'], ['Maldives: capital?', 'Malé.'], ['Sri Lanka: capital?', 'Sri Jayawardenepura Kotte is the legislative capital; Colombo is the main commercial city. The source gives Colombo alone.'],
      ['Russia: capital?', 'Moscow.'], ['China: capital?', 'Beijing; Peking is an older English spelling in the source.'], ['Türkiye: capital?', 'Ankara.'],
      ['Denmark: capital?', 'Copenhagen.'], ['Finland: capital?', 'Helsinki.'], ['Norway: capital?', 'Oslo.'], ['United Kingdom: capital?', 'London.'],
      ['United States: capital?', 'Washington, D.C.'], ['Belgium: capital?', 'Brussels.'], ['Netherlands: capital?', 'Amsterdam; the government sits in The Hague. Holland is only part of the country.'],
      ['North Korea: capital?', 'Pyongyang. The source swaps the two Korean capitals.'], ['South Korea: capital?', 'Seoul. The source swaps the two Korean capitals.'],
      ['Vietnam: capital?', 'Hanoi.'], ['Canada: capital?', 'Ottawa.'], ['Italy: capital?', 'Rome.'], ['Germany: capital?', 'Berlin.'],
      ['Which country has Doha as its capital?', 'Qatar. The country label beside Doha is covered by a hand in the photo, so this pairing is supplied as a factual clarification, not a complete transcription.'],
      ['Egypt: capital?', 'Cairo is the capital named in the source. Egypt is developing and moving government functions to a new administrative capital; check the official status for a current-affairs answer.'],
      ['Iran: capital?', 'Tehran.'], ['Chechnya: capital?', 'Grozny. Chechnya is a republic within Russia, not an independent country.'],
      ['Myanmar: capital?', 'Naypyidaw. Yangon (Rangoon), given in the old notes, is the former capital.'], ['Philippines: capital?', 'Manila.'], ['Iraq: capital?', 'Baghdad.'],
      ['Saudi Arabia: capital?', 'Riyadh.'], ['Libya: capital?', 'Tripoli.'], ['Sudan: capital?', 'Khartoum is the constitutional capital; war has displaced government functions.'],
      ['Sweden: capital?', 'Stockholm.'], ['Tajikistan: capital?', 'Dushanbe.'], ['Uzbekistan: capital?', 'Tashkent.'], ['Azerbaijan: capital?', 'Baku.'],
      ['Switzerland: federal city?', 'Bern.'], ['France: capital?', 'Paris.'], ['Uganda: capital?', 'Kampala.'], ['Austria: capital?', 'Vienna.'],
      ['Greece: capital?', 'Athens.'], ['Angola: capital?', 'Luanda.'], ['Paraguay: capital?', 'Asunción.'], ['Oman: capital?', 'Muscat.'],
      ['Japan: capital?', 'Tokyo.'], ['Brazil: capital?', 'Brasília.'], ['Rwanda: capital?', 'Kigali.'],
    ],
    note: 'All readable country-capital pairs are covered. Corrects the swapped Korean capitals, obsolete Myanmar capital, Sri Lankan distinction and the status of Chechnya. The final right-hand country label is obscured.',
  },
  {
    sourceImage: 'IMG20260919120152.jpg', sourcePage: '75', category: 'World',
    cards: [
      ['Which Middle Eastern places are listed in the notes?', 'Iran, Iraq, Syria, Lebanon, Saudi Arabia, Kuwait, Yemen, Bahrain, United Arab Emirates, Israel and Palestine. This source list is not exhaustive.'],
      ['Which places are listed under Far East in the source?', 'Japan, North and South Korea, Myanmar, Thailand, Vietnam, Taiwan, Cambodia and China. Myanmar, Thailand, Vietnam and Cambodia are normally classified as Southeast Asia.'],
      ['Which countries are Scandinavian?', 'Denmark, Norway and Sweden. The source also lists Finland, which is Nordic but not usually included in Scandinavia in the strict geographical sense.'],
      ['Which Latin American countries are named?', 'Brazil, Argentina, Chile, Colombia, Bolivia and Paraguay. They are examples, not a complete list.'],
      ['What were the seven former FATA agencies?', 'Bajaur, Mohmand, Khyber, Kurram, Orakzai, North Waziristan and South Waziristan. Malakand, included in the source, was not one of the seven.'],
      ['Which UN Security Council permanent members have veto power?', 'China, France, Russia, the United Kingdom and the United States.'],
      ['What are the seven emirates of the UAE?', 'Abu Dhabi, Dubai, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah and Fujairah. The source omits Umm Al Quwain.'],
      ['Where is Khanpur Dam?', 'On the Haro River near Khanpur in Khyber Pakhtunkhwa.'], ['Where is Tarbela Dam?', 'On the Indus River in Khyber Pakhtunkhwa.'],
      ['Where is Mangla Dam?', 'On the Jhelum River near Mirpur in Azad Jammu and Kashmir.'], ['Where is Warsak Dam?', 'On the Kabul River near Peshawar.'],
      ['Where is the Ghazi-Barotha project?', 'On the Indus River, using a diversion and power channel near Ghazi and Barotha. It is a run-of-river hydropower scheme.'],
      ['What is Saindak?', 'A copper-gold mining project in Balochistan, not a dam.'],
      ['Where is the Khyber Pass?', 'Near Peshawar, linking Pakistan with Afghanistan.'], ['Where is the Bolan Pass?', 'In Balochistan.'],
      ['Where is Cyprus?', 'An island in the eastern Mediterranean, south of Türkiye.'], ['Where is Cuba?', 'In the Caribbean, geographically part of North America.'],
      ['Where is Malta?', 'An island country in the Mediterranean, south of Sicily, historically important on routes between Europe and North Africa.'],
      ['Where is the Dead Sea?', 'Between Jordan to the east and Israel and the occupied West Bank to the west. It is a salt lake, not an ocean sea.'],
      ['Where is the Yellow Sea?', 'Between China and the Korean Peninsula.'], ['Where is the Black Sea?', 'North of Türkiye, bordered by several countries in Europe and Asia.'],
      ['Where are the Andaman Islands?', 'In the Bay of Bengal, part of the Indian Ocean.'], ['Where are the West Indies?', 'The Caribbean island region, geographically associated with North America.'],
    ],
    note: 'The source has several geographical errors and incomplete lists. Its topics are retained with corrected answers.',
  },
  {
    sourceImage: 'IMG20260919120150.jpg', sourcePage: '73', category: 'World',
    cards: [
      ['What is the capital of Syria?', 'Damascus.'], ['What is the constitutional capital of Yemen?', "Sana'a. Aden has served as the temporary seat of Yemen's internationally recognised government during the conflict."],
      ['What is the capital of Somalia?', 'Mogadishu.'], ['What is the capital of Bosnia and Herzegovina?', 'Sarajevo.'],
      ['What is the capital of Lebanon?', 'Beirut.'],
      ['How should the Jerusalem entry in the source be explained?', "Israel calls Jerusalem its capital. Palestinians seek East Jerusalem as the capital of a future Palestinian state, and the city's status is disputed internationally. The source's single-word answer omits this context."],
    ],
    note: 'The facing pages contain a blank officeholder checklist. It is preserved in interview prompts with corrections to outdated titles.',
  },
  {
    sourceImage: 'IMG20260919120148.jpg', sourcePage: '70 and facing Army notes', category: 'Service knowledge',
    cards: [
      ['What are the two broad Army groups used in the notes?', 'Fighting arms and services. This is the source classification, not a complete organisational chart.'],
      ['Which five fighting arms are listed?', 'Infantry, Armoured Corps, Artillery, Engineers and Air Defence.'],
      ['Which five services are listed?', 'Signals, Ordnance, Army Education Corps, Army Service Corps and Army Medical Corps.'],
      ['Which tank and manufacturing location are named in the notes?', 'Al-Khalid tank, Taxila.'],
      ['Which missile is linked with Dr Abdul Qadeer Khan in the notes?', 'Ghauri. The source gives a range of 1,500 km; treat that as a historical source claim, not a verified specification for every variant.'],
      ['What is an armoured personnel carrier?', 'A protected vehicle for transporting personnel. The usual abbreviation is APC; the source prints A.P.'],
      ['Which Army chiefs are printed in the old notes?', 'General Raheel Sharif and General Ahsan Saleem Hayat, with Rawalpindi as headquarters. This is an outdated and chronologically inconsistent pairing, not a current leadership list.'],
      ['Which Navy chiefs are printed in the old notes?', 'Admiral Zakaullah and Vice Admiral Asif Humayun, with Islamabad as headquarters. Do not treat this old pairing as current.'],
      ['Which Air Force chiefs are printed in the old notes?', 'Air Chief Marshal Tahir Rafique Butt and Air Marshal Sohail Gul. The headquarters entry is obscured in this photo; Air Headquarters is in Islamabad. The names are historical, not current.'],
      ['Which recipient is missing from the photographed ten-name award table?', 'Naik Saif Ali Janjua, recipient of Hilal-e-Kashmir, which was declared equivalent to Nishan-e-Haider. The interview story collection includes him as the eleventh person.'],
    ],
    note: 'The source award table is preserved separately. Its Rashid Minhas location and squadron should not be used as a verified account. See the researched stories for the corrected biography. A hand covers the Air Force headquarters entry.',
  },
  {
    sourceImage: 'IMG20260919120145.jpg', sourcePage: '68 and facing service notes', category: 'Service knowledge',
    cards: [
      ['What is Nishan-e-Haider?', "Pakistan's highest military gallantry award. It is an award, not a rank. The source describes a star-shaped medal with a crescent and star."],
      ['Which award is next below Nishan-e-Haider in gallantry precedence?', 'Hilal-e-Jurat.'],
      ['Which armoured equipment names appear in the source?', 'T-59, T-85 and Al-Khalid tanks, together with a mortar entry. This is a historical study list, not a current inventory.'],
      ['Which infantry equipment names appear in the source?', 'Light machine gun (LMG), machine gun (MG), hand grenade, rocket launcher and mortar. Names only; the list is not exhaustive.'],
      ['At a general level, how do a gun, mortar, artillery piece and tank differ?', 'Gun is a broad term. A mortar is generally a high-angle indirect-fire weapon. Artillery refers to larger support weapons. A tank is an armoured fighting vehicle with a main gun. The source oversimplifies which branch operates each.'],
    ],
    note: 'The rank comparison table is preserved separately as a source table. It is not proof of identical status, especially for Midshipman, a training-stage rank. The equipment list is not a current inventory or operating guide.',
  },
  {
    sourceImage: 'IMG20260919120143.jpg', sourcePage: '66 and facing interview notes', category: 'World',
    cards: [
      ['What does VCR stand for?', 'Video cassette recorder. It records and plays video on magnetic tape.'],
      ['Which meanings of BP are printed in the interview notes?', 'Blueprint, boiling point and blood pressure. Ask for context rather than guessing.'],
      ['Which bowling variations appear in the notes?', 'Left-arm wrist spin (called Chinaman in the source), outswing, inswing, leg cutter, off cutter and yorker. These are examples, not an exhaustive classification of bowling.'],
      ['How long is a cricket pitch?', '22 yards, or 66 feet (20.12 metres).'],
      ['What is the width of a cricket wicket?', '9 inches (22.86 cm) across the three stumps. The wickets are 22 yards apart; do not confuse wicket width with pitch length.'],
      ["How much does a new men's cricket ball weigh?", 'Between 5.5 and 5.75 ounces (155.9 to 163 grams). The source gives only 5.5 ounces.'],
      ['Which cricket fielding positions appear in the notes?', 'Wicketkeeper, slip, gully, point, cover, extra cover, mid-off, mid-on, long leg, third man and midwicket.'],
      ['Which cricket dismissals appear in the notes?', 'Bowled, leg before wicket (LBW), hit wicket, run out, stumped and caught. These are common examples, not every dismissal allowed by the Laws.'],
    ],
    note: 'The source mixes bowling styles with deliveries and oversimplifies ball weight. The study answers distinguish these.',
  },
  {
    sourceImage: 'IMG20260919120136.jpg', sourcePage: '64, 65', category: 'Service knowledge',
    cards: [
      ['NPA', 'National Police Academy. The source misprints Police as Publice.'], ['NPT', 'Treaty on the Non-Proliferation of Nuclear Weapons.'],
      ['NSP (source wording)', 'The source pairs NSP with National Shipping Corporation. The Pakistani organisation is Pakistan National Shipping Corporation, abbreviated PNSC.'],
      ['NWFP', 'North-West Frontier Province, the former name of Khyber Pakhtunkhwa.'],
      ['OAN (source wording)', 'The page gives Organization of Arab Nation, which is not a verified standard organisation name. The Arab League is formally the League of Arab States.'],
      ['OIC', 'Organisation of Islamic Cooperation. The source uses the former name Organisation of the Islamic Conference.'],
      ['Where does OK come from?', 'It is commonly traced to the humorous spelling oll korrect for all correct. It is not a modern institutional acronym.'],
      ['OP', 'Observation post or observation point in a military context.'], ['OPEC', 'Organization of the Petroleum Exporting Countries.'],
      ['PA', 'Personal assistant in this source.'], ['PAEC', 'Pakistan Atomic Energy Commission.'], ['PAF', 'Pakistan Air Force.'],
      ['PAFWA', "Pakistan Air Force Women's Association."], ['PAMS', 'Pakistan Academy of Medical Sciences.'], ['PARCO', 'Pak-Arab Refinery Company.'],
      ['PBC', 'Pakistan Broadcasting Corporation.'], ['PCO', 'Provisional Constitutional Order.'], ['PIMS', 'Pakistan Institute of Medical Sciences.'],
      ['PMA', 'Pakistan Military Academy.'], ['PN', 'Pakistan Navy.'], ['POF', 'Pakistan Ordnance Factories.'], ['PPC', 'Pakistan Penal Code.'],
      ['PPI', 'Pakistan Press International.'], ['PSO', 'Pakistan State Oil.'], ['PTA', 'Pakistan Telecommunication Authority.'], ['PTO', 'Please turn over.'],
      ['PTV', 'Pakistan Television.'], ['RAW', 'Research and Analysis Wing.'], ['SAARC', 'South Asian Association for Regional Cooperation.'],
      ['SDO', 'Sub-Divisional Officer.'], ['SBP', 'State Bank of Pakistan.'], ['SEATO', 'Southeast Asia Treaty Organization, a former alliance.'],
      ['SIPRI', 'Stockholm International Peace Research Institute.'], ['SMLA', 'Sub-Martial Law Administrator, a historical designation.'],
      ['SPO', 'Strengthening Participatory Organization.'], ['SSG', 'Special Service Group.'], ['SUPARCO', 'Space and Upper Atmosphere Research Commission.'],
      ['UAE', 'United Arab Emirates.'], ['UK', 'United Kingdom.'], ['UNESCO', 'United Nations Educational, Scientific and Cultural Organization.'],
      ['UNICEF', "United Nations Children's Fund. Its acronym comes from its earlier name, United Nations International Children's Emergency Fund."],
      ['UNO', 'United Nations Organization; UN is the usual short form.'], ['UPP', 'United Press of Pakistan.'], ['USA', 'United States of America.'],
      ['USAID', 'United States Agency for International Development.'], ['USSR', 'Union of Soviet Socialist Republics, a former state.'],
      ['WAPDA', 'Water and Power Development Authority.'], ['WASA', 'Water and Sanitation Agency.'], ['WHO', 'World Health Organization.'],
      ['WTO', 'World Trade Organization.'], ['WWF', 'World Wide Fund for Nature internationally; World Wildlife Fund remains its name in some countries.'],
      ['WWW', 'World Wide Web.'], ['W/O', 'Warrant Officer.'], ['Z.C. (source wording)', 'Zone Checker in this source; the meaning depends on the organisation using it.'],
    ],
    note: 'All entries 80 to 133 are retained. Historical names, source typos and uncertain expansions are labelled.',
  },
  {
    sourceImage: 'IMG20260919120134.jpg', sourcePage: '62, 63', category: 'Service knowledge',
    cards: [
      ['Brig.', 'Brigadier.'], ['CAA', 'Civil Aviation Authority.'], ['CAS', 'Chief of the Air Staff.'],
      ['CBI', 'Central Bureau of Investigation, India.'], ['CBR', "Central Board of Revenue, the former name of Pakistan's Federal Board of Revenue (FBR)."],
      ['CDA', 'Capital Development Authority.'], ['CEC', 'Chief Election Commissioner.'], ['CENTO', 'Central Treaty Organization, a former alliance.'],
      ['CIA', 'Central Intelligence Agency.'], ['CID', 'Criminal Investigation Department.'], ['CSP', 'Civil Service of Pakistan, a historical service designation.'],
      ['CSS', 'Central Superior Services.'], ['CSSP (source wording)', 'The source prints Central Superior Service of Pakistan. CSS is the usual abbreviation; this is not a separate verified institution.'],
      ['CTBT', 'Comprehensive Nuclear-Test-Ban Treaty.'], ['DIG', 'Deputy Inspector General.'], ['ECO', 'Economic Cooperation Organization.'],
      ['EPB', 'Export Promotion Bureau, a former Pakistani trade-promotion body.'], ['FATA', 'Federally Administered Tribal Areas, a former administrative region merged into Khyber Pakhtunkhwa.'],
      ['FIR', 'First Information Report, not First Investigation Report as printed.'], ['GCC', 'Gulf Cooperation Council.'], ['GHQ', 'General Headquarters.'],
      ['GMT', 'Greenwich Mean Time.'], ['GNA (source wording)', 'The page gives Gulf News Agency. The abbreviation is context-dependent; for example, Ghana News Agency also uses GNA.'],
      ['GNP', 'Gross National Product.'], ['GT Road', 'Grand Trunk Road.'], ['GTO', 'Group Testing Officer.'], ['IATA', 'International Air Transport Association.'],
      ['IB', 'Intelligence Bureau.'], ['IBM', 'International Business Machines.'], ['IBRD', 'International Bank for Reconstruction and Development.'],
      ['IAEA', 'International Atomic Energy Agency.'], ['ICC', 'International Cricket Council in this source. In legal affairs, ICC means International Criminal Court.'],
      ['ICJ', 'International Court of Justice.'], ['IDBP', 'Industrial Development Bank of Pakistan.'], ['ILO', 'International Labour Organization.'],
      ['IMF', 'International Monetary Fund.'], ['ISPR', 'Inter Services Public Relations.'], ['ISSB', 'Inter Services Selection Board.'],
      ['KANUPP', 'Karachi Nuclear Power Plant.'], ['KKA (source wording)', 'The page prints Kara Kram Agency. This is not a verified standard expansion; retain it only as a source-reading note.'],
      ['KKH', 'Karakoram Highway.'], ['MBA', 'Master of Business Administration.'], ['MBBS', 'Bachelor of Medicine, Bachelor of Surgery.'],
      ['MCG', 'Melbourne Cricket Ground.'], ['MES', 'Military Engineer Services.'], ['NAM', 'Non-Aligned Movement.'],
      ['NASA', 'National Aeronautics and Space Administration.'], ['NATO', 'North Atlantic Treaty Organization.'], ['NCC', 'National Cadet Corps.'],
      ['Is NEWS an acronym for North, East, West, South?', 'No. News comes from the idea of new information. North, East, West, South is a memory phrase in the source, not its etymology.'],
      ['NIPA', 'National Institute of Public Administration.'], ['NIT', 'National Investment Trust.'], ['NLI', 'Northern Light Infantry.'], ['NOC', 'No Objection Certificate.'],
    ],
    note: 'All 54 entries are retained. Incorrect expansions, ambiguous initials and former organisations are explicitly distinguished.',
  },
  {
    sourceImage: 'IMG20260919120131.jpg', sourcePage: '60', category: 'Science',
    cards: [
      ['What is frequency?', 'The number of complete cycles per second, measured in hertz (Hz).'],
      ['What is the difference between g and G?', "G is the universal gravitational constant, about 6.674 × 10⁻¹¹ N·m²/kg². g is local gravitational acceleration, about 9.8 m/s² near Earth's surface, and varies with location."],
      ['What is boiling point?', 'The temperature at which the vapour pressure of a liquid equals the external pressure.'],
      ['What causes day and night?', "Earth rotates on its axis. The side facing the Sun has daylight and the side facing away has night."],
      ['How does an aeroplane fly?', 'Engines or propellers provide thrust. Airflow around the wings produces a pressure distribution and deflects air downward, creating lift. In steady level flight, lift balances weight and thrust balances drag.'],
    ],
    note: 'The printed answer confuses propeller thrust with wing lift. The wing and engine roles are separated here. P = F/A on this page continues the preceding pressure answer.',
  },
  {
    sourceImage: 'IMG20260919120131.jpg', sourcePage: '61', category: 'Service knowledge',
    cards: [
      ['ABC', 'Audit Bureau of Circulations.'], ['ADC', 'Agricultural Development Corporation in this list; in military contexts, ADC also means aide-de-camp.'],
      ['AEC', 'Army Education Corps.'], ['AG', 'Adjutant General.'], ['AHQ', 'Air Headquarters.'],
      ['AIDS', 'Acquired immunodeficiency syndrome.'], ['AIR', 'All India Radio.'], ['AM (time)', 'Ante meridiem, before noon.'],
      ['AMC', 'Army Medical Corps.'], ['ANF', 'Anti Narcotics Force.'], ['ANN', 'Asia News Network.'],
      ['APA (source wording)', 'The page prints Associated Press of America. The major US news agency is Associated Press, abbreviated AP; do not memorise APA as its standard name.'],
      ['APC', 'All Parties Conference in this political context; armoured personnel carrier in military usage.'],
      ['APEC', 'Asia-Pacific Economic Cooperation.'], ['API', 'Associated Press of India, a historical news agency.'],
      ['APNS', 'All Pakistan Newspapers Society.'], ['APWA', "All Pakistan Women's Association."],
      ['ASC', 'Army Service Corps.'], ['ASI', 'Assistant Sub-Inspector.'], ['Adjt.', 'Adjutant.'], ['Adm.', 'Admiral.'],
      ['BBC', 'British Broadcasting Corporation.'], ['BPS', 'Basic Pay Scale.'], ['BP', 'Blood pressure or boiling point, depending on context.'],
      ['BRB', 'Bambanwala-Ravi-Bedian Canal.'],
    ],
    note: 'Spelling and official names are normalised. Ambiguous or historical abbreviations are identified instead of presenting every expansion as universal.',
  },
  {
    sourceImage: 'IMG20260919120128.jpg', sourcePage: '58, 59', category: 'Science',
    cards: [
      ['Why do seasons change, and why does weather change?', "Seasons mainly result from Earth's tilted axis as it orbits the Sun, not changes in Earth-Sun distance. Day-to-day weather changes with moving air masses, pressure, temperature and moisture."],
      ['Why is Murree usually cooler than Lahore?', 'Murree is at a much higher altitude. In the lower atmosphere, temperature generally decreases with height as rising air expands and cools.'],
      ['Why can water pipes burst in winter?', 'Water expands when it freezes. If trapped in a pipe, the expanding ice can create enough pressure to split the pipe. Water is densest near +4°C, not -4°C.'],
      ['Why does wind blow?', 'Air moves in response to pressure differences produced partly by unequal heating. Rotation and friction also affect its direction and speed.'],
      ['What causes thunder?', 'Lightning heats the surrounding air rapidly. The sudden expansion creates a shock wave heard as thunder. Clouds do not need to collide.'],
      ['Why does a thrown object normally fall back down?', "Earth's gravity pulls it down. Ordinary throws do not give an object enough speed to escape Earth's gravity."],
      ['How do potential and kinetic energy differ?', 'Potential energy is associated with position or configuration. Kinetic energy is associated with motion.'],
      ['What is the difference between a dam and a barrage?', 'A dam commonly creates a reservoir to store water and may generate electricity. A barrage is a gated structure mainly used to regulate river level and divert flow, often into irrigation canals.'],
      ['What are isotopes?', 'Atoms of the same element with the same proton number but different neutron numbers, and therefore different mass numbers.'],
      ['What is specific heat capacity?', 'Energy needed to raise the temperature of 1 kg of a substance by 1 kelvin, equivalent to a 1°C temperature change. Unit: J/(kg·K).'],
      ['What does a voltmeter measure?', 'Potential difference between two points in a circuit, in volts.'],
      ['How do hard and soft water differ?', 'Hard water contains appreciable calcium or magnesium ions and forms lather with soap less readily. Soft water has low concentrations of these ions and lathers more easily.'],
      ['How does a rocket take off?', "It accelerates exhaust gas backward and receives an opposite thrust, consistent with Newton's third law and momentum conservation. It does not need to push against air."],
      ['What is pressure?', 'Normal force per unit area: P = F/A. The SI unit is the pascal (N/m²).'],
    ],
    note: 'The source answers about seasons, Murree, freezing and thunder contain errors. Their questions are retained with corrected explanations rather than teaching those errors.',
  },
  {
    sourceImage: 'IMG20260919120125.jpg', sourcePage: '56, 57', category: 'Science',
    cards: [
      ["What is Newton's law of cooling?", 'Under suitable conditions, the rate of heat loss is proportional to the temperature difference between an object and its surroundings. The proportionality depends on the object and heat-transfer conditions.'],
      ['What is heat, and what can it do?', 'Energy transferred because of a temperature difference. Heating may raise temperature, cause expansion, change a state of matter or drive physical and chemical changes.'],
      ['What is reflection?', 'The return of a wave into its original medium after meeting a boundary.'],
      ['What are the laws of reflection?', 'The angle of incidence equals the angle of reflection. The incident ray, reflected ray and normal at the point of incidence lie in one plane. Angles are measured from the normal.'],
      ['What is refraction of light?', 'A change in direction as light enters a medium in which its speed differs, except when it enters along the normal.'],
      ['How does a rainbow form?', 'Sunlight is refracted, dispersed into colours and internally reflected inside water droplets. A primary rainbow is seen opposite the Sun. The internal reflection need not be total.'],
      ['What is the focal length of a spherical mirror?', 'The distance from the pole of the mirror to its principal focus.'],
      ['What is the speed of sound in air?', 'About 331 m/s in dry air at 0°C, or 343 m/s at 20°C. It depends on the medium and temperature.'],
      ['What is a transverse wave?', 'A wave whose oscillation is perpendicular to the direction of propagation.'],
      ['What is a longitudinal wave?', 'A wave whose oscillation is parallel to the direction of propagation.'],
      ['What is torque?', 'The turning effect of a force about an axis. Magnitude = force × perpendicular distance from the axis to the line of action. Its SI unit is N·m.'],
      ['What is a capacitor?', 'A device that stores separated electric charge and energy in an electric field.'],
      ['What is weather?', 'The short-term condition of the atmosphere at a place, including temperature, rain, wind and humidity. It is not limited to a fixed one- or two-day period.'],
      ['What is sound?', 'A mechanical disturbance travelling through a medium. Audible sound can produce the sensation of hearing.'],
      ["What is Coulomb's law?", 'The electrostatic force between point charges is proportional to the product of their charges and inversely proportional to the square of their separation: F = k|q₁q₂|/r². Like charges repel; unlike charges attract.'],
    ],
    note: 'Corrects the source on cooling dependence, rainbow reflection, the temperature needed for 331 m/s, and the definition of weather.',
  },
  {
    sourceImage: 'IMG20260919120120.jpg', sourcePage: '52, 53', category: 'Science',
    cards: [
      ["What is Newton's first law of motion?", 'With no net external force, an object stays at rest or continues with constant velocity in a straight line.'],
      ["What is Newton's second law of motion?", 'For constant mass, net force equals mass × acceleration: F = ma. Acceleration is proportional to net force and inversely proportional to mass.'],
      ["What is Newton's third law of motion?", 'When one body exerts a force on another, the second exerts an equal and opposite force on the first. The pair acts on different bodies.'],
      ["What is Newton's law of universal gravitation?", 'Two masses attract with a force proportional to their mass product and inversely proportional to the square of their separation: F = Gm₁m₂/r².'],
      ['How do mass and weight differ?', 'Mass is a scalar measured in kilograms and does not change just because location changes. Weight is gravitational force, a vector measured in newtons; it changes with gravitational field strength. W = mg.'],
      ['What is kinetic energy?', 'Energy associated with motion: KE = ½mv² in classical mechanics.'],
      ['What is potential energy?', 'Energy associated with position or configuration, such as a raised object or a stretched spring.'],
      ['What is momentum?', 'Mass × velocity: p = mv. It is a vector measured in kg·m/s.'],
      ['What is power?', 'The rate of doing work or transferring energy: P = W/t for average power. Its SI unit is the watt.'],
      ['What is energy?', 'The capacity to do work, measured in joules. Kinetic and potential energy are two forms; thermal, chemical and other forms also exist.'],
      ['What is centripetal force?', 'The net inward force that produces circular motion, directed towards the centre. For uniform circular motion, F = mv²/r.'],
      ['What is centrifugal force?', 'An apparent outward force used when describing motion in a rotating reference frame. It is not an additional outward interaction in an inertial frame.'],
      ['What is a machine?', 'A device that can change the magnitude or direction of a force, or trade force for distance or speed. It does not create energy.'],
    ],
    note: 'The source calls kinetic and potential the only types of energy and omits the rotating-frame qualification for centrifugal force. Both are corrected here.',
  },
  {
    sourceImage: 'IMG20260919120123.jpg', sourcePage: '54, 55', category: 'Science',
    cards: [
      ['What is friction?', 'A contact force that opposes relative sliding or the tendency to slide between surfaces.'],
      ["What is Pascal's law?", 'A pressure change applied to an enclosed fluid is transmitted undiminished throughout the fluid and to its container.'],
      ["What is Hooke's law?", 'Within the proportional limit, stress is proportional to strain. For an ideal spring, force is proportional to extension: F = kx.'],
      ['What does a barometer measure?', 'Atmospheric pressure.'],
      ["What is Archimedes' principle?", 'An object partly or wholly immersed in a fluid experiences an upward buoyant force equal to the weight of fluid it displaces. Its apparent weight is reduced, not its mass.'],
      ['How are pressure and thrust related?', 'Pressure is normal force per unit area: P = F/A. For uniform pressure, thrust = pressure × area.'],
      ['What is radioactivity?', 'Spontaneous emission of radiation from unstable atomic nuclei.'],
      ['What does a galvanometer detect?', 'Small electric currents.'],
      ['What is a semiconductor?', 'A material with electrical conductivity between that of typical conductors and insulators.'],
      ['What does an electric motor do?', 'Converts electrical energy into mechanical energy.'],
      ['What does an AC generator do?', 'Converts mechanical energy into electrical energy with an alternating output.'],
      ["What is Boyle's law?", 'For a fixed amount of gas at constant temperature, pressure is inversely proportional to volume: PV is constant.'],
      ["What is Charles's law?", 'For a fixed amount of gas at constant pressure, volume is proportional to absolute temperature in kelvin: V/T is constant.'],
      ['What is electric current?', 'The rate of flow of electric charge: I = Q/t for a steady current. The SI unit is the ampere.'],
    ],
    note: 'The printed definitions are clarified: enclosed fluid for Pascal, proportional limit for Hooke, apparent weight for buoyancy, kelvin for Charles, and charge per unit time for current.',
  },
  {
    sourceImage: 'IMG20260919120118.jpg', sourcePage: '51', category: 'Science',
    cards: [
      ['What does a vernier caliper measure?', 'External and internal dimensions and depth. Resolution depends on the instrument; 0.1 mm is the example in the source.'],
      ['What is a scalar quantity?', 'A quantity described by magnitude alone, such as mass, length, speed, time, work or density.'],
      ['What is a vector quantity?', 'A quantity with magnitude and direction, such as force, acceleration, displacement, velocity or torque.'],
      ['What is average speed?', 'Total distance divided by total elapsed time. Its SI unit is metres per second (m/s).'],
      ['What is average velocity?', 'Displacement divided by elapsed time. It is a vector measured in m/s.'],
      ['What is average acceleration?', 'Change in velocity divided by elapsed time: (final velocity minus initial velocity) / time. Its SI unit is m/s².'],
    ],
    note: 'The printed acceleration formula omits change in velocity. The corrected definition is used here. Caliper resolution is not universal.',
  },
];
