export const CATEGORY_LABELS = {
  "levers-torque-balance": "Levers, torque & balance",
  pulleys: "Pulleys",
  "gears-belts-rotation": "Gears, belts & rotation",
  "simple-machines": "Simple machines",
  "work-power-efficiency-motion": "Work, power, efficiency & motion",
  "force-friction-springs": "Force, friction & springs",
  "pressure-hydraulics-fluids": "Pressure, hydraulics & fluids",
  "mechanisms-tools-weight-balance": "Mechanisms, tools & weight balance",
} as const;

export type MechanicalCategory = keyof typeof CATEGORY_LABELS;
export type Difficulty = "easy" | "medium" | "hard";

export const PRINCIPLE_SOURCES = {
  "openstax-torque": {
    label: "OpenStax Physics: Torque",
    url: "https://openstax.org/books/physics/pages/9-2-torque",
  },
  "openstax-simple-machines": {
    label: "OpenStax Physics: Simple Machines",
    url: "https://openstax.org/books/physics/pages/9-3-simple-machines",
  },
  "openstax-work-power": {
    label: "OpenStax Physics: Work, Energy, and Power",
    url: "https://openstax.org/books/physics/pages/9-introduction",
  },
  "openstax-motion": {
    label: "OpenStax Physics: Motion",
    url: "https://openstax.org/books/physics/pages/2-introduction",
  },
  "openstax-forces": {
    label: "OpenStax Physics: Force and Newton's Laws",
    url: "https://openstax.org/books/physics/pages/4-introduction",
  },
  "openstax-friction": {
    label: "OpenStax Physics: Friction",
    url: "https://openstax.org/books/physics/pages/5-1-friction",
  },
  "openstax-springs": {
    label: "OpenStax Physics: Elasticity and Hooke's Law",
    url: "https://openstax.org/books/physics/pages/16-1-hookes-law-stress-and-strain-revisited",
  },
  "openstax-pressure": {
    label: "OpenStax Physics: Pressure",
    url: "https://openstax.org/books/physics/pages/11-3-pressure",
  },
  "openstax-fluids": {
    label: "OpenStax Physics: Fluid Dynamics",
    url: "https://openstax.org/books/physics/pages/12-introduction",
  },
  "openstax-buoyancy": {
    label: "OpenStax Physics: Archimedes' Principle",
    url: "https://openstax.org/books/physics/pages/11-7-archimedes-principle",
  },
  "britannica-gear": {
    label: "Encyclopaedia Britannica: Gear",
    url: "https://www.britannica.com/technology/gear",
  },
  "britannica-linkage": {
    label: "Encyclopaedia Britannica: Linkage",
    url: "https://www.britannica.com/technology/linkage-mechanics",
  },
} as const;

export type PrincipleSource = keyof typeof PRINCIPLE_SOURCES;

export type DiagramSpec =
  | {
      type: "lever";
      fulcrum: number;
      leftArm: number;
      rightArm: number;
      leftLabel: string;
      rightLabel: string;
    }
  | {
      type: "pulley";
      arrangement: "fixed" | "movable" | "block-and-tackle";
      supportingStrands: number;
      loadLabel: string;
      effortLabel: string;
    }
  | {
      type: "gears";
      teethA: number;
      teethB: number;
      connectedBy: "mesh" | "open-belt" | "crossed-belt";
      labelA: string;
      labelB: string;
    }
  | {
      type: "incline";
      rise: number;
      run: number;
      loadLabel: string;
    }
  | {
      type: "spring";
      extension: number;
      forceLabel: string;
    }
  | {
      type: "hydraulic";
      areaA: number;
      areaB: number;
      forceA: number;
    }
  | {
      type: "balance";
      leftLabel: string;
      rightLabel: string;
      state: "level" | "left-down" | "right-down";
    };

export type MechanicalQuestion = {
  id: string;
  prompt: string;
  choices: readonly [string, string, string, string];
  answerIndex: number;
  explanation: string;
  category: MechanicalCategory;
  difficulty: Difficulty;
  sources: readonly PrincipleSource[];
  diagram?: DiagramSpec;
};

export const mechanicalQuestions: readonly MechanicalQuestion[] = [
  {
    id: "MA-001",
    prompt: "A 20 N load is 0.5 m left of a fulcrum. What downward force 1 m to the right will balance it?",
    choices: ["5 N", "10 N", "20 N", "40 N"],
    answerIndex: 1,
    explanation: "Balance requires equal moments: 20 × 0.5 = F × 1, so F = 10 N.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 35, rightArm: 55, leftLabel: "20 N", rightLabel: "?" },
  },
  {
    id: "MA-002",
    prompt: "Which change gives the greatest turning effect from the same force on a spanner?",
    choices: ["Push nearer the nut", "Use a longer spanner", "Push along the handle", "Use a lighter nut"],
    answerIndex: 1,
    explanation: "Torque equals force times perpendicular distance, so a longer lever arm increases torque.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-003",
    prompt: "A seesaw is balanced. One rider moves closer to the pivot while both riders keep the same weight. What happens?",
    choices: ["That rider's side rises", "That rider's side falls", "The seesaw stays level", "Both ends rise"],
    answerIndex: 0,
    explanation: "Moving closer reduces that rider's moment, so the opposite side has the greater turning effect.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 30, rightArm: 45, leftLabel: "rider", rightLabel: "rider" },
  },
  {
    id: "MA-004",
    prompt: "A 60 N force acts 0.2 m from a pivot. What torque does it produce when perpendicular to the lever?",
    choices: ["3 N·m", "12 N·m", "30 N·m", "300 N·m"],
    answerIndex: 1,
    explanation: "Torque is 60 × 0.2 = 12 N·m.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-005",
    prompt: "Two equal downward forces act on opposite sides of a pivot. The left force is twice as far from the pivot. Which way does the lever turn?",
    choices: ["Clockwise", "Anticlockwise", "It remains balanced", "It moves straight down"],
    answerIndex: 1,
    explanation: "The left moment is larger because its lever arm is longer, producing anticlockwise rotation.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-006",
    prompt: "A 15 N force at 0.8 m balances a force at 0.3 m. What is the second force?",
    choices: ["5.625 N", "18 N", "40 N", "60 N"],
    answerIndex: 2,
    explanation: "15 × 0.8 = F × 0.3, giving F = 40 N.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 60, rightArm: 25, leftLabel: "15 N", rightLabel: "?" },
  },
  {
    id: "MA-007",
    prompt: "Why is a door handle normally placed far from the hinges?",
    choices: ["To reduce door mass", "To increase the lever arm", "To increase hinge friction", "To move the centre of mass"],
    answerIndex: 1,
    explanation: "A greater perpendicular distance from the hinge produces more torque for the same force.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-008",
    prompt: "A uniform metre rule is supported exactly at its 50 cm mark. With no other loads, what is its condition?",
    choices: ["Left side falls", "Right side falls", "It balances", "It rotates continuously"],
    answerIndex: 2,
    explanation: "The centre of mass of a uniform rule is at its midpoint, directly above the support.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "balance", leftLabel: "50 cm", rightLabel: "50 cm", state: "level" },
  },
  {
    id: "MA-009",
    prompt: "A 30 N load sits 0.4 m from a pivot. An effort of 10 N balances it. How far is the effort from the pivot?",
    choices: ["0.13 m", "0.4 m", "1.2 m", "3 m"],
    answerIndex: 2,
    explanation: "30 × 0.4 = 10 × d, so d = 1.2 m.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-010",
    prompt: "Which item is a first-class lever, with the pivot between effort and load?",
    choices: ["Wheelbarrow", "Nutcracker", "Scissors", "Tweezers"],
    answerIndex: 2,
    explanation: "Scissors have a pivot between the effort at the handles and the load at the blades.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-011",
    prompt: "A beam is level with 50 N at 2 m left and 25 N at 4 m right of its pivot. What is the net torque?",
    choices: ["0 N·m", "50 N·m clockwise", "100 N·m anticlockwise", "200 N·m clockwise"],
    answerIndex: 0,
    explanation: "Both moments are 100 N·m in opposite directions, so the net torque is zero.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 45, rightArm: 70, leftLabel: "50 N", rightLabel: "25 N" },
  },
  {
    id: "MA-012",
    prompt: "The same force is applied to a lever at 30° and at 90° to the handle. Which application produces more torque?",
    choices: ["30°", "90°", "Both are equal", "Neither produces torque"],
    answerIndex: 1,
    explanation: "Only the perpendicular component creates torque, and it is greatest at 90°.",
    category: "levers-torque-balance",
    difficulty: "hard",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-013",
    prompt: "A balanced lever has a 24 N load 0.25 m from the pivot. If the effort arm is shortened from 1 m to 0.5 m, what effort is now needed?",
    choices: ["3 N", "6 N", "12 N", "48 N"],
    answerIndex: 2,
    explanation: "The load moment is 6 N·m; over 0.5 m the effort must be 12 N.",
    category: "levers-torque-balance",
    difficulty: "hard",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-014",
    prompt: "What is the main ideal advantage of a single fixed pulley?",
    choices: ["It halves the effort", "It changes force direction", "It doubles lifting speed", "It stores energy"],
    answerIndex: 1,
    explanation: "A fixed pulley ideally changes the direction of the applied force without multiplying it.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "fixed", supportingStrands: 1, loadLabel: "load", effortLabel: "pull" },
  },
  {
    id: "MA-015",
    prompt: "An ideal movable pulley supports a load with two rope segments. What effort lifts a 200 N load?",
    choices: ["50 N", "100 N", "200 N", "400 N"],
    answerIndex: 1,
    explanation: "Two supporting rope segments give an ideal mechanical advantage of 2, so effort is 100 N.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "200 N", effortLabel: "?" },
  },
  {
    id: "MA-016",
    prompt: "An ideal block-and-tackle has four rope segments supporting the moving block. Its mechanical advantage is:",
    choices: ["1", "2", "4", "8"],
    answerIndex: 2,
    explanation: "Ideal pulley mechanical advantage equals the number of rope segments supporting the moving load.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "load", effortLabel: "effort" },
  },
  {
    id: "MA-017",
    prompt: "In an ideal two-supporting-strand pulley, how far must the free end move to raise the load 1 m?",
    choices: ["0.5 m", "1 m", "2 m", "4 m"],
    answerIndex: 2,
    explanation: "The effort distance is multiplied by the same factor that the effort force is reduced, so it moves 2 m.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-018",
    prompt: "Why is the actual effort in a pulley system usually greater than the ideal calculation?",
    choices: ["The rope loses mass", "Friction resists motion", "Gravity becomes stronger", "The load gains volume"],
    answerIndex: 1,
    explanation: "Bearing and rope friction reduce efficiency, so extra input force is required.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-friction"],
  },
  {
    id: "MA-019",
    prompt: "A pulley system has ideal mechanical advantage 5. Approximately what effort is needed for a 500 N load if friction is ignored?",
    choices: ["50 N", "100 N", "250 N", "2500 N"],
    answerIndex: 1,
    explanation: "Effort equals load divided by mechanical advantage: 500 ÷ 5 = 100 N.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-020",
    prompt: "A 300 N load is lifted by an actual effort of 120 N. What is the actual mechanical advantage?",
    choices: ["0.4", "2.5", "3.6", "36"],
    answerIndex: 1,
    explanation: "Actual mechanical advantage is load divided by effort: 300 ÷ 120 = 2.5.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-021",
    prompt: "Which action increases the ideal mechanical advantage of a block-and-tackle?",
    choices: ["Use a shorter rope", "Add supporting rope segments", "Use a heavier hook", "Pull faster"],
    answerIndex: 1,
    explanation: "More rope segments sharing the moving load reduce the ideal force needed.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-022",
    prompt: "A load rises 0.5 m while the effort end is pulled 2 m. What is the ideal velocity ratio?",
    choices: ["0.25", "1", "4", "8"],
    answerIndex: 2,
    explanation: "Velocity ratio is effort distance divided by load distance: 2 ÷ 0.5 = 4.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-023",
    prompt: "A four-strand ideal pulley lifts a load at 0.2 m/s. How fast must rope pass through the effort end?",
    choices: ["0.05 m/s", "0.2 m/s", "0.8 m/s", "4 m/s"],
    answerIndex: 2,
    explanation: "The effort end travels four times as fast and far as the load: 4 × 0.2 = 0.8 m/s.",
    category: "pulleys",
    difficulty: "hard",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-024",
    prompt: "If one supporting strand in an ideal pulley carries 80 N tension, what load can four supporting strands hold at rest?",
    choices: ["20 N", "80 N", "240 N", "320 N"],
    answerIndex: 3,
    explanation: "Four equal strand tensions support the load, so total upward force is 4 × 80 = 320 N.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines", "openstax-forces"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "?", effortLabel: "80 N tension" },
  },
  {
    id: "MA-025",
    prompt: "A pulley lifts a 400 N load 2 m while the operator pulls with 120 N through 8 m. What is the efficiency?",
    choices: ["42%", "67%", "83%", "120%"],
    answerIndex: 2,
    explanation: "Output work is 800 J and input work is 960 J; 800 ÷ 960 ≈ 83%.",
    category: "pulleys",
    difficulty: "hard",
    sources: ["openstax-simple-machines", "openstax-work-power"],
  },
  {
    id: "MA-026",
    prompt: "Gear A has 10 teeth and drives gear B with 30 teeth. If A turns at 90 rpm, how fast does B turn?",
    choices: ["30 rpm", "90 rpm", "270 rpm", "900 rpm"],
    answerIndex: 0,
    explanation: "Speed is inversely proportional to tooth count: 90 × 10 ÷ 30 = 30 rpm.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 10, teethB: 30, connectedBy: "mesh", labelA: "90 rpm", labelB: "?" },
  },
  {
    id: "MA-027",
    prompt: "Two external gears mesh directly. If the first turns clockwise, the second turns:",
    choices: ["Clockwise", "Anticlockwise", "Without rotating", "In either direction randomly"],
    answerIndex: 1,
    explanation: "Directly meshing external gears rotate in opposite directions.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-028",
    prompt: "Three external gears form a line. Gear 1 turns clockwise and drives gear 2, which drives gear 3. Gear 3 turns:",
    choices: ["Clockwise", "Anticlockwise", "At zero speed", "Back and forth"],
    answerIndex: 0,
    explanation: "Each mesh reverses direction; two reversals make gear 3 turn like gear 1.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-029",
    prompt: "A 12-tooth gear drives a 48-tooth gear. Compared with the driver, the driven gear has:",
    choices: ["Four times the speed", "One quarter the speed", "The same speed", "Twice the speed"],
    answerIndex: 1,
    explanation: "The driven gear has four times as many teeth, so it rotates at one quarter the speed.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 12, teethB: 48, connectedBy: "mesh", labelA: "driver", labelB: "driven" },
  },
  {
    id: "MA-030",
    prompt: "Two equal pulleys are joined by an uncrossed belt. How do they rotate?",
    choices: ["Same direction, same speed", "Opposite direction, same speed", "Same direction, different speed", "Opposite direction, different speed"],
    answerIndex: 0,
    explanation: "An open belt preserves direction, and equal pulley diameters give equal rotational speed.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 24, teethB: 24, connectedBy: "open-belt", labelA: "A", labelB: "B" },
  },
  {
    id: "MA-031",
    prompt: "Two equal pulleys are joined by a crossed belt. If the driver turns clockwise, the driven pulley turns:",
    choices: ["Clockwise", "Anticlockwise", "Twice as fast clockwise", "It does not turn"],
    answerIndex: 1,
    explanation: "Crossing the belt reverses the driven pulley's direction.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 24, teethB: 24, connectedBy: "crossed-belt", labelA: "clockwise", labelB: "?" },
  },
  {
    id: "MA-032",
    prompt: "A small driving pulley is connected by an open belt to a pulley twice its diameter. The larger pulley rotates:",
    choices: ["Twice as fast, same direction", "Half as fast, same direction", "Half as fast, opposite direction", "At the same speed"],
    answerIndex: 1,
    explanation: "The same belt speed acts at twice the radius, so the larger pulley turns at half the angular speed.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-033",
    prompt: "What is the purpose of an idler gear placed between a driver and a driven gear?",
    choices: ["Change the gear ratio", "Alter direction or spacing without changing the ratio", "Stop all rotation", "Double every tooth count"],
    answerIndex: 1,
    explanation: "An idler can change final direction and bridge distance, but the driver-to-driven ratio remains set by their teeth.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-034",
    prompt: "A 20-tooth driver turns at 150 rpm and drives a 50-tooth gear. What is the driven speed?",
    choices: ["60 rpm", "100 rpm", "375 rpm", "750 rpm"],
    answerIndex: 0,
    explanation: "150 × 20 ÷ 50 = 60 rpm.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-035",
    prompt: "Which gear pair gives the greatest torque increase when the smaller gear is the driver?",
    choices: ["20 teeth driving 20", "20 driving 30", "20 driving 60", "60 driving 20"],
    answerIndex: 2,
    explanation: "The largest driven-to-driver tooth ratio gives the greatest ideal torque multiplication.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-036",
    prompt: "A worm gear commonly allows a large speed reduction because:",
    choices: ["The worm advances the wheel only a small amount per turn", "Both parts have equal diameter", "It removes all friction", "The wheel has no teeth"],
    answerIndex: 0,
    explanation: "Each worm revolution advances the wheel by a small number of teeth, producing a large reduction.",
    category: "gears-belts-rotation",
    difficulty: "hard",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-037",
    prompt: "If a belt slips on a driven pulley, the driven pulley will usually rotate:",
    choices: ["Faster than the ideal speed", "Slower than the ideal speed", "In the opposite direction", "At exactly the ideal speed"],
    answerIndex: 1,
    explanation: "Slip means some belt motion is not transferred, reducing the driven pulley's speed.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear", "openstax-friction"],
  },
  {
    id: "MA-038",
    prompt: "A 15-tooth gear drives a 45-tooth gear on the same shaft as a 10-tooth gear, which drives a 20-tooth output. If the input is 120 rpm, output speed is:",
    choices: ["20 rpm", "40 rpm", "80 rpm", "240 rpm"],
    answerIndex: 0,
    explanation: "First stage: 120 × 15/45 = 40 rpm. Second stage: 40 × 10/20 = 20 rpm.",
    category: "gears-belts-rotation",
    difficulty: "hard",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-039",
    prompt: "An ideal ramp is 5 m long and rises 1 m. Its ideal mechanical advantage is:",
    choices: ["0.2", "1", "5", "25"],
    answerIndex: 2,
    explanation: "For an inclined plane, ideal mechanical advantage is slope length divided by rise: 5 ÷ 1 = 5.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "incline", rise: 1, run: 4.9, loadLabel: "load" },
  },
  {
    id: "MA-040",
    prompt: "Ignoring friction, which ramp requires the least force to raise the same load to the same height?",
    choices: ["The shortest ramp", "The longest ramp", "All require the same force", "A vertical wall"],
    answerIndex: 1,
    explanation: "A longer ramp spreads the same work over more distance, reducing the required force.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-041",
    prompt: "A screw is best described as:",
    choices: ["A rotating inclined plane", "A fixed pulley", "A flexible lever", "A hydraulic piston"],
    answerIndex: 0,
    explanation: "A screw thread is an inclined plane wrapped around a cylinder.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-042",
    prompt: "Which change to a screw makes it advance less distance per turn and usually increases ideal force advantage?",
    choices: ["Coarser thread pitch", "Finer thread pitch", "Shorter handle radius", "Removing the thread"],
    answerIndex: 1,
    explanation: "A finer pitch trades more turning distance for less axial advance, increasing ideal mechanical advantage.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-043",
    prompt: "A wedge converts an input force mainly into forces directed:",
    choices: ["Along its sloping faces", "Only backward", "In a circle", "Straight upward regardless of position"],
    answerIndex: 0,
    explanation: "The wedge's inclined faces redirect the input force outward along the contact surfaces.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-044",
    prompt: "On a wheel and axle, applying effort at the rim of a large wheel to turn a smaller axle provides:",
    choices: ["Force multiplication", "No mechanical effect", "Only a direction change", "A reduction in effort distance"],
    answerIndex: 0,
    explanation: "The large wheel radius creates greater torque at the smaller axle for the applied force.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-torque"],
  },
  {
    id: "MA-045",
    prompt: "A wheel radius is 30 cm and its axle radius is 5 cm. What is the ideal mechanical advantage when effort is applied to the wheel?",
    choices: ["5", "6", "25", "35"],
    answerIndex: 1,
    explanation: "Ideal mechanical advantage is wheel radius divided by axle radius: 30 ÷ 5 = 6.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-046",
    prompt: "Why can no real simple machine be more than 100% efficient?",
    choices: ["It creates extra mass", "Some input energy is dissipated", "Output distance is always zero", "Gravity switches off"],
    answerIndex: 1,
    explanation: "Friction, deformation, and other losses mean useful output energy cannot exceed input energy.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-work-power"],
  },
  {
    id: "MA-047",
    prompt: "A machine has velocity ratio 5 and efficiency 80%. What is its actual mechanical advantage?",
    choices: ["4", "5", "6.25", "400"],
    answerIndex: 0,
    explanation: "Efficiency = MA/VR, so MA = 0.80 × 5 = 4.",
    category: "simple-machines",
    difficulty: "hard",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-048",
    prompt: "Which tool most directly combines two levers and two wedges?",
    choices: ["Scissors", "Single fixed pulley", "Ramp", "Hydraulic jack"],
    answerIndex: 0,
    explanation: "Scissor handles act as levers and the cutting edges act as wedges.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-049",
    prompt: "An ideal machine receives 600 J of work. How much useful work can it deliver?",
    choices: ["Less than 0 J", "Exactly 600 J", "More than 600 J", "Exactly 60 J"],
    answerIndex: 1,
    explanation: "An ideal machine has no losses, so output work equals input work.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-work-power"],
  },
  {
    id: "MA-050",
    prompt: "A jack handle is lengthened while the screw pitch stays the same. The force needed at the handle generally:",
    choices: ["Increases", "Decreases", "Stays exactly the same in all cases", "Becomes zero"],
    answerIndex: 1,
    explanation: "A longer handle increases torque for the same hand force, so less force is needed.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines", "openstax-torque"],
  },
  {
    id: "MA-051",
    prompt: "A 50 N force moves a box 4 m in the force direction. How much work is done?",
    choices: ["12.5 J", "46 J", "200 J", "400 J"],
    answerIndex: 2,
    explanation: "Work equals force times distance in the force direction: 50 × 4 = 200 J.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-052",
    prompt: "A motor does 1,200 J of work in 6 seconds. Its average power is:",
    choices: ["72 W", "200 W", "1,206 W", "7,200 W"],
    answerIndex: 1,
    explanation: "Power is work divided by time: 1,200 ÷ 6 = 200 W.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-053",
    prompt: "Two motors lift identical loads to the same height. Motor A takes half as long as motor B. Motor A has:",
    choices: ["Half the power", "Twice the power", "The same power", "Four times the work"],
    answerIndex: 1,
    explanation: "Both do the same work, but A does it in half the time, so A has twice the power.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-054",
    prompt: "A machine takes in 500 J and gives 350 J of useful output. What is its efficiency?",
    choices: ["30%", "70%", "85%", "143%"],
    answerIndex: 1,
    explanation: "Efficiency is useful output divided by input: 350 ÷ 500 = 70%.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-055",
    prompt: "A trolley moves at constant speed in a straight line. What can be concluded about its net force?",
    choices: ["It is zero", "It points forward", "It points backward", "It continually increases"],
    answerIndex: 0,
    explanation: "Constant velocity means zero acceleration, so the resultant force is zero.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-motion", "openstax-forces"],
  },
  {
    id: "MA-056",
    prompt: "A car increases speed uniformly from 5 m/s to 15 m/s in 5 s. What is its acceleration?",
    choices: ["2 m/s²", "3 m/s²", "4 m/s²", "10 m/s²"],
    answerIndex: 0,
    explanation: "Acceleration is change in velocity divided by time: (15 − 5) ÷ 5 = 2 m/s².",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-motion"],
  },
  {
    id: "MA-057",
    prompt: "At constant speed, a conveyor carries twice as much load through the same vertical height each minute. Required power ideally:",
    choices: ["Halves", "Stays the same", "Doubles", "Quadruples"],
    answerIndex: 2,
    explanation: "Twice the weight means twice the work in the same time, so power doubles.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-058",
    prompt: "A worker pushes horizontally on a wall that does not move. Mechanical work done on the wall is:",
    choices: ["Zero", "Equal to the force", "Maximum", "Negative infinity"],
    answerIndex: 0,
    explanation: "Mechanical work requires displacement; the wall has none.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-059",
    prompt: "A 2 kg object accelerates at 3 m/s². What net force acts on it?",
    choices: ["0.67 N", "1.5 N", "5 N", "6 N"],
    answerIndex: 3,
    explanation: "Newton's second law gives F = ma = 2 × 3 = 6 N.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-forces"],
  },
  {
    id: "MA-060",
    prompt: "A machine outputs 800 W at 80% efficiency. What input power is required?",
    choices: ["640 W", "800 W", "1,000 W", "6,400 W"],
    answerIndex: 2,
    explanation: "Input power is output divided by efficiency: 800 ÷ 0.8 = 1,000 W.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-061",
    prompt: "A wheel makes 120 revolutions in 2 minutes. Its rotational speed is:",
    choices: ["1 rpm", "60 rpm", "120 rpm", "240 rpm"],
    answerIndex: 1,
    explanation: "120 revolutions divided by 2 minutes equals 60 rpm.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-motion"],
  },
  {
    id: "MA-062",
    prompt: "A lift raises a 600 N load by 5 m in 10 s. Ignoring losses, what power is delivered to the load?",
    choices: ["60 W", "120 W", "300 W", "3,000 W"],
    answerIndex: 2,
    explanation: "Work is 600 × 5 = 3,000 J; power is 3,000 ÷ 10 = 300 W.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-063",
    prompt: "A machine's efficiency improves while its input power stays fixed. Its useful output power:",
    choices: ["Decreases", "Increases", "Must stay zero", "Becomes unrelated to input"],
    answerIndex: 1,
    explanation: "Useful output equals efficiency times input, so greater efficiency gives greater useful output.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-work-power"],
  },
  {
    id: "MA-064",
    prompt: "A 10 kg object experiences a net force of 20 N. What is its acceleration?",
    choices: ["0.5 m/s²", "2 m/s²", "10 m/s²", "200 m/s²"],
    answerIndex: 1,
    explanation: "Acceleration is F/m = 20 ÷ 10 = 2 m/s².",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-forces"],
  },
  {
    id: "MA-065",
    prompt: "Which surface pair usually provides the greatest sliding friction?",
    choices: ["Smooth ice on steel", "Oiled metal on metal", "Rough rubber on dry concrete", "Air cushion on glass"],
    answerIndex: 2,
    explanation: "Rough, high-grip dry surfaces generally resist sliding more than lubricated or low-friction pairs.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
  },
  {
    id: "MA-066",
    prompt: "Why are ball bearings used between a shaft and its housing?",
    choices: ["To convert rolling friction into sliding friction", "To reduce friction by replacing sliding with rolling", "To increase the shaft's mass", "To stop heat transfer"],
    answerIndex: 1,
    explanation: "Rolling resistance is generally much smaller than sliding friction.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
  },
  {
    id: "MA-067",
    prompt: "A horizontal pull is gradually increased on a stationary crate. Just before it moves, static friction is:",
    choices: ["Zero", "Opposite and equal to the pull up to its limit", "Always greater than the pull", "In the same direction as the pull"],
    answerIndex: 1,
    explanation: "Static friction adjusts to match the applied force until its maximum value is reached.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-friction"],
  },
  {
    id: "MA-068",
    prompt: "A spring extends 2 cm under a 6 N force and remains within its elastic range. What force would extend it 5 cm?",
    choices: ["2.4 N", "9 N", "15 N", "30 N"],
    answerIndex: 2,
    explanation: "By Hooke's law force is proportional to extension: 6 × 5/2 = 15 N.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 5, forceLabel: "?" },
  },
  {
    id: "MA-069",
    prompt: "Two identical springs support a load in parallel. Compared with one spring, the pair is:",
    choices: ["Less stiff", "Twice as stiff", "Half as stiff", "Unable to support load"],
    answerIndex: 1,
    explanation: "Parallel springs share the load, so their effective spring constant is the sum of both constants.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-springs"],
  },
  {
    id: "MA-070",
    prompt: "What happens after a spring is stretched beyond its elastic limit?",
    choices: ["It must return exactly to its original length", "It may remain permanently deformed", "Its mass becomes zero", "It produces unlimited force"],
    answerIndex: 1,
    explanation: "Beyond the elastic limit, deformation may no longer be fully reversible.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-springs"],
  },
  {
    id: "MA-071",
    prompt: "A box is pulled right with 40 N while friction acts left with 15 N. What is the net horizontal force?",
    choices: ["15 N right", "25 N right", "40 N left", "55 N right"],
    answerIndex: 1,
    explanation: "Opposing forces subtract: 40 − 15 = 25 N to the right.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-forces", "openstax-friction"],
  },
  {
    id: "MA-072",
    prompt: "Increasing the normal force between two dry sliding surfaces usually makes friction:",
    choices: ["Increase", "Decrease to zero", "Reverse direction", "Independent of contact"],
    answerIndex: 0,
    explanation: "The common dry-friction model makes friction proportional to normal force.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
  },
  {
    id: "MA-073",
    prompt: "A compressed spring launches two carts of different mass with equal and opposite forces. Which cart has greater acceleration?",
    choices: ["The heavier cart", "The lighter cart", "Both have zero acceleration", "Both must have equal acceleration"],
    answerIndex: 1,
    explanation: "For the same force, acceleration is inversely proportional to mass.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-forces", "openstax-springs"],
  },
  {
    id: "MA-074",
    prompt: "Why does lubrication reduce wear between moving metal parts?",
    choices: ["It increases direct surface contact", "It forms a film that reduces friction", "It makes both parts heavier", "It eliminates all normal force"],
    answerIndex: 1,
    explanation: "A lubricant separates surface irregularities and reduces direct sliding friction.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
  },
  {
    id: "MA-075",
    prompt: "A spring constant is 200 N/m. What force is required for a 0.03 m extension?",
    choices: ["0.15 N", "6 N", "60 N", "6,667 N"],
    answerIndex: 1,
    explanation: "Hooke's law gives F = kx = 200 × 0.03 = 6 N.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 3, forceLabel: "6 N" },
  },
  {
    id: "MA-076",
    prompt: "A 5 kg block rests on a level floor. A 20 N horizontal force acts, but static friction is also 20 N. The block:",
    choices: ["Accelerates at 4 m/s²", "Moves at constant increasing speed", "Remains at rest", "Accelerates backward"],
    answerIndex: 2,
    explanation: "The forces cancel, so the net force and acceleration are zero; because it started at rest, it stays at rest.",
    category: "force-friction-springs",
    difficulty: "hard",
    sources: ["openstax-forces", "openstax-friction"],
  },
  {
    id: "MA-077",
    prompt: "The same force is applied to two flat pistons. Which piston creates greater pressure on the fluid?",
    choices: ["The larger-area piston", "The smaller-area piston", "Both always create zero pressure", "Area has no effect"],
    answerIndex: 1,
    explanation: "Pressure is force divided by area, so the smaller area produces greater pressure.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-078",
    prompt: "A force of 100 N acts on an area of 0.02 m². What pressure is produced?",
    choices: ["2 Pa", "50 Pa", "2,000 Pa", "5,000 Pa"],
    answerIndex: 3,
    explanation: "Pressure is F/A = 100 ÷ 0.02 = 5,000 Pa.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-079",
    prompt: "A hydraulic input piston has area 2 cm² and the output piston has area 20 cm². An input force of 30 N ideally produces:",
    choices: ["3 N", "30 N", "300 N", "600 N"],
    answerIndex: 2,
    explanation: "Equal pressure gives force in proportion to area: 30 × 20/2 = 300 N.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure"],
    diagram: { type: "hydraulic", areaA: 2, areaB: 20, forceA: 30 },
  },
  {
    id: "MA-080",
    prompt: "In an ideal hydraulic lift, the large piston rises 1 cm. If its area is ten times the small piston's area, the small piston must move:",
    choices: ["0.1 cm", "1 cm", "10 cm", "100 cm"],
    answerIndex: 2,
    explanation: "Equal displaced volume requires the small piston to move ten times farther.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure", "openstax-fluids"],
  },
  {
    id: "MA-081",
    prompt: "Why does water pressure increase with depth in a tank?",
    choices: ["Deeper water has no weight", "More fluid weight lies above", "The tank becomes narrower automatically", "Gravity decreases with depth"],
    answerIndex: 1,
    explanation: "At greater depth, a taller column of fluid contributes weight and therefore pressure.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-082",
    prompt: "Three differently shaped open containers hold the same liquid to the same depth. At equal depth, the fluid pressure is:",
    choices: ["Greatest in the widest container", "Greatest in the narrowest container", "The same in all three", "Determined only by total liquid volume"],
    answerIndex: 2,
    explanation: "Hydrostatic pressure depends on fluid density, gravity, and depth, not container shape.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-083",
    prompt: "An object floats at rest. How does its buoyant force compare with its weight?",
    choices: ["It is smaller", "It is equal", "It is twice as large", "It is zero"],
    answerIndex: 1,
    explanation: "A floating object is in vertical equilibrium, so buoyant force equals weight.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-buoyancy"],
  },
  {
    id: "MA-084",
    prompt: "A solid object is fully submerged and displaces 0.003 m³ of water. The buoyant force equals the:",
    choices: ["Object's volume only", "Weight of 0.003 m³ of water", "Object's mass times its speed", "Pressure at the surface only"],
    answerIndex: 1,
    explanation: "Archimedes' principle states that buoyant force equals the weight of displaced fluid.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-buoyancy"],
  },
  {
    id: "MA-085",
    prompt: "When a pipe narrows and steady incompressible fluid flow continues, fluid speed in the narrow section:",
    choices: ["Decreases", "Increases", "Becomes zero", "Must reverse"],
    answerIndex: 1,
    explanation: "Continuity requires the same volume flow rate, so smaller area means higher speed.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-fluids"],
  },
  {
    id: "MA-086",
    prompt: "Why are hydraulic systems commonly filled with liquid rather than gas?",
    choices: ["Liquids are nearly incompressible", "Liquids have no mass", "Gases cannot exert pressure", "Liquids remove every energy loss"],
    answerIndex: 0,
    explanation: "A nearly incompressible liquid transmits pressure changes reliably through the system.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-087",
    prompt: "A hydraulic brake pedal feels spongy because air entered the line. The best mechanical explanation is:",
    choices: ["Air compresses more than brake fluid", "Air is denser than steel", "Air prevents all pressure", "Brake fluid becomes solid"],
    answerIndex: 0,
    explanation: "Compressible air absorbs pedal travel instead of transmitting it promptly to the brakes.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure"],
  },
  {
    id: "MA-088",
    prompt: "A hydraulic system multiplies force by 12 ideally. If the small piston moves 24 cm, how far does the large piston move?",
    choices: ["2 cm", "12 cm", "24 cm", "288 cm"],
    answerIndex: 0,
    explanation: "The force gain is traded for distance, so the output moves 24 ÷ 12 = 2 cm.",
    category: "pressure-hydraulics-fluids",
    difficulty: "hard",
    sources: ["openstax-pressure", "openstax-simple-machines"],
  },
  {
    id: "MA-089",
    prompt: "A cam rotating at constant speed is commonly used to convert rotary motion into:",
    choices: ["Reciprocating or oscillating motion", "Only faster rotary motion", "Fluid pressure only", "No motion"],
    answerIndex: 0,
    explanation: "A shaped cam pushes a follower through a repeating rise-and-fall or rocking motion.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["britannica-linkage"],
  },
  {
    id: "MA-090",
    prompt: "A crank and connecting rod in a piston engine convert between rotary motion and:",
    choices: ["Reciprocating motion", "Random vibration only", "Hydraulic pressure only", "Static balance"],
    answerIndex: 0,
    explanation: "The crank rotates while the connecting rod drives the piston back and forth.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["britannica-linkage"],
  },
  {
    id: "MA-091",
    prompt: "A ratchet and pawl mechanism is designed mainly to:",
    choices: ["Allow rotation in one direction while resisting reverse motion", "Multiply fluid pressure", "Join two smooth shafts permanently", "Measure temperature"],
    answerIndex: 0,
    explanation: "The pawl rides over teeth one way and catches them against reverse rotation.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-092",
    prompt: "Which tool is most suitable for tightening a hexagonal nut without gripping its corners with teeth?",
    choices: ["Open-ended spanner", "Wood chisel", "Claw hammer", "Hand saw"],
    answerIndex: 0,
    explanation: "A correctly sized spanner applies torque to the nut's flat faces.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-093",
    prompt: "Why should a heavy load be carried close to the body?",
    choices: ["It reduces the moment about the lower back", "It increases the lever arm", "It makes gravity disappear", "It doubles the load mass"],
    answerIndex: 0,
    explanation: "Reducing horizontal distance from the body's pivot points reduces the torque muscles must oppose.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-094",
    prompt: "A tall cabinet is less likely to tip if:",
    choices: ["Its base is wider and heavy items are low", "Its base is narrower and heavy items are high", "All weight is moved to one side", "Its centre of mass is raised"],
    answerIndex: 0,
    explanation: "A wide support base and low centre of mass keep the weight line within the base over a larger tilt.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
  },
  {
    id: "MA-095",
    prompt: "A wheelbarrow carries its load between the wheel axle and the operator's hands. It is which lever class?",
    choices: ["First class", "Second class", "Third class", "Not a lever"],
    answerIndex: 1,
    explanation: "The load lies between the pivot at the wheel and the effort at the handles, making it second class.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
  },
  {
    id: "MA-096",
    prompt: "Pliers with longer handles require less hand force for the same gripping force because they have:",
    choices: ["A longer effort arm", "A shorter effort arm", "No pivot", "Less output torque"],
    answerIndex: 0,
    explanation: "Long handles increase input torque about the pivot for a given hand force.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque", "openstax-simple-machines"],
  },
  {
    id: "MA-097",
    prompt: "A balanced scale has a 2 kg object on the left pan. Ignoring the scale's own imbalance, what mass on the right keeps it level?",
    choices: ["0.5 kg", "1 kg", "2 kg", "4 kg"],
    answerIndex: 2,
    explanation: "Equal arms require equal weights, so an equal 2 kg mass balances the scale.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "balance", leftLabel: "2 kg", rightLabel: "?", state: "level" },
  },
  {
    id: "MA-098",
    prompt: "A load is suspended from two identical vertical ropes and is stationary. If its weight is 600 N, the tension in each rope is:",
    choices: ["150 N", "300 N", "600 N", "1,200 N"],
    answerIndex: 1,
    explanation: "The two equal upward tensions share the 600 N weight, giving 300 N each.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-forces"],
  },
  {
    id: "MA-099",
    prompt: "Which mechanism is best for turning intermittent input into step-by-step one-way rotation?",
    choices: ["Ratchet and pawl", "Fixed pulley", "Smooth open belt", "Hydraulic reservoir"],
    answerIndex: 0,
    explanation: "A ratchet advances tooth by tooth while its pawl prevents backward motion.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["britannica-gear"],
  },
  {
    id: "MA-100",
    prompt: "A 40 kg load is placed 0.6 m from the centreline of a platform. Where should a 60 kg counterweight be placed on the opposite side to balance it?",
    choices: ["0.2 m", "0.4 m", "0.6 m", "0.9 m"],
    answerIndex: 1,
    explanation: "Balance moments using mass because gravity cancels: 40 × 0.6 = 60 × d, so d = 0.4 m.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "hard",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 45, rightArm: 30, leftLabel: "40 kg", rightLabel: "60 kg" },
  },
] as const;
