export const CATEGORY_LABELS = {
  "levers-torque-balance": "Levers, torque & balance",
  pulleys: "Pulleys",
  "gears-belts-rotation": "Gears, belts & rotation",
  "simple-machines": "Simple machines",
  "work-power-efficiency-motion": "Motion, Doppler & work",
  "force-friction-springs": "Force, friction & springs",
  "pressure-hydraulics-fluids": "Pressure, hydraulics & fluids",
  "mechanisms-tools-weight-balance": "Aircraft, boats & mechanisms",
} as const;

export type MechanicalCategory = keyof typeof CATEGORY_LABELS;
export type Difficulty = "easy" | "medium" | "hard";

export const PRINCIPLE_SOURCES = {
  "openstax-torque": {
    label: "OpenStax Physics: Torque",
    url: "https://openstax.org/books/physics/pages/9-2-torque",
  },
  "openstax-simple-machines": {
    label: "OpenStax Physics: Simple Machines",
    url: "https://openstax.org/books/physics/pages/9-3-simple-machines",
  },
  "openstax-work-power": {
    label: "OpenStax Physics: Work, Energy, and Power",
    url: "https://openstax.org/books/physics/pages/9-introduction",
  },
  "openstax-motion": {
    label: "OpenStax Physics: Motion",
    url: "https://openstax.org/books/physics/pages/2-introduction",
  },
  "openstax-forces": {
    label: "OpenStax Physics: Force and Newton's Laws",
    url: "https://openstax.org/books/physics/pages/4-introduction",
  },
  "openstax-friction": {
    label: "OpenStax Physics: Friction",
    url: "https://openstax.org/books/physics/pages/5-1-friction",
  },
  "openstax-springs": {
    label: "OpenStax Physics: Elasticity and Hooke's Law",
    url: "https://openstax.org/books/physics/pages/16-1-hookes-law-stress-and-strain-revisited",
  },
  "openstax-pressure": {
    label: "OpenStax Physics: Pressure",
    url: "https://openstax.org/books/physics/pages/11-3-pressure",
  },
  "openstax-fluids": {
    label: "OpenStax Physics: Fluid Dynamics",
    url: "https://openstax.org/books/physics/pages/12-introduction",
  },
  "openstax-buoyancy": {
    label: "OpenStax Physics: Archimedes' Principle",
    url: "https://openstax.org/books/physics/pages/11-7-archimedes-principle",
  },
  "openstax-doppler": {
    label: "OpenStax Physics: The Doppler Effect",
    url: "https://openstax.org/books/university-physics-volume-1/pages/17-7-the-doppler-effect",
  },
  "britannica-gear": {
    label: "Encyclopaedia Britannica: Gear",
    url: "https://www.britannica.com/technology/gear",
  },
  "britannica-linkage": {
    label: "Encyclopaedia Britannica: Linkage",
    url: "https://www.britannica.com/technology/linkage-mechanics",
  },
} as const;

export type PrincipleSource = keyof typeof PRINCIPLE_SOURCES;

export type DiagramSpec =
  | {
      type: "lever";
      fulcrum: number;
      leftArm: number;
      rightArm: number;
      leftLabel: string;
      rightLabel: string;
    }
  | {
      type: "pulley";
      arrangement: "fixed" | "movable" | "block-and-tackle";
      supportingStrands: number;
      loadLabel: string;
      effortLabel: string;
    }
  | {
      type: "gears";
      teethA: number;
      teethB: number;
      connectedBy: "mesh" | "open-belt" | "crossed-belt";
      labelA: string;
      labelB: string;
    }
  | {
      type: "gears3";
      labelA: string;
      labelB: string;
      labelC: string;
    }
  | {
      type: "incline";
      rise: number;
      run: number;
      loadLabel: string;
    }
  | {
      type: "spring";
      extension: number;
      forceLabel: string;
    }
  | {
      type: "hydraulic";
      areaA: number;
      areaB: number;
      forceA: number;
    }
  | {
      type: "balance";
      leftLabel: string;
      rightLabel: string;
      state: "level" | "left-down" | "right-down";
    }
  | {
      type: "aircraft";
      failedEngine: "left" | "right" | "none";
      caption: string;
    }
  | {
      type: "doppler";
      motion: "toward" | "away" | "pass";
      sourceLabel: string;
      listenerLabel: string;
    }
  | {
      type: "boat";
      rudder: "left" | "right" | "straight";
    }
  | {
      type: "buoyancy";
      state: "float" | "suspend" | "sink";
      objectLabel: string;
    }
  | {
      type: "shadow";
      lightSide: "left" | "right";
      objectHeight: "tall" | "short";
    }
  | {
      type: "spanner";
      forceAt: "near" | "far";
    }
  | {
      type: "wheel";
      diameterA: number;
      diameterB: number;
      labelA: string;
      labelB: string;
    }
  | {
      type: "door";
      handleFar: boolean;
    }
  | {
      type: "cam";
    }
  | {
      type: "beam";
      loadAt: "left" | "centre" | "right";
    };

export type MechanicalQuestion = {
  id: string;
  prompt: string;
  choices: readonly [string, string, string, string];
  answerIndex: number;
  explanation: string;
  category: MechanicalCategory;
  difficulty: Difficulty;
  sources: readonly PrincipleSource[];
  diagram: DiagramSpec;
};

export const mechanicalQuestions: readonly MechanicalQuestion[] = [

  {
    id: "MA-001",
    prompt: "Look at the lever. A 20 N load is on the short arm. Which downward force on the long arm balances it?",
    choices: ["5 N", "10 N", "20 N", "40 N"],
    answerIndex: 1,
    explanation: "Equal moments: 20 × 0.5 = F × 1, so F = 10 N. The diagram shows the shorter load arm and longer effort arm.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 35, rightArm: 55, leftLabel: "20 N", rightLabel: "?" },
  },
  {
    id: "MA-002",
    prompt: "Look at the spanner on the hex nut. Where should you push to get the greatest turning effect with the same force?",
    choices: ["Near the nut", "At the far end of the handle", "Straight down on the nut", "On the hinge pin"],
    answerIndex: 1,
    explanation: "Torque equals force times perpendicular distance from the pivot, so pushing at the far end of the handle gives more turn.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "spanner", forceAt: "far" },
  },
  {
    id: "MA-003",
    prompt: "The seesaw diagram is balanced. If the left rider moves closer to the fulcrum (same weights), what happens?",
    choices: ["Left side rises", "Left side falls", "It stays level", "Both ends rise"],
    answerIndex: 0,
    explanation: "Moving closer reduces that rider's moment, so the opposite side has the greater turning effect and the left side rises.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 30, rightArm: 45, leftLabel: "rider", rightLabel: "rider" },
  },
  {
    id: "MA-004",
    prompt: "In the diagram, equal forces act on both sides, but the left force is farther from the pivot. Which way does the beam turn?",
    choices: ["Clockwise", "Anticlockwise", "It stays balanced", "Straight down"],
    answerIndex: 1,
    explanation: "The left moment is larger because its lever arm is longer, so the beam turns anticlockwise.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 60, rightArm: 30, leftLabel: "F", rightLabel: "F" },
  },
  {
    id: "MA-005",
    prompt: "The door diagram shows the handle far from the hinges. Why is that placement useful?",
    choices: ["It reduces door mass", "It increases the lever arm", "It increases hinge friction", "It moves the centre of mass"],
    answerIndex: 1,
    explanation: "A greater distance from the hinge produces more torque for the same push, so the door opens more easily.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "door", handleFar: true },
  },
  {
    id: "MA-006",
    prompt: "The balance scale is level with equal arm labels. Where is the centre of mass of a uniform metre rule supported at 50 cm?",
    choices: ["Left of centre", "Right of centre", "At the midpoint support", "At one end"],
    answerIndex: 2,
    explanation: "A uniform rule has its centre of mass at the midpoint, so it balances on a support there.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "balance", leftLabel: "50 cm", rightLabel: "50 cm", state: "level" },
  },
  {
    id: "MA-007",
    prompt: "In the lever diagram, 15 N is on the long arm. What force on the short arm balances it?",
    choices: ["5.6 N", "18 N", "40 N", "60 N"],
    answerIndex: 2,
    explanation: "15 × 0.8 = F × 0.3, so F = 40 N. The diagram shows unequal arm lengths.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 60, rightArm: 25, leftLabel: "15 N", rightLabel: "?" },
  },
  {
    id: "MA-008",
    prompt: "The beam diagram shows 50 N left and 25 N right at the labelled distances. What is the net torque?",
    choices: ["0 N·m", "50 N·m clockwise", "100 N·m anticlockwise", "200 N·m clockwise"],
    answerIndex: 0,
    explanation: "Both moments are 100 N·m in opposite directions, so the net torque is zero and the beam stays level.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 45, rightArm: 70, leftLabel: "50 N", rightLabel: "25 N" },
  },
  {
    id: "MA-009",
    prompt: "Compare the two spanner diagrams in your mind: force near the nut versus at the handle end. Which produces more torque?",
    choices: ["Near the nut", "At the handle end", "Both equal", "Neither"],
    answerIndex: 1,
    explanation: "The same force at a larger perpendicular distance from the nut produces more torque.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "spanner", forceAt: "near" },
  },
  {
    id: "MA-010",
    prompt: "The balance pans tip left-down. Which side is heavier (or has the larger moment)?",
    choices: ["Right pan", "Left pan", "They are equal", "Cannot tell"],
    answerIndex: 1,
    explanation: "The lower pan has the greater downward moment, so the left side is heavier or farther out.",
    category: "levers-torque-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "balance", leftLabel: "?", rightLabel: "?", state: "left-down" },
  },
  {
    id: "MA-011",
    prompt: "Scissors are a first-class lever: pivot between effort and load. Which diagram object matches that idea (pivot in the middle)?",
    choices: ["Wheelbarrow", "Nutcracker only", "Seesaw / scissors style", "Tweezers only"],
    answerIndex: 2,
    explanation: "First-class levers have the fulcrum between effort and load, like a seesaw or scissors.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 40, rightArm: 40, leftLabel: "load", rightLabel: "effort" },
  },
  {
    id: "MA-012",
    prompt: "A 30 N load sits 0.4 m from the pivot in the diagram. What effort distance balances it with 10 N?",
    choices: ["0.13 m", "0.4 m", "1.2 m", "3 m"],
    answerIndex: 2,
    explanation: "30 × 0.4 = 10 × d, so d = 1.2 m. The effort arm must be longer than the load arm.",
    category: "levers-torque-balance",
    difficulty: "medium",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 30, rightArm: 70, leftLabel: "30 N", rightLabel: "10 N ?" },
  },
  {
    id: "MA-013",
    prompt: "If the effort arm on a balanced lever is halved (same load), what happens to the needed effort?",
    choices: ["It halves", "It doubles", "It stays the same", "It becomes zero"],
    answerIndex: 1,
    explanation: "Load moment is fixed; halving the effort arm doubles the force needed to keep the same moment.",
    category: "levers-torque-balance",
    difficulty: "hard",
    sources: ["openstax-torque"],
    diagram: { type: "lever", fulcrum: 50, leftArm: 40, rightArm: 20, leftLabel: "load", rightLabel: "effort" },
  },
  {
    id: "MA-014",
    prompt: "The diagram shows a single fixed pulley. What is its main ideal advantage?",
    choices: ["It halves the effort", "It changes force direction", "It doubles lifting speed", "It stores energy"],
    answerIndex: 1,
    explanation: "A fixed pulley ideally changes the direction of the pull without multiplying the force.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "fixed", supportingStrands: 1, loadLabel: "load", effortLabel: "pull" },
  },
  {
    id: "MA-015",
    prompt: "The movable pulley shows two supporting strands. What ideal effort lifts a 200 N load?",
    choices: ["50 N", "100 N", "200 N", "400 N"],
    answerIndex: 1,
    explanation: "Two supporting strands give an ideal mechanical advantage of 2, so effort is about 100 N.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "200 N", effortLabel: "?" },
  },
  {
    id: "MA-016",
    prompt: "Count the supporting strands in the block-and-tackle diagram. Ideal mechanical advantage equals that count. What is it?",
    choices: ["1", "2", "4", "8"],
    answerIndex: 2,
    explanation: "Ideal pulley MA equals the number of rope segments supporting the moving load; here there are four.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "load", effortLabel: "effort" },
  },
  {
    id: "MA-017",
    prompt: "In a two-strand ideal pulley like the diagram, how far must you pull the free end to raise the load 1 m?",
    choices: ["0.5 m", "1 m", "2 m", "4 m"],
    answerIndex: 2,
    explanation: "You trade force for distance: the effort end moves twice as far as the load rises.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "↑1 m", effortLabel: "pull ?" },
  },
  {
    id: "MA-018",
    prompt: "Why is the real effort on a pulley system usually larger than the ideal diagram suggests?",
    choices: ["The rope loses mass", "Friction resists motion", "Gravity gets stronger", "The load gains volume"],
    answerIndex: 1,
    explanation: "Bearing and rope friction reduce efficiency, so you must pull harder than the ideal calculation.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-friction"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 3, loadLabel: "load", effortLabel: "real > ideal" },
  },
  {
    id: "MA-019",
    prompt: "The diagram has four strands. If each strand tension is 80 N at rest, what load can they hold?",
    choices: ["20 N", "80 N", "240 N", "320 N"],
    answerIndex: 3,
    explanation: "Four equal upward tensions support the load: 4 × 80 = 320 N.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines", "openstax-forces"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "?", effortLabel: "80 N each" },
  },
  {
    id: "MA-020",
    prompt: "Which change increases ideal mechanical advantage of the block-and-tackle shown?",
    choices: ["Shorter rope", "More supporting strands", "Heavier hook", "Pull faster"],
    answerIndex: 1,
    explanation: "More rope segments sharing the moving load reduce the ideal force needed.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "load", effortLabel: "effort" },
  },
  {
    id: "MA-021",
    prompt: "Load rises 0.5 m while the free end moves 2 m (same idea as the multi-strand diagram). Ideal velocity ratio?",
    choices: ["0.25", "1", "4", "8"],
    answerIndex: 2,
    explanation: "Velocity ratio is effort distance ÷ load distance: 2 ÷ 0.5 = 4.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "0.5 m up", effortLabel: "2 m pull" },
  },
  {
    id: "MA-022",
    prompt: "A four-strand ideal pulley lifts the load at 0.2 m/s. How fast must rope pass at the effort end?",
    choices: ["0.05 m/s", "0.2 m/s", "0.8 m/s", "4 m/s"],
    answerIndex: 2,
    explanation: "The effort end travels four times as fast as the load: 4 × 0.2 = 0.8 m/s.",
    category: "pulleys",
    difficulty: "hard",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "0.2 m/s", effortLabel: "?" },
  },
  {
    id: "MA-023",
    prompt: "Ideal MA is 5 for a system like the multi-strand diagram. Effort for a 500 N load (ignore friction)?",
    choices: ["50 N", "100 N", "250 N", "2500 N"],
    answerIndex: 1,
    explanation: "Effort = load ÷ MA = 500 ÷ 5 = 100 N.",
    category: "pulleys",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 5, loadLabel: "500 N", effortLabel: "?" },
  },
  {
    id: "MA-024",
    prompt: "Actual effort 120 N lifts 300 N. What is actual mechanical advantage?",
    choices: ["0.4", "2.5", "3.6", "36"],
    answerIndex: 1,
    explanation: "Actual MA = load ÷ effort = 300 ÷ 120 = 2.5.",
    category: "pulleys",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "300 N", effortLabel: "120 N" },
  },
  {
    id: "MA-025",
    prompt: "Output work 800 J, input work 960 J on a pulley lift. Efficiency?",
    choices: ["42%", "67%", "83%", "120%"],
    answerIndex: 2,
    explanation: "Efficiency = output ÷ input = 800 ÷ 960 ≈ 83%.",
    category: "pulleys",
    difficulty: "hard",
    sources: ["openstax-simple-machines", "openstax-work-power"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 4, loadLabel: "400 N", effortLabel: "120 N" },
  },
  {
    id: "MA-026",
    prompt: "Gear A (10 teeth) drives gear B (30 teeth) as shown. If A turns at 90 rpm, how fast is B?",
    choices: ["30 rpm", "90 rpm", "270 rpm", "900 rpm"],
    answerIndex: 0,
    explanation: "Speed is inversely proportional to teeth: 90 × 10 ÷ 30 = 30 rpm.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 10, teethB: 30, connectedBy: "mesh", labelA: "90 rpm", labelB: "?" },
  },
  {
    id: "MA-027",
    prompt: "Two external gears mesh as in the diagram. If the left gear turns clockwise, the right gear turns:",
    choices: ["Clockwise", "Anticlockwise", "Not at all", "Either way"],
    answerIndex: 1,
    explanation: "Directly meshing external gears always rotate in opposite directions.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 20, teethB: 20, connectedBy: "mesh", labelA: "CW", labelB: "?" },
  },
  {
    id: "MA-028",
    prompt: "Three gears mesh in a line (A–B–C). A turns clockwise. Which way does C turn?",
    choices: ["Clockwise", "Anticlockwise", "Stops", "Oscillates"],
    answerIndex: 0,
    explanation: "Each mesh reverses direction. Two reversals make C turn the same way as A.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears3", labelA: "CW", labelB: "idler", labelC: "?" },
  },
  {
    id: "MA-029",
    prompt: "Driver has 12 teeth, driven has 48 (diagram). Driven speed compared with driver?",
    choices: ["4× faster", "¼ as fast", "Same speed", "2× faster"],
    answerIndex: 1,
    explanation: "Four times the teeth means one quarter the rotational speed.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 12, teethB: 48, connectedBy: "mesh", labelA: "driver", labelB: "driven" },
  },
  {
    id: "MA-030",
    prompt: "Look at the open (uncrossed) belt joining equal pulleys A and B. How do they rotate?",
    choices: ["Same direction, same speed", "Opposite, same speed", "Same direction, different speed", "Opposite, different speed"],
    answerIndex: 0,
    explanation: "An open belt keeps the same direction; equal diameters give equal speed.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 24, teethB: 24, connectedBy: "open-belt", labelA: "A", labelB: "B" },
  },
  {
    id: "MA-031",
    prompt: "Look at the crossed belt joining equal pulleys. Driver A turns clockwise → driven B turns:",
    choices: ["Clockwise", "Anticlockwise", "Twice as fast CW", "Does not turn"],
    answerIndex: 1,
    explanation: "Crossing the belt reverses the driven pulley's direction.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 24, teethB: 24, connectedBy: "crossed-belt", labelA: "CW", labelB: "?" },
  },
  {
    id: "MA-032",
    prompt: "Small driver pulley, open belt to a pulley twice the diameter. Larger pulley rotates:",
    choices: ["2× fast, same way", "½ as fast, same way", "½ as fast, opposite", "Same speed"],
    answerIndex: 1,
    explanation: "Same belt speed at twice the radius means half the angular speed; open belt keeps direction.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 16, teethB: 32, connectedBy: "open-belt", labelA: "small", labelB: "large" },
  },
  {
    id: "MA-033",
    prompt: "Gear B sits between A and C as an idler. What does the idler mainly change?",
    choices: ["The gear ratio of A to C", "Direction or spacing, not the A–C ratio", "It stops rotation", "It doubles every tooth count"],
    answerIndex: 1,
    explanation: "An idler can reverse final direction and bridge distance; the A-to-C ratio still depends on A and C teeth.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears3", labelA: "driver", labelB: "idler", labelC: "driven" },
  },
  {
    id: "MA-034",
    prompt: "20-tooth driver at 150 rpm drives a 50-tooth gear. Driven speed?",
    choices: ["60 rpm", "100 rpm", "375 rpm", "750 rpm"],
    answerIndex: 0,
    explanation: "150 × 20 ÷ 50 = 60 rpm.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 20, teethB: 50, connectedBy: "mesh", labelA: "150 rpm", labelB: "?" },
  },
  {
    id: "MA-035",
    prompt: "Which pair gives the greatest torque increase when the smaller gear drives?",
    choices: ["20 driving 20", "20 driving 30", "20 driving 60", "60 driving 20"],
    answerIndex: 2,
    explanation: "Largest driven-to-driver tooth ratio gives the greatest ideal torque multiplication.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 20, teethB: 60, connectedBy: "mesh", labelA: "driver", labelB: "driven" },
  },
  {
    id: "MA-036",
    prompt: "Two wheels share one axle (diagram). If they roll without slip on flat ground, which statement is true?",
    choices: ["They must have equal diameter", "The larger wheel travels farther per turn", "Only the small wheel turns", "Axle speed is zero"],
    answerIndex: 1,
    explanation: "One turn of the shared axle moves each rim by its own circumference, so the larger wheel covers more ground per turn if free—on a fixed axle vehicle both are forced to the same rpm, which is why different diameters scrub.",
    category: "gears-belts-rotation",
    difficulty: "hard",
    sources: ["openstax-motion"],
    diagram: { type: "wheel", diameterA: 40, diameterB: 70, labelA: "small", labelB: "large" },
  },
  {
    id: "MA-037",
    prompt: "In the three-gear line, A clockwise makes B anticlockwise. B drives C, so C is:",
    choices: ["Clockwise", "Anticlockwise", "Locked", "Faster only"],
    answerIndex: 0,
    explanation: "B is opposite to A; C is opposite to B, so C matches A.",
    category: "gears-belts-rotation",
    difficulty: "medium",
    sources: ["britannica-gear"],
    diagram: { type: "gears3", labelA: "CW", labelB: "ACW", labelC: "?" },
  },
  {
    id: "MA-038",
    prompt: "Open (uncrossed) belt from small pulley A to larger pulley B. Direction of B compared with A?",
    choices: ["Same direction", "Opposite direction", "No motion", "Random"],
    answerIndex: 0,
    explanation: "An open belt preserves rotation direction between the two pulleys.",
    category: "gears-belts-rotation",
    difficulty: "easy",
    sources: ["britannica-gear"],
    diagram: { type: "gears", teethA: 18, teethB: 36, connectedBy: "open-belt", labelA: "driver", labelB: "driven" },
  },
  {
    id: "MA-039",
    prompt: "The inclined plane shows rise and run. Ideal MA is roughly run÷rise. For rise 1 and run 4, ideal MA is about:",
    choices: ["0.25", "1", "4", "5"],
    answerIndex: 2,
    explanation: "Ideal mechanical advantage of a frictionless incline equals length of slope over height, about run÷rise here = 4.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "incline", rise: 1, run: 4, loadLabel: "box" },
  },
  {
    id: "MA-040",
    prompt: "On the incline diagram, why does a gentle slope make lifting easier?",
    choices: ["Gravity disappears", "You trade a longer path for less force", "The box loses mass", "Friction becomes zero always"],
    answerIndex: 1,
    explanation: "Work is similar; a longer distance lets you use a smaller force to raise the same height.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-work-power"],
    diagram: { type: "incline", rise: 2, run: 6, loadLabel: "load" },
  },
  {
    id: "MA-041",
    prompt: "Wheel and axle: large wheel, small axle. Turning the large wheel to lift a rope on the axle mainly:",
    choices: ["Increases needed force", "Reduces needed force", "Removes all friction", "Stops rotation"],
    answerIndex: 1,
    explanation: "A larger effort radius than load radius multiplies torque, so less effort force is needed.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "wheel", diameterA: 70, diameterB: 30, labelA: "wheel", labelB: "axle" },
  },
  {
    id: "MA-042",
    prompt: "The cam diagram shows a follower on top. As the cam lobe passes under, the follower:",
    choices: ["Moves sideways only", "Rises and falls", "Spins with the cam", "Locks forever"],
    answerIndex: 1,
    explanation: "A rotating cam with a lobe pushes the follower up, then lets it drop—turning rotation into reciprocating motion.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["britannica-linkage"],
    diagram: { type: "cam" },
  },
  {
    id: "MA-043",
    prompt: "A wedge is like two inclined planes back to back. Its main job in tools is to:",
    choices: ["Store fuel", "Split or separate material with a sideways force", "Measure time", "Create electricity"],
    answerIndex: 1,
    explanation: "A wedge converts an input push into a large splitting force along its sides.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "incline", rise: 3, run: 5, loadLabel: "split" },
  },
  {
    id: "MA-044",
    prompt: "Screw = incline wrapped around a cylinder. Finer thread (more turns per length) usually means:",
    choices: ["Less force advantage", "More force advantage, more turns", "No holding power", "Higher speed only"],
    answerIndex: 1,
    explanation: "A finer thread is a gentler incline, so more turns for the same advance and a greater ideal force advantage.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "incline", rise: 1, run: 8, loadLabel: "thread" },
  },
  {
    id: "MA-045",
    prompt: "Class 2 lever idea (load between fulcrum and effort): which everyday tool matches?",
    choices: ["Seesaw", "Wheelbarrow", "Tweezers", "Scissors only"],
    answerIndex: 1,
    explanation: "In a wheelbarrow the wheel is the fulcrum, the load sits in the tray, and you lift at the handles.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "lever", fulcrum: 30, leftArm: 20, rightArm: 70, leftLabel: "wheel", rightLabel: "effort" },
  },
  {
    id: "MA-046",
    prompt: "Class 3 lever (effort between fulcrum and load): which matches tweezers?",
    choices: ["Wheelbarrow", "Crowbar", "Tweezers / fishing rod style", "Seesaw"],
    answerIndex: 2,
    explanation: "Tweezers put effort between the pivot and the tip load, trading force for larger tip motion.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-simple-machines"],
    diagram: { type: "lever", fulcrum: 25, leftArm: 15, rightArm: 55, leftLabel: "pivot", rightLabel: "load" },
  },
  {
    id: "MA-047",
    prompt: "On the incline, mechanical advantage falls if friction rises. Why?",
    choices: ["Gravity increases", "Some input work is wasted as heat", "The slope shortens", "Mass becomes energy"],
    answerIndex: 1,
    explanation: "Friction dissipates energy, so more effort is needed than the ideal calculation.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines", "openstax-friction"],
    diagram: { type: "incline", rise: 2, run: 5, loadLabel: "box" },
  },
  {
    id: "MA-048",
    prompt: "Ideal machines never give free energy. What do they trade?",
    choices: ["Force for distance (or vice versa)", "Mass for time", "Colour for heat", "Charge for spin"],
    answerIndex: 0,
    explanation: "Work in ≈ work out ideally; a machine that multiplies force makes you move farther.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-work-power"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "force↓", effortLabel: "path↑" },
  },
  {
    id: "MA-049",
    prompt: "Single fixed pulley MA is about 1. Movable pulley with two strands is about:",
    choices: ["0", "1", "2", "10"],
    answerIndex: 2,
    explanation: "Two supporting strands share the load, so ideal MA ≈ 2.",
    category: "simple-machines",
    difficulty: "easy",
    sources: ["openstax-simple-machines"],
    diagram: { type: "pulley", arrangement: "movable", supportingStrands: 2, loadLabel: "load", effortLabel: "½" },
  },
  {
    id: "MA-050",
    prompt: "The beam with a centre load on two supports: each support ideally carries about:",
    choices: ["All the load", "Half the load", "None of the load", "Twice the load"],
    answerIndex: 1,
    explanation: "For a symmetric centre load on equal supports, each support takes roughly half the weight.",
    category: "simple-machines",
    difficulty: "medium",
    sources: ["openstax-forces"],
    diagram: { type: "beam", loadAt: "centre" },
  },
  {
    id: "MA-051",
    prompt: "The twin-engine plane flies forward. The RIGHT engine fails (marked). Which way does the nose tend to yaw?",
    choices: ["Left (toward the good engine)", "Right (toward the failed engine)", "Straight only", "Straight up"],
    answerIndex: 1,
    explanation: "The working left engine still pushes forward on the left side, so asymmetric thrust yaws the nose toward the failed (right) engine.",
    category: "work-power-efficiency-motion",
    difficulty: "hard",
    sources: ["openstax-forces", "openstax-motion"],
    diagram: { type: "aircraft", failedEngine: "right", caption: "right engine failed · which way yaw?" },
  },
  {
    id: "MA-052",
    prompt: "Same idea: LEFT engine fails on the twin-engine plane. The nose tends to yaw:",
    choices: ["Left (toward failed engine)", "Right (toward good engine)", "Down only", "No yaw"],
    answerIndex: 0,
    explanation: "Thrust on the right side only swings the nose left, toward the failed engine.",
    category: "work-power-efficiency-motion",
    difficulty: "hard",
    sources: ["openstax-forces", "openstax-motion"],
    diagram: { type: "aircraft", failedEngine: "left", caption: "left engine failed · which way yaw?" },
  },
  {
    id: "MA-053",
    prompt: "Ambulance approaches the listener (diagram). Compared with the siren at rest, the pitch you hear is:",
    choices: ["Higher", "Lower", "The same", "Silent"],
    answerIndex: 0,
    explanation: "When the source moves toward you, wave fronts bunch up and the heard frequency rises (Doppler effect).",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-doppler"],
    diagram: { type: "doppler", motion: "toward", sourceLabel: "siren", listenerLabel: "you" },
  },
  {
    id: "MA-054",
    prompt: "Ambulance drives away from the listener. The pitch you hear is:",
    choices: ["Higher", "Lower", "Unchanged", "Only louder"],
    answerIndex: 1,
    explanation: "When the source recedes, wave fronts stretch and the heard frequency falls.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-doppler"],
    diagram: { type: "doppler", motion: "away", sourceLabel: "siren", listenerLabel: "you" },
  },
  {
    id: "MA-055",
    prompt: "As the ambulance passes you (diagram), the pitch change is typically:",
    choices: ["High then suddenly lower", "Always rising", "Always falling", "No change ever"],
    answerIndex: 0,
    explanation: "Pitch is higher while approaching and drops as the source passes and recedes.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-doppler"],
    diagram: { type: "doppler", motion: "pass", sourceLabel: "siren", listenerLabel: "you" },
  },
  {
    id: "MA-056",
    prompt: "Both engines run equally on the twin plane. Ideal yaw from thrust alone?",
    choices: ["Strong left yaw", "Strong right yaw", "No thrust yaw", "Always spins"],
    answerIndex: 2,
    explanation: "Equal thrust on both sides produces no net yawing moment from the engines.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-forces"],
    diagram: { type: "aircraft", failedEngine: "none", caption: "both engines running" },
  },
  {
    id: "MA-057",
    prompt: "Work = force × distance in the force direction. Pushing a box 2 m with 50 N (same line) does:",
    choices: ["25 J", "50 J", "100 J", "200 J"],
    answerIndex: 2,
    explanation: "Work = 50 × 2 = 100 J when force and displacement align.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
    diagram: { type: "incline", rise: 1, run: 4, loadLabel: "50 N" },
  },
  {
    id: "MA-058",
    prompt: "Same work done in half the time means power is:",
    choices: ["Halved", "Doubled", "Unchanged", "Zero"],
    answerIndex: 1,
    explanation: "Power is work ÷ time, so half the time doubles power for the same work.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
    diagram: { type: "pulley", arrangement: "fixed", supportingStrands: 1, loadLabel: "work", effortLabel: "faster" },
  },
  {
    id: "MA-059",
    prompt: "Efficiency cannot exceed 100% in a real machine because:",
    choices: ["Friction and other losses", "Gravity reverses", "Mass disappears", "Time stops"],
    answerIndex: 0,
    explanation: "Some input energy always becomes heat or sound; output work is less than input.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-work-power"],
    diagram: { type: "pulley", arrangement: "block-and-tackle", supportingStrands: 3, loadLabel: "out", effortLabel: "in" },
  },
  {
    id: "MA-060",
    prompt: "A boat moves forward with rudder turned to the boat's right (starboard). The stern tends to swing:",
    choices: ["Left", "Right", "Straight up", "No effect"],
    answerIndex: 1,
    explanation: "Water hitting an angled rudder pushes the stern the way the rudder faces; rudder right swings stern right and bows left.",
    category: "work-power-efficiency-motion",
    difficulty: "hard",
    sources: ["openstax-fluids", "openstax-forces"],
    diagram: { type: "boat", rudder: "right" },
  },
  {
    id: "MA-061",
    prompt: "Boat rudder centred (straight). Ideal steering effect from the rudder alone?",
    choices: ["Hard left turn", "Hard right turn", "No rudder turn", "Spins in place"],
    answerIndex: 2,
    explanation: "A centred rudder does not create a sideways steering force.",
    category: "work-power-efficiency-motion",
    difficulty: "easy",
    sources: ["openstax-fluids"],
    diagram: { type: "boat", rudder: "straight" },
  },
  {
    id: "MA-062",
    prompt: "Rudder angled to the boat's left. The bow tends to go:",
    choices: ["Left", "Right", "Straight only", "Backward"],
    answerIndex: 0,
    explanation: "Rudder left pushes the stern left, so the bow yaws left.",
    category: "work-power-efficiency-motion",
    difficulty: "hard",
    sources: ["openstax-fluids", "openstax-forces"],
    diagram: { type: "boat", rudder: "left" },
  },
  {
    id: "MA-063",
    prompt: "Kinetic energy depends on speed squared. Doubling speed (same mass) multiplies KE by:",
    choices: ["2", "3", "4", "½"],
    answerIndex: 2,
    explanation: "KE = ½mv², so doubling v multiplies KE by four.",
    category: "work-power-efficiency-motion",
    difficulty: "medium",
    sources: ["openstax-work-power"],
    diagram: { type: "wheel", diameterA: 40, diameterB: 40, labelA: "v", labelB: "2v" },
  },
  {
    id: "MA-064",
    prompt: "The spring stretches 4 cm under the labelled load. If force doubles (Hooke's law range), extension becomes about:",
    choices: ["1 cm", "2 cm", "8 cm", "16 cm"],
    answerIndex: 2,
    explanation: "Within the elastic limit, extension is proportional to force, so double force → double extension.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 4, forceLabel: "F" },
  },
  {
    id: "MA-065",
    prompt: "Spring shows 2 cm extension under F. Same spring, same F but two identical springs in parallel share load. Each extends about:",
    choices: ["4 cm", "2 cm", "1 cm", "0"],
    answerIndex: 2,
    explanation: "Parallel springs share the force, so each takes about half and extends about half as much.",
    category: "force-friction-springs",
    difficulty: "hard",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 2, forceLabel: "F shared" },
  },
  {
    id: "MA-066",
    prompt: "Heavier box on the same rough floor. Static friction you must overcome to start sliding usually:",
    choices: ["Decreases", "Increases", "Becomes zero", "Depends only on colour"],
    answerIndex: 1,
    explanation: "Friction scales with the normal force; a heavier box presses harder, so starting friction is larger.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
    diagram: { type: "incline", rise: 1, run: 8, loadLabel: "heavy" },
  },
  {
    id: "MA-067",
    prompt: "On a gentle incline the box stays at rest. Friction here is acting:",
    choices: ["Down the slope only", "Up the slope, balancing the downhill component", "Horizontally only", "Not at all"],
    answerIndex: 1,
    explanation: "Static friction can act up the plane to cancel the component of weight down the slope.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-friction", "openstax-forces"],
    diagram: { type: "incline", rise: 2, run: 7, loadLabel: "rest" },
  },
  {
    id: "MA-068",
    prompt: "Newton's third law: you push the wall, the wall pushes you. Forces are:",
    choices: ["Equal and opposite", "Unequal", "Only on the wall", "Only gravity"],
    answerIndex: 0,
    explanation: "Action and reaction forces are equal in size, opposite in direction, on different bodies.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-forces"],
    diagram: { type: "beam", loadAt: "centre" },
  },
  {
    id: "MA-069",
    prompt: "A spring returns to its original length after the load is removed (diagram idea). It was loaded:",
    choices: ["Beyond breaking point", "Within the elastic limit", "Into plastic flow only", "With zero force"],
    answerIndex: 1,
    explanation: "Elastic behaviour means the spring recovers its shape after the load is removed.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 3, forceLabel: "F" },
  },
  {
    id: "MA-070",
    prompt: "Rougher surfaces usually mean:",
    choices: ["Less friction", "More friction", "No normal force", "Negative mass"],
    answerIndex: 1,
    explanation: "Rougher contact generally increases the friction coefficient.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
    diagram: { type: "incline", rise: 3, run: 4, loadLabel: "rough" },
  },
  {
    id: "MA-071",
    prompt: "Force sensor reads weight on Earth. In freefall (ignore air), apparent weight is about:",
    choices: ["Double", "Unchanged", "Near zero", "Infinite"],
    answerIndex: 2,
    explanation: "A scale in freefall falls with you, so it reads near zero apparent weight.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-forces"],
    diagram: { type: "spring", extension: 0.5, forceLabel: "~0" },
  },
  {
    id: "MA-072",
    prompt: "To slide a crate, you need to overcome static friction first. Once sliding, kinetic friction is often:",
    choices: ["Higher than static", "Lower than static", "Exactly zero", "Infinite"],
    answerIndex: 1,
    explanation: "Kinetic friction is usually less than the maximum static friction that blocked the start of motion.",
    category: "force-friction-springs",
    difficulty: "medium",
    sources: ["openstax-friction"],
    diagram: { type: "incline", rise: 1, run: 5, loadLabel: "crate" },
  },
  {
    id: "MA-073",
    prompt: "Two springs identical; series stack under one load. Total extension vs one spring alone?",
    choices: ["About half", "About the same", "About double", "Zero"],
    answerIndex: 2,
    explanation: "In series each spring takes the full load, so total extension is about twice one spring.",
    category: "force-friction-springs",
    difficulty: "hard",
    sources: ["openstax-springs"],
    diagram: { type: "spring", extension: 6, forceLabel: "F series" },
  },
  {
    id: "MA-074",
    prompt: "Pushing a wall that does not move: work done on the wall is:",
    choices: ["Large", "Zero (no displacement)", "Negative mass", "Infinite"],
    answerIndex: 1,
    explanation: "Work needs displacement in the force direction; a static wall means zero work on the wall.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-work-power"],
    diagram: { type: "door", handleFar: true },
  },
  {
    id: "MA-075",
    prompt: "Mass unchanged, net force doubles. Acceleration:",
    choices: ["Halves", "Doubles", "Unchanged", "Becomes zero"],
    answerIndex: 1,
    explanation: "Newton's second law: a = F/m, so double net force doubles acceleration.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-forces"],
    diagram: { type: "aircraft", failedEngine: "none", caption: "net force → acceleration" },
  },
  {
    id: "MA-076",
    prompt: "Lubricating a machine mainly reduces:",
    choices: ["Mass", "Friction", "Gravity", "Volume"],
    answerIndex: 1,
    explanation: "Lubricants separate surfaces and cut friction losses.",
    category: "force-friction-springs",
    difficulty: "easy",
    sources: ["openstax-friction"],
    diagram: { type: "gears", teethA: 20, teethB: 20, connectedBy: "mesh", labelA: "oil", labelB: "help" },
  },
  {
    id: "MA-077",
    prompt: "Hydraulic diagram: small piston area A, large piston 4A. Ideal force on the large piston if small gets 20 N?",
    choices: ["5 N", "20 N", "80 N", "320 N"],
    answerIndex: 2,
    explanation: "Pressure is equal ideally: F/A constant, so 20 × 4 = 80 N on the large side.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure", "openstax-fluids"],
    diagram: { type: "hydraulic", areaA: 1, areaB: 4, forceA: 20 },
  },
  {
    id: "MA-078",
    prompt: "Object floats as in the buoyancy diagram. Average density vs water?",
    choices: ["Greater than water", "Less than water", "Exactly zero", "Infinite"],
    answerIndex: 1,
    explanation: "Floating objects displace a weight of fluid equal to their weight; their average density is less than the fluid.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-buoyancy"],
    diagram: { type: "buoyancy", state: "float", objectLabel: "wood" },
  },
  {
    id: "MA-079",
    prompt: "Object sinks (diagram). Average density vs water?",
    choices: ["Less than water", "Equal only", "Greater than water", "Zero"],
    answerIndex: 2,
    explanation: "If it sinks, its weight exceeds the maximum buoyant force; average density is greater than the fluid.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-buoyancy"],
    diagram: { type: "buoyancy", state: "sink", objectLabel: "steel" },
  },
  {
    id: "MA-080",
    prompt: "Object suspended mid-water (neutral buoyancy). Densities are:",
    choices: ["Object denser", "Object less dense", "About equal", "Undefined"],
    answerIndex: 2,
    explanation: "Suspended neutrally means weight equals buoyant force, so average densities match.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-buoyancy"],
    diagram: { type: "buoyancy", state: "suspend", objectLabel: "sub" },
  },
  {
    id: "MA-081",
    prompt: "Pressure in a liquid at rest increases with:",
    choices: ["Depth", "Colour", "Only width of tank", "Only time of day"],
    answerIndex: 0,
    explanation: "Hydrostatic pressure rises with depth: P = ρgh above atmospheric at the surface.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
    diagram: { type: "buoyancy", state: "suspend", objectLabel: "depth" },
  },
  {
    id: "MA-082",
    prompt: "Same force, smaller contact area → pressure:",
    choices: ["Decreases", "Increases", "Unchanged", "Becomes negative"],
    answerIndex: 1,
    explanation: "Pressure = force ÷ area, so a sharper tip (small area) makes higher pressure.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
    diagram: { type: "incline", rise: 4, run: 2, loadLabel: "tip" },
  },
  {
    id: "MA-083",
    prompt: "Hydraulic jack multiplies force but the small piston must move:",
    choices: ["A shorter distance", "A longer distance", "Not at all", "Sideways only"],
    answerIndex: 1,
    explanation: "Work is conserved ideally; smaller force side travels farther.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-fluids", "openstax-work-power"],
    diagram: { type: "hydraulic", areaA: 1, areaB: 5, forceA: 10 },
  },
  {
    id: "MA-084",
    prompt: "Squeezing a closed fluid (Pascal): pressure change is transmitted:",
    choices: ["Only upward", "Only to the nearest wall", "Throughout the fluid", "Nowhere"],
    answerIndex: 2,
    explanation: "Pascal's principle: a pressure change in a confined fluid is felt throughout the fluid.",
    category: "pressure-hydraulics-fluids",
    difficulty: "easy",
    sources: ["openstax-pressure"],
    diagram: { type: "hydraulic", areaA: 2, areaB: 2, forceA: 15 },
  },
  {
    id: "MA-085",
    prompt: "A dam is thicker at the bottom mainly because:",
    choices: ["Water pressure is greater at depth", "Waves only hit the top", "Concrete floats there", "Fish push harder"],
    answerIndex: 0,
    explanation: "Hydrostatic pressure grows with depth, so the base must resist a larger load.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-pressure"],
    diagram: { type: "buoyancy", state: "suspend", objectLabel: "dam" },
  },
  {
    id: "MA-086",
    prompt: "Airfoil idea: faster flow over the top (Bernoulli) tends to make pressure above the wing:",
    choices: ["Higher", "Lower", "Vacuum absolute", "Irrelevant"],
    answerIndex: 1,
    explanation: "Faster airflow is linked with lower pressure; lower pressure above helps produce lift.",
    category: "pressure-hydraulics-fluids",
    difficulty: "hard",
    sources: ["openstax-fluids"],
    diagram: { type: "aircraft", failedEngine: "none", caption: "lift from pressure difference" },
  },
  {
    id: "MA-087",
    prompt: "Hydraulic areas 1 : 3. Input 30 N on small side → ideal output force:",
    choices: ["10 N", "30 N", "90 N", "270 N"],
    answerIndex: 2,
    explanation: "Force scales with area: 30 × 3 = 90 N.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-fluids"],
    diagram: { type: "hydraulic", areaA: 1, areaB: 3, forceA: 30 },
  },
  {
    id: "MA-088",
    prompt: "Hot air balloon rises because the balloon's average density becomes:",
    choices: ["Greater than air", "Less than surrounding air", "Equal to steel", "Infinite"],
    answerIndex: 1,
    explanation: "Heating lowers the density of the enclosed air so buoyant force can exceed weight.",
    category: "pressure-hydraulics-fluids",
    difficulty: "medium",
    sources: ["openstax-buoyancy"],
    diagram: { type: "buoyancy", state: "float", objectLabel: "balloon" },
  },
  {
    id: "MA-089",
    prompt: "Shadow diagram: sun on the left, tall object. The shadow falls mainly to the:",
    choices: ["Left", "Right", "Straight up", "Nowhere"],
    answerIndex: 1,
    explanation: "Light rays travel in straight lines; an object blocks light and casts a shadow on the opposite side from the sun.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-motion"],
    diagram: { type: "shadow", lightSide: "left", objectHeight: "tall" },
  },
  {
    id: "MA-090",
    prompt: "Sun on the right of a short object. Shadow is on the:",
    choices: ["Right", "Left", "Top only", "Inside the sun"],
    answerIndex: 1,
    explanation: "The shadow lies opposite the light source.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-motion"],
    diagram: { type: "shadow", lightSide: "right", objectHeight: "short" },
  },
  {
    id: "MA-091",
    prompt: "Taller object, same sun angle (diagram style). Shadow length is:",
    choices: ["Shorter", "Longer", "Zero always", "Independent of height"],
    answerIndex: 1,
    explanation: "At the same sun elevation, a taller object casts a longer shadow.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-motion"],
    diagram: { type: "shadow", lightSide: "left", objectHeight: "tall" },
  },
  {
    id: "MA-092",
    prompt: "Cam and follower: one full cam turn typically makes the follower:",
    choices: ["One rise-fall cycle (for a single lobe)", "Spin forever faster", "Never move", "Move only sideways"],
    answerIndex: 0,
    explanation: "A single-lobe cam produces one lift cycle per revolution.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["britannica-linkage"],
    diagram: { type: "cam" },
  },
  {
    id: "MA-093",
    prompt: "Beam load on the left support side. Which support carries more load?",
    choices: ["Left support", "Right support", "Neither", "Only the sky"],
    answerIndex: 0,
    explanation: "A load nearer one support puts more force on that nearer support.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-forces"],
    diagram: { type: "beam", loadAt: "left" },
  },
  {
    id: "MA-094",
    prompt: "Beam load on the right. Which support takes more?",
    choices: ["Left", "Right", "Equal always", "None"],
    answerIndex: 1,
    explanation: "The nearer (right) support carries the larger share.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "medium",
    sources: ["openstax-forces"],
    diagram: { type: "beam", loadAt: "right" },
  },
  {
    id: "MA-095",
    prompt: "Spanner: same force at the far end vs near the nut. Far end is better for loosening because:",
    choices: ["Less torque", "More torque", "Less friction everywhere", "The nut gets lighter"],
    answerIndex: 1,
    explanation: "Larger lever arm increases torque on the nut.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "spanner", forceAt: "far" },
  },
  {
    id: "MA-096",
    prompt: "Door handle near the hinges (diagram). Opening feels harder because:",
    choices: ["Lever arm is small", "Door mass doubles", "Hinges vanish", "Gravity reverses"],
    answerIndex: 0,
    explanation: "A short distance from the hinge means less torque for the same push.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "door", handleFar: false },
  },
  {
    id: "MA-097",
    prompt: "Balance scale tips right-down. Which pan has the greater moment?",
    choices: ["Left", "Right", "Equal", "Neither"],
    answerIndex: 1,
    explanation: "The descending side has the greater turning moment.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["openstax-torque"],
    diagram: { type: "balance", leftLabel: "A", rightLabel: "B", state: "right-down" },
  },
  {
    id: "MA-098",
    prompt: "Twin-engine aircraft: if the right engine fails mid-flight, a pilot counters yaw mainly with:",
    choices: ["More right thrust only", "Rudder (and trim) opposite the yaw", "Turning off the good engine", "Opening windows"],
    answerIndex: 1,
    explanation: "Rudder (and related controls) create a yawing moment to oppose asymmetric thrust.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "hard",
    sources: ["openstax-forces"],
    diagram: { type: "aircraft", failedEngine: "right", caption: "use rudder against yaw" },
  },
  {
    id: "MA-099",
    prompt: "Linkages can change the direction of motion. A cam converts rotation mainly into:",
    choices: ["Pure continuous spin of the follower", "Up-and-down (reciprocating) motion", "Random noise only", "Magnetic fields"],
    answerIndex: 1,
    explanation: "Cams are classic converters from rotary motion to reciprocating follower motion.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "easy",
    sources: ["britannica-linkage"],
    diagram: { type: "cam" },
  },
  {
    id: "MA-100",
    prompt: "Two wheels fixed on one axle must share rpm. If diameters differ on a straight road without a differential, the result is often:",
    choices: ["Perfect rolling both", "Scrubbing / slip on one or both", "Infinite speed", "No friction ever"],
    answerIndex: 1,
    explanation: "Different rolling radii want different ground speeds at the same rpm, so tyres scrub unless a differential allows different wheel speeds.",
    category: "mechanisms-tools-weight-balance",
    difficulty: "hard",
    sources: ["openstax-motion", "britannica-gear"],
    diagram: { type: "wheel", diameterA: 35, diameterB: 55, labelA: "L", labelB: "R" },
  },
];
