import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { generateOpiBank } from '../app/opi/content/generator.ts';

const outputPath = fileURLToPath(
  new URL('../app/opi/content/bank.generated.ts', import.meta.url),
);

function renderBank() {
  const bank = generateOpiBank();
  return [
    "import type { OpiStatement } from './model';",
    '',
    '// Generated deterministically from generator.ts. Do not edit this file by hand.',
    `export const OPI_BANK = ${JSON.stringify(bank, null, 2)} as const satisfies readonly OpiStatement[];`,
    '',
  ].join('\n');
}

const expected = renderBank();

if (process.argv.includes('--write')) {
  writeFileSync(outputPath, expected);
  console.log(`Wrote ${outputPath}`);
} else {
  const checkedIn = readFileSync(outputPath, 'utf8');
  assert.equal(
    checkedIn,
    expected,
    'bank.generated.ts differs from the deterministic authored source',
  );
  console.log('OPI generated bank is deterministic and current.');
}
